import { calculate401kCalculator } from '../retirement/401k-calculator.js';

export const fourZeroOneKCalculatorConfig = {
  title: '401(k) Retirement Details',
  currency: 'USD',
  currencySymbol: '$',
  calculateFn: calculate401kCalculator,
  primaryResult: {
    key: 'finalBalance',
    label: 'Total 401(k) Balance at Retirement',
  },
  ratioBarItems: [
    { key: 'totalEmployeeContributions', label: 'Employee Contributions', colorClass: 'bg-primary' },
    { key: 'totalEmployerMatch', label: 'Employer Match ("Free Money")', colorClass: 'bg-semantic-up' },
    { key: 'totalGrowth', label: 'Compound Investment Growth', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'yearsInvested', label: 'Years Invested Until Retirement' },
    { key: 'totalEmployeeContributions', label: 'Total Employee Contributions' },
    { key: 'totalEmployerMatch', label: 'Total Employer Match Contributions', class: 'text-semantic-up' },
    { key: 'totalContributions', label: 'Total Combined Contributions' },
    { key: 'totalGrowth', label: 'Total Compound Investment Growth' },
    { key: 'finalBalance', label: 'Total Final 401(k) Nest Egg Balance', isTotal: true },
  ],
  inputs: [
    {
      id: 'annualSalary',
      type: 'number',
      label: 'Annual Gross Salary ($)',
      min: 20000,
      max: 500000,
      step: 2500,
      prefix: '$',
      minLabel: '$20K',
      maxLabel: '$500K',
      default: 90000,
    },
    {
      id: 'currentAge',
      type: 'number',
      label: 'Current Age (Years)',
      min: 18,
      max: 64,
      step: 1,
      suffix: 'Yrs',
      minLabel: '18 Yrs',
      maxLabel: '64 Yrs',
      default: 30,
    },
    {
      id: 'retirementAge',
      type: 'number',
      label: 'Target Retirement Age (Years)',
      min: 50,
      max: 75,
      step: 1,
      suffix: 'Yrs',
      minLabel: '50 Yrs',
      maxLabel: '75 Yrs',
      default: 65,
    },
    {
      id: 'contributionPercent',
      type: 'number',
      label: 'Employee Contribution Rate (%)',
      min: 1,
      max: 50,
      step: 1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '50%',
      default: 8,
    },
    {
      id: 'employerMatchPercent',
      type: 'number',
      label: 'Employer Match Rate (%)',
      min: 0,
      max: 100,
      step: 5,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '100%',
      default: 50,
    },
    {
      id: 'employerMatchLimit',
      type: 'number',
      label: 'Employer Match Salary Cap (%)',
      min: 0,
      max: 15,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '15%',
      default: 6,
    },
    {
      id: 'currentBalance',
      type: 'number',
      label: 'Current 401(k) Balance ($)',
      min: 0,
      max: 1000000,
      step: 2500,
      prefix: '$',
      minLabel: '$0',
      maxLabel: '$1M',
      default: 25000,
    },
    {
      id: 'expectedReturn',
      type: 'number',
      label: 'Expected Investment Growth (%)',
      min: 2,
      max: 15,
      step: 0.5,
      suffix: '%',
      minLabel: '2%',
      maxLabel: '15%',
      default: 7,
    },
  ],
  hasAmortizationTable: false,
};