import { calculate401kCalculator } from '../retirement/401k-calculator.js';

export const FOUR_ZERO_ONE_K_CONFIG = {
  id: '401k-calculator',
  title: '401(k) Retirement Calculator',
  category: 'Retirement Calculators',
  categorySlug: 'retirement',
  defaultSalary: 90000,
  defaultAge: 30,
  defaultRetirementAge: 65,
  defaultReturn: 7.0,

  presets: [
    {
      id: 'standard_match_50_6',
      title: '🏢 Standard Corporate Match (50% up to 6%)',
      description: 'Typical US employer match offering 50% match on employee salary contributions up to 6%.',
      values: {
        annualSalary: 90000,
        currentAge: 30,
        retirementAge: 65,
        contributionPercent: 8,
        employerMatchPercent: 50,
        employerMatchLimit: 6,
        currentBalance: 25000,
        expectedReturn: 7,
        annualSalaryIncrease: 3,
      },
    },
    {
      id: 'generous_match_100_5',
      title: '🌟 Generous Employer Match (100% up to 5%)',
      description: 'Top-tier tech/consulting employer match offering 100% dollar-for-dollar match up to 5%.',
      values: {
        annualSalary: 120000,
        currentAge: 28,
        retirementAge: 65,
        contributionPercent: 10,
        employerMatchPercent: 100,
        employerMatchLimit: 5,
        currentBalance: 40000,
        expectedReturn: 7.5,
        annualSalaryIncrease: 4,
      },
    },
    {
      id: 'max_irs_contributor',
      title: '🚀 Max IRS Contributor ($23.5k Annual Cap)',
      description: 'High earner maximizing the full annual IRS 401(k) elective deferral limit.',
      values: {
        annualSalary: 180000,
        currentAge: 35,
        retirementAge: 65,
        contributionPercent: 15,
        employerMatchPercent: 50,
        employerMatchLimit: 6,
        currentBalance: 120000,
        expectedReturn: 7,
        annualSalaryIncrease: 3,
      },
    },
    {
      id: 'catch_up_age_50',
      title: '👵 Age 50+ Catch-Up Contributor ($31k Cap)',
      description: 'Older worker taking advantage of the additional $7,500 IRS catch-up allowance.',
      values: {
        annualSalary: 140000,
        currentAge: 52,
        retirementAge: 67,
        contributionPercent: 20,
        employerMatchPercent: 50,
        employerMatchLimit: 6,
        currentBalance: 350000,
        expectedReturn: 6.5,
        annualSalaryIncrease: 2.5,
      },
    },
  ],

  benchmarks: {
    irsBaseLimit2025: 23500,
    irsCatchUpLimit2025: 7500,
    irsMaxTotalLimit2025: 69000,
    avgStockMarketReturn: 7.0,
    avgSalaryGrowth: 3.0,
  },
};

export const fourZeroOneKCalculatorConfig = {
  ...FOUR_ZERO_ONE_K_CONFIG,
  currency: 'USD',
  currencySymbol: '$',
  calculateFn: calculate401kCalculator,
  primaryResult: {
    key: 'finalBalance',
    label: 'Total 401(k) Balance at Retirement',
  },
  ratioBarItems: [
    { key: 'totalEmployeeContributions', label: 'Employee Contributions', colorClass: 'bg-primary' },
    { key: 'totalEmployerMatch', label: 'Employer Match ("Free Money")', colorClass: 'bg-semantic-up' },
    { key: 'totalGrowth', label: 'Compound Investment Growth', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'yearsInvested', label: 'Years Invested Until Retirement' },
    { key: 'totalEmployeeContributions', label: 'Total Employee Contributions' },
    { key: 'totalEmployerMatch', label: 'Total Employer Match Contributions', class: 'text-semantic-up' },
    { key: 'totalContributions', label: 'Total Combined Contributions' },
    { key: 'totalGrowth', label: 'Total Compound Investment Growth' },
    { key: 'finalBalance', label: 'Total Final 401(k) Nest Egg Balance', isTotal: true },
  ],
  inputs: [
    {
      id: 'annualSalary',
      type: 'number',
      label: 'Annual Gross Salary ($)',
      min: 20000,
      max: 500000,
      step: 2500,
      prefix: '$',
      minLabel: '$20K',
      maxLabel: '$500K',
      default: 90000,
    },
    {
      id: 'currentAge',
      type: 'number',
      label: 'Current Age (Years)',
      min: 18,
      max: 64,
      step: 1,
      suffix: 'Yrs',
      minLabel: '18 Yrs',
      maxLabel: '64 Yrs',
      default: 30,
    },
    {
      id: 'retirementAge',
      type: 'number',
      label: 'Target Retirement Age (Years)',
      min: 50,
      max: 75,
      step: 1,
      suffix: 'Yrs',
      minLabel: '50 Yrs',
      maxLabel: '75 Yrs',
      default: 65,
    },
    {
      id: 'contributionPercent',
      type: 'number',
      label: 'Employee Contribution Rate (%)',
      min: 1,
      max: 50,
      step: 1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '50%',
      default: 8,
    },
    {
      id: 'employerMatchPercent',
      type: 'number',
      label: 'Employer Match Rate (%)',
      min: 0,
      max: 100,
      step: 5,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '100%',
      default: 50,
    },
    {
      id: 'employerMatchLimit',
      type: 'number',
      label: 'Employer Match Salary Cap (%)',
      min: 0,
      max: 15,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '15%',
      default: 6,
    },
    {
      id: 'currentBalance',
      type: 'number',
      label: 'Current 401(k) Balance ($)',
      min: 0,
      max: 1000000,
      step: 2500,
      prefix: '$',
      minLabel: '$0',
      maxLabel: '$1M',
      default: 25000,
    },
    {
      id: 'expectedReturn',
      type: 'number',
      label: 'Expected Investment Growth (%)',
      min: 2,
      max: 15,
      step: 0.5,
      suffix: '%',
      minLabel: '2%',
      maxLabel: '15%',
      default: 7,
    },
  ],
  hasAmortizationTable: false,
};