import { calculate503020BudgetCalculator } from '../salary/50-30-20-budget-calculator.js';

export const BUDGET_PRESETS = [
  {
    id: 'young_graduate',
    name: 'Young Professional (₹40K)',
    description: '₹40K/mo Take-Home, ₹20K Needs (50%), ₹12K Wants (30%), ₹8K Savings (20%)',
    badge: 'Entry Level',
    values: {
      monthlyIncome: 40000,
      ruleFramework: '50_30_20',
      actualRent: 12000,
      actualGroceries: 4000,
      actualUtilities: 2000,
      actualInsurance: 1000,
      actualTransport: 1000,
      actualDining: 4000,
      actualEntertainment: 3000,
      actualShopping: 3000,
      actualVacation: 2000,
      actualInvestments: 6000,
      actualEmergencyFund: 2000,
      expectedReturnRate: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'metro_family',
    name: 'Metro Family (₹1.5L)',
    description: '₹1.5L/mo Take-Home, Higher Rent & Household Expenses in Tier-1 City',
    badge: 'Family Budget',
    values: {
      monthlyIncome: 150000,
      ruleFramework: '60_20_20',
      actualRent: 45000,
      actualGroceries: 20000,
      actualUtilities: 10000,
      actualInsurance: 8000,
      actualTransport: 7000,
      actualDining: 12000,
      actualEntertainment: 8000,
      actualShopping: 6000,
      actualVacation: 4000,
      actualInvestments: 22000,
      actualEmergencyFund: 8000,
      expectedReturnRate: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'dual_income',
    name: 'Dual Income No Kids (₹2.5L)',
    description: '₹2.5L/mo Combined Income, Strong Savings & Discretionary Lifestyle',
    badge: 'DINK Profile',
    values: {
      monthlyIncome: 250000,
      ruleFramework: '50_30_20',
      actualRent: 60000,
      actualGroceries: 25000,
      actualUtilities: 15000,
      actualInsurance: 12000,
      actualTransport: 13000,
      actualDining: 25000,
      actualEntertainment: 18000,
      actualShopping: 20000,
      actualVacation: 12000,
      actualInvestments: 40000,
      actualEmergencyFund: 10000,
      expectedReturnRate: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'fire_saver',
    name: 'Aggressive FIRE Saver (₹1.2L)',
    description: '₹1.2L/mo Income with 40% Savings Rate for Early Retirement',
    badge: 'FIRE Movement',
    values: {
      monthlyIncome: 120000,
      ruleFramework: '40_20_40',
      actualRent: 24000,
      actualGroceries: 12000,
      actualUtilities: 5000,
      actualInsurance: 4000,
      actualTransport: 3000,
      actualDining: 8000,
      actualEntertainment: 6000,
      actualShopping: 6000,
      actualVacation: 4000,
      actualInvestments: 40000,
      actualEmergencyFund: 8000,
      expectedReturnRate: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'debt_turnaround',
    name: 'Debt Recovery Model (₹80K)',
    description: '₹80K/mo Income, 70% Essential Costs & High Loan Repayment',
    badge: 'Debt Repayment',
    values: {
      monthlyIncome: 80000,
      ruleFramework: '70_20_10',
      actualRent: 30000,
      actualGroceries: 12000,
      actualUtilities: 6000,
      actualInsurance: 4000,
      actualTransport: 4000,
      actualDining: 6000,
      actualEntertainment: 4000,
      actualShopping: 3000,
      actualVacation: 3000,
      actualInvestments: 6000,
      actualEmergencyFund: 2000,
      expectedReturnRate: 10,
      currencySymbol: '₹',
    },
  },
  {
    id: 'executive_hni',
    name: 'Executive Wealth Builder (₹4.0L)',
    description: '₹4.0L/mo Take-Home, ₹1.2L/mo Monthly Equity Investments',
    badge: 'High Earner',
    values: {
      monthlyIncome: 400000,
      ruleFramework: '50_30_20',
      actualRent: 90000,
      actualGroceries: 35000,
      actualUtilities: 20000,
      actualInsurance: 20000,
      actualTransport: 15000,
      actualDining: 35000,
      actualEntertainment: 25000,
      actualShopping: 35000,
      actualVacation: 25000,
      actualInvestments: 80000,
      actualEmergencyFund: 20000,
      expectedReturnRate: 12,
      currencySymbol: '₹',
    },
  },
];

export const budget503020CalculatorConfig = {
  title: '50/30/20 Budget Calculator & 10-Year Wealth Projection',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculate503020BudgetCalculator,
  presets: BUDGET_PRESETS,
  defaultMonthlyIncome: 100000,
  defaultRuleFramework: '50_30_20',
  defaultExpectedReturnRate: 12,
  primaryResult: {
    key: 'totalActualSavings',
    label: 'Monthly Savings & Investments',
  },
  ratioBarItems: [
    { key: 'totalActualNeeds', label: 'Essential Needs', colorClass: 'bg-primary' },
    { key: 'totalActualWants', label: 'Discretionary Wants', colorClass: 'bg-amber-500' },
    { key: 'totalActualSavings', label: 'Savings & Investments', colorClass: 'bg-emerald-500' },
  ],
  summaryItems: [
    { key: 'totalActualSavings', label: 'Total Monthly Savings & Investments', isTotal: true },
    { key: 'totalActualNeeds', label: 'Total Essential Needs Outflow' },
    { key: 'totalActualWants', label: 'Total Discretionary Lifestyle Outflow' },
    { key: 'unallocatedCash', label: 'Unallocated Monthly Balance' },
    { key: 'tenYearActualCorpus', label: '10-Year Compound Wealth Projection' },
  ],
  inputs: [
    {
      id: 'monthlyIncome',
      type: 'number',
      label: 'Monthly Take-Home Income (Post-Tax)',
      min: 5000,
      max: 10000000,
      step: 5000,
      prefix: '₹',
      default: 100000,
    },
    {
      id: 'expectedReturnRate',
      type: 'number',
      label: 'Expected Investment Return (CAGR %)',
      min: 0,
      max: 30,
      step: 0.5,
      suffix: '%',
      default: 12,
    },
  ],
};
