/**
 * Refinance & Balance Transfer Savings Calculator Configuration Module
 * 
 * Defines metadata, input boundaries, classifications, reference bands, and illustrative valuation presets.
 */

export const BALANCE_TRANSFER_CONFIG = {
  metadata: {
    title: 'Refinance & Balance Transfer Savings Calculator',
    slug: 'balance-transfer-calculator',
    category: 'loans',
    categoryName: 'Loan & EMI Calculators',
    lastUpdated: '2026-08-09',
    financialAuthority: 'Consumer Loan Refinancing & Interest Optimization Standard',
    disclosure: 'Refinancing savings estimations are illustrative scenario models. Actual lender processing fees, balance transfer charges, foreclosure penalties, taxes, and final interest rates depend on individual bank agreements and credit evaluation.',
  },

  financialMethodology: 'Net Savings = Current Remaining Total Outflow - (Refinanced Total Outflow + Upfront Outlay Fees). For financed fees, fees are embedded in the new principal and EMI without double counting. Break-even is computed via month-by-month cumulative cash-flow comparison.',

  defaultInputs: {
    outstandingPrincipal: 3000000,
    currentInterestRatePercent: 9.5,
    remainingTenureMonths: 180,
    newInterestRatePercent: 8.4,
    newTenureMonths: 180,
    processingFeePercent: 0.5,
    processingFeeFixed: 0,
    transferFeePercent: 0,
    transferFeeFixed: 0,
    foreclosurePenaltyPercent: 0,
    foreclosurePenaltyFixed: 0,
    financeFeesIntoLoan: false,
  },

  scenarios: {
    homeLoanRateReduction: {
      id: 'homeLoanRateReduction',
      title: 'Home Loan Interest Rate Switching',
      description: 'Switch ₹50 Lakhs home loan from 9.5% to 8.4% APR with 15 years remaining.',
      outstandingPrincipal: 5000000,
      currentInterestRatePercent: 9.5,
      remainingTenureMonths: 180,
      newInterestRatePercent: 8.4,
      newTenureMonths: 180,
      processingFeePercent: 0.5,
      processingFeeFixed: 0,
      transferFeePercent: 0,
      transferFeeFixed: 0,
      foreclosurePenaltyPercent: 0,
      foreclosurePenaltyFixed: 0,
      financeFeesIntoLoan: false,
    },
    personalLoanBalanceTransfer: {
      id: 'personalLoanBalanceTransfer',
      title: 'Personal Loan Balance Transfer',
      description: 'Transfer high-interest ₹5 Lakhs personal loan from 16% to 11.5% APR.',
      outstandingPrincipal: 500000,
      currentInterestRatePercent: 16,
      remainingTenureMonths: 48,
      newInterestRatePercent: 11.5,
      newTenureMonths: 48,
      processingFeePercent: 1,
      processingFeeFixed: 0,
      transferFeePercent: 0.5,
      transferFeeFixed: 0,
      foreclosurePenaltyPercent: 1,
      foreclosurePenaltyFixed: 0,
      financeFeesIntoLoan: true,
    },
    carLoanRefinancing: {
      id: 'carLoanRefinancing',
      title: 'Car Loan Refinancing',
      description: 'Refinance ₹8 Lakhs auto loan from 11% to 8.8% APR with 36 months remaining.',
      outstandingPrincipal: 800000,
      currentInterestRatePercent: 11,
      remainingTenureMonths: 36,
      newInterestRatePercent: 8.8,
      newTenureMonths: 36,
      processingFeePercent: 0.75,
      processingFeeFixed: 0,
      transferFeePercent: 0,
      transferFeeFixed: 0,
      foreclosurePenaltyPercent: 0,
      foreclosurePenaltyFixed: 0,
      financeFeesIntoLoan: false,
    },
    shortTenureHighFeeRefinance: {
      id: 'shortTenureHighFeeRefinance',
      title: 'Short Tenure High-Fee Scenario (Unfavorable)',
      description: 'Short remaining tenure where high upfront fees exceed projected interest savings.',
      outstandingPrincipal: 300000,
      currentInterestRatePercent: 12,
      remainingTenureMonths: 12,
      newInterestRatePercent: 11.5,
      newTenureMonths: 12,
      processingFeePercent: 2,
      processingFeeFixed: 0,
      transferFeePercent: 1,
      transferFeeFixed: 0,
      foreclosurePenaltyPercent: 1,
      foreclosurePenaltyFixed: 0,
      financeFeesIntoLoan: false,
    },
  },

  fieldLimits: {
    outstandingPrincipal: { min: 10000, max: 100000000, step: 50000, label: 'Outstanding Loan Principal (₹ / $)' },
    currentInterestRatePercent: { min: 0.1, max: 50, step: 0.1, label: 'Current Interest Rate (% p.a.)' },
    remainingTenureMonths: { min: 1, max: 360, step: 6, label: 'Remaining Tenure (Months)' },
    newInterestRatePercent: { min: 0.1, max: 50, step: 0.1, label: 'New Interest Rate (% p.a.)' },
    newTenureMonths: { min: 1, max: 360, step: 6, label: 'New Loan Tenure (Months)' },
    processingFeePercent: { min: 0, max: 10, step: 0.1, label: 'Processing Fee (%)' },
    processingFeeFixed: { min: 0, max: 500000, step: 1000, label: 'Processing Fee Fixed (₹ / $)' },
    transferFeePercent: { min: 0, max: 10, step: 0.1, label: 'Balance Transfer Fee (%)' },
    transferFeeFixed: { min: 0, max: 500000, step: 1000, label: 'Balance Transfer Fee Fixed (₹ / $)' },
    foreclosurePenaltyPercent: { min: 0, max: 10, step: 0.1, label: 'Prepayment / Foreclosure Fee (%)' },
    foreclosurePenaltyFixed: { min: 0, max: 500000, step: 1000, label: 'Prepayment / Foreclosure Fee Fixed (₹ / $)' },
  },
};
