import { calculateBurnRateRunwayCalculator } from '../business/burn-rate-runway-calculator.js';

export const BURN_RUNWAY_PRESETS = [
  {
    id: 'pre_seed',
    name: 'Pre-Seed Startup (₹25L Cash)',
    description: '₹25L Angel Round, ₹3.5L Gross Burn, ₹3.0L Net Burn (8.3 Mo Runway)',
    badge: 'Pre-Seed',
    values: {
      cashBalance: 2500000,
      monthlyRevenue: 50000,
      monthlyPayroll: 250000,
      monthlyMarketing: 50000,
      monthlyServers: 20000,
      monthlyOffice: 20000,
      monthlyOtherExpenses: 10000,
      monthlyRevGrowthPct: 10,
      monthlyExpGrowthPct: 3,
      targetSafetyMonths: 6,
      currencySymbol: '₹',
    },
  },
  {
    id: 'seed_saas',
    name: 'Seed Stage SaaS (₹1.5 Cr Cash)',
    description: '₹1.5 Cr Treasury, ₹13.6L Gross Burn, ₹4L MRR, 15.6 Mo Runway',
    badge: 'Seed Stage',
    values: {
      cashBalance: 15000000,
      monthlyRevenue: 400000,
      monthlyPayroll: 900000,
      monthlyMarketing: 250000,
      monthlyServers: 100000,
      monthlyOffice: 80000,
      monthlyOtherExpenses: 30000,
      monthlyRevGrowthPct: 8,
      monthlyExpGrowthPct: 3,
      targetSafetyMonths: 6,
      currencySymbol: '₹',
    },
  },
  {
    id: 'series_a',
    name: 'Series A Scaleup (₹5.0 Cr Cash)',
    description: '₹5.0 Cr Growth Capital, ₹71L Gross Burn, ₹25L Revenue, 10.9 Mo Runway',
    badge: 'Series A',
    values: {
      cashBalance: 50000000,
      monthlyRevenue: 2500000,
      monthlyPayroll: 4500000,
      monthlyMarketing: 1500000,
      monthlyServers: 500000,
      monthlyOffice: 400000,
      monthlyOtherExpenses: 200000,
      monthlyRevGrowthPct: 12,
      monthlyExpGrowthPct: 4,
      targetSafetyMonths: 6,
      currencySymbol: '₹',
    },
  },
  {
    id: 'profitable_bootstrapped',
    name: 'Profitable SaaS (Default Alive)',
    description: '₹50L Reserves, ₹12L Revenue > ₹9.0L Expenses (+₹3L Monthly FCF)',
    badge: 'Cash Flow +',
    values: {
      cashBalance: 5000000,
      monthlyRevenue: 1200000,
      monthlyPayroll: 600000,
      monthlyMarketing: 150000,
      monthlyServers: 80000,
      monthlyOffice: 50000,
      monthlyOtherExpenses: 20000,
      monthlyRevGrowthPct: 5,
      monthlyExpGrowthPct: 2,
      targetSafetyMonths: 6,
      currencySymbol: '₹',
    },
  },
  {
    id: 'distressed_urgent',
    name: 'Bridge Needed (<3 Mo Critical)',
    description: '₹15L Remaining Cash, ₹8.2L Burn, 2.4 Mo to Zero Cash Date',
    badge: 'Urgent Bridge',
    values: {
      cashBalance: 1500000,
      monthlyRevenue: 200000,
      monthlyPayroll: 600000,
      monthlyMarketing: 100000,
      monthlyServers: 50000,
      monthlyOffice: 50000,
      monthlyOtherExpenses: 20000,
      monthlyRevGrowthPct: 3,
      monthlyExpGrowthPct: 0,
      targetSafetyMonths: 6,
      currencySymbol: '₹',
    },
  },
  {
    id: 'deeptech_rd',
    name: 'DeepTech & Hardware R&D (₹3.0 Cr)',
    description: '₹3.0 Cr Grant/Seed, Pre-Revenue Lab Phase, 10.0 Mo Pure R&D Runway',
    badge: 'Pre-Revenue R&D',
    values: {
      cashBalance: 30000000,
      monthlyRevenue: 0,
      monthlyPayroll: 1800000,
      monthlyMarketing: 200000,
      monthlyServers: 500000,
      monthlyOffice: 300000,
      monthlyOtherExpenses: 200000,
      monthlyRevGrowthPct: 0,
      monthlyExpGrowthPct: 2,
      targetSafetyMonths: 6,
      currencySymbol: '₹',
    },
  },
];

export const burnRateRunwayCalculatorConfig = {
  title: 'Startup Burn Rate & Runway Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateBurnRateRunwayCalculator,
  presets: BURN_RUNWAY_PRESETS,
  defaultCashBalance: 5000000,
  defaultMonthlyRevenue: 400000,
  defaultTargetSafetyMonths: 6,
  primaryResult: {
    key: 'staticRunwayMonths',
    label: 'Cash Runway (Months)',
  },
  ratioBarItems: [
    { key: 'payroll', label: 'Payroll & Salaries', colorClass: 'bg-primary' },
    { key: 'marketing', label: 'Marketing & CAC', colorClass: 'bg-indigo-500' },
    { key: 'servers', label: 'Servers & SaaS Tools', colorClass: 'bg-amber-500' },
    { key: 'office', label: 'Office & Admin', colorClass: 'bg-emerald-500' },
  ],
  summaryItems: [
    { key: 'staticRunwayMonths', label: 'Static Cash Runway (Months)', isTotal: true },
    { key: 'netBurn', label: 'Net Monthly Burn Rate' },
    { key: 'grossBurn', label: 'Gross Monthly Operating Expenses' },
    { key: 'monthlyRevenue', label: 'Monthly Cash Inflow / Revenue' },
    { key: 'cashBalance', label: 'Total Liquid Cash Reserves' },
  ],
  inputs: [
    {
      id: 'cashBalance',
      type: 'number',
      label: 'Current Bank Cash Reserves',
      min: 0,
      max: 1000000000,
      step: 100000,
      prefix: '₹',
      default: 5000000,
    },
    {
      id: 'monthlyRevenue',
      type: 'number',
      label: 'Monthly Revenue / Collections',
      min: 0,
      max: 500000000,
      step: 50000,
      prefix: '₹',
      default: 400000,
    },
    {
      id: 'monthlyRevGrowthPct',
      type: 'number',
      label: 'MoM Revenue Growth Rate (%)',
      min: -50,
      max: 100,
      step: 1,
      suffix: '%',
      default: 5,
    },
  ],
};
