/**
 * Configuration module for Cap Rate (Capitalization Rate) Calculator
 */

export const CAP_RATE_CONFIG = {
  meta: {
    title: 'Cap Rate Calculator (Capitalization Rate)',
    description: 'Calculate Net Operating Income (NOI), Capitalization Rate (Cap Rate %), implied property valuation at target cap rates, operating expense ratios, and mortgage rate spreads.',
    category: 'real-estate',
    categoryName: 'Real Estate & Property Calculators',
    slug: 'cap-rate-calculator',
    route: '/tools/real-estate/cap-rate-calculator',
  },

  defaultInputs: {
    propertyValue: 10000000, // ₹1 Crore
    monthlyRent: 65000,
    otherIncomeAnnual: 20000,
    vacancyRatePct: 5,
    propertyTaxAnnual: 60000,
    insuranceAnnual: 24000,
    maintenanceAnnual: 45000,
    managementFeePct: 8,
    utilitiesAnnual: 0,
    hoaChargesAnnual: 15000,
    otherOpExAnnual: 10000,
    targetCapRatePct: 7,
    mortgageInterestRate: 8.5,
  },

  fieldBoundaries: {
    propertyValue: { min: 500000, max: 1000000000, step: 100000 },
    monthlyRent: { min: 0, max: 10000000, step: 5000 },
    otherIncomeAnnual: { min: 0, max: 10000000, step: 5000 },
    vacancyRatePct: { min: 0, max: 50, step: 0.5 },
    propertyTaxAnnual: { min: 0, max: 10000000, step: 2000 },
    insuranceAnnual: { min: 0, max: 5000000, step: 1000 },
    maintenanceAnnual: { min: 0, max: 10000000, step: 5000 },
    managementFeePct: { min: 0, max: 30, step: 0.5 },
    targetCapRatePct: { min: 1, max: 25, step: 0.25 },
    mortgageInterestRate: { min: 0, max: 25, step: 0.25 },
  },

  disclaimers: {
    educationalNotice: 'This calculator provides an unleveraged property-level return estimation based on standard Net Operating Income (NOI) principles. Cap rate does not account for mortgage debt service, income tax liability, or future market appreciation.',
    noiNotice: 'Net Operating Income (NOI) strictly excludes mortgage principal, mortgage interest payments, income tax withholdings, and capital improvements (CapEx) per GAAP real estate accounting guidelines.',
  },

  scenarios: {
    singleFamily: {
      title: 'Single-Family Rental Property (₹50 LPA)',
      description: 'Standard residential rental property with 5% vacancy rate and standard property management fees.',
      propertyValue: 5000000,
      monthlyRent: 30000,
      otherIncomeAnnual: 0,
      vacancyRatePct: 5,
      propertyTaxAnnual: 25000,
      insuranceAnnual: 12000,
      maintenanceAnnual: 24000,
      managementFeePct: 8,
      utilitiesAnnual: 0,
      hoaChargesAnnual: 12000,
      otherOpExAnnual: 5000,
      targetCapRatePct: 6.5,
      mortgageInterestRate: 8.5,
    },
    commercialRetail: {
      title: 'Commercial Retail Unit (₹2 Crore)',
      description: 'Prime commercial shop or office space with low vacancy and steady monthly rental yields.',
      propertyValue: 20000000,
      monthlyRent: 140000,
      otherIncomeAnnual: 50000,
      vacancyRatePct: 4,
      propertyTaxAnnual: 120000,
      insuranceAnnual: 45000,
      maintenanceAnnual: 60000,
      managementFeePct: 6,
      utilitiesAnnual: 0,
      hoaChargesAnnual: 36000,
      otherOpExAnnual: 20000,
      targetCapRatePct: 7.5,
      mortgageInterestRate: 8.75,
    },
    multiFamily: {
      title: 'Multi-Family Apartment Complex (₹5 Crore)',
      description: 'Multi-unit residential complex evaluated at scale with professional management retentions.',
      propertyValue: 50000000,
      monthlyRent: 380000,
      otherIncomeAnnual: 150000,
      vacancyRatePct: 6,
      propertyTaxAnnual: 300000,
      insuranceAnnual: 120000,
      maintenanceAnnual: 180000,
      managementFeePct: 8,
      utilitiesAnnual: 60000,
      hoaChargesAnnual: 0,
      otherOpExAnnual: 50000,
      targetCapRatePct: 7.0,
      mortgageInterestRate: 8.5,
    },
    industrialWarehouse: {
      title: 'High-Yield Industrial Warehouse (₹1.5 Crore)',
      description: 'Industrial logistics asset evaluated with NNN lease style low operating overheads.',
      propertyValue: 15000000,
      monthlyRent: 120000,
      otherIncomeAnnual: 30000,
      vacancyRatePct: 3,
      propertyTaxAnnual: 80000,
      insuranceAnnual: 30000,
      maintenanceAnnual: 36000,
      managementFeePct: 5,
      utilitiesAnnual: 0,
      hoaChargesAnnual: 0,
      otherOpExAnnual: 15000,
      targetCapRatePct: 8.5,
      mortgageInterestRate: 8.5,
    },
  },
};
