import { calculateCapitalGainsTaxCalculator } from '../tax/capital-gains-tax-calculator.js';

export const capitalGainsTaxCalculatorConfig = {
  title: 'Capital Gains Tax Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateCapitalGainsTaxCalculator,
  primaryResult: {
    key: 'taxPayable',
    label: 'Total Capital Gains Tax Payable (incl. Cess)',
  },
  ratioBarItems: [
    { key: 'netProfit', label: 'Net Profit Kept', colorClass: 'bg-semantic-up' },
    { key: 'taxPayable', label: 'Tax Payable', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'grossGain', label: 'Gross Capital Gain' },
    { key: 'netCapitalGain', label: 'Net Capital Gain (after fees)' },
    { key: 'exemptionAmount', label: 'Exemption Limit (Sec 112A)' },
    { key: 'taxableGain', label: 'Net Taxable Capital Gain' },
    { key: 'taxPayable', label: 'Total Tax Payable', isTotal: true },
    { key: 'netProfit', label: 'Net Post-Tax Profit', class: 'text-semantic-up' },
  ],
  inputs: [
    {
      id: 'purchasePrice',
      type: 'number',
      label: 'Original Purchase Price (₹)',
      min: 1000,
      max: 100000000,
      step: 5000,
      prefix: '₹',
      minLabel: '₹1K',
      maxLabel: '₹10 Cr',
      default: 100000,
    },
    {
      id: 'salePrice',
      type: 'number',
      label: 'Sale / Redemption Price (₹)',
      min: 1000,
      max: 100000000,
      step: 5000,
      prefix: '₹',
      minLabel: '₹1K',
      maxLabel: '₹10 Cr',
      default: 250000,
    },
    {
      id: 'holdingPeriodMonths',
      type: 'number',
      label: 'Holding Duration (Months)',
      min: 1,
      max: 120,
      step: 1,
      suffix: 'Mos',
      minLabel: '1 Mo',
      maxLabel: '10 Yrs',
      default: 18,
    },
    {
      id: 'transferExpenses',
      type: 'number',
      label: 'Brokerage / Transfer Expenses (₹)',
      min: 0,
      max: 500000,
      step: 500,
      prefix: '₹',
      minLabel: '₹0',
      maxLabel: '₹5L',
      default: 0,
    },
  ],
  hasAmortizationTable: false,
};