import { calculateCarLoan } from '../loans/car-loan-calculator.js';

export const carLoanCalculatorConfig = {
  title: 'Car Loan & Vehicle Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateCarLoan,
  primaryResult: {
    key: 'emi',
    label: 'Monthly Car Loan EMI',
  },
  ratioBarItems: [
    { key: 'loanAmount', label: 'Loan Principal', colorClass: 'bg-primary' },
    { key: 'totalInterest', label: 'Total Interest', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'downPaymentAmount', label: 'Down Payment Required' },
    { key: 'loanAmount', label: 'Net Borrowed Car Loan' },
    { key: 'totalInterest', label: 'Total Interest Payable', class: 'text-semantic-down' },
    { key: 'processingFee', label: 'Processing Fee (Est.)' },
    { key: 'totalPayment', label: 'Total Repayment Amount', isTotal: true },
  ],
  inputs: [
    {
      id: 'vehiclePrice',
      type: 'number',
      label: 'On-Road Vehicle Price',
      min: 100000,
      max: 20000000,
      step: 50000,
      prefix: '₹',
      minLabel: '₹1L',
      maxLabel: '₹2 Cr',
      default: 1000000,
    },
    {
      id: 'downPaymentPct',
      type: 'number',
      label: 'Down Payment (%)',
      min: 0,
      max: 90,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '90%',
      default: 15,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (p.a.)',
      min: 1,
      max: 25,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '25%',
      default: 9.0,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Loan Tenure',
      maxYears: 7,
      maxMonths: 84,
      default: 5,
    },
    {
      id: 'processingFeePct',
      type: 'number',
      label: 'Processing Fee (%)',
      min: 0,
      max: 3,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '3%',
      default: 1.0,
    },
  ],
  hasAmortizationTable: true,
};