import { calculateCompoundInterestCalculator } from '../investment/compound-interest-calculator.js';

export const COMPOUND_INTEREST_CONFIG = {
  id: 'compound-interest-calculator',
  title: 'Compound Interest Calculator',
  category: 'Investment Calculators',
  categorySlug: 'investment',
  defaultPrincipal: 100000,
  defaultMonthlyDeposit: 5000,
  defaultRate: 10.0,
  defaultTenureYears: 10,
  defaultCompoundingFrequency: 'annually',
  defaultContributionTiming: 'end',
  defaultInflationRate: 5.0,

  frequencies: [
    { id: 'daily', label: 'Daily (365/yr)', n: 365 },
    { id: 'monthly', label: 'Monthly (12/yr)', n: 12 },
    { id: 'quarterly', label: 'Quarterly (4/yr)', n: 4 },
    { id: 'semi-annually', label: 'Semi-Annually (2/yr)', n: 2 },
    { id: 'annually', label: 'Annually (1/yr)', n: 1 },
  ],

  timingOptions: [
    { id: 'end', label: 'End of Month' },
    { id: 'beginning', label: 'Beginning of Month' },
  ],

  presets: [
    {
      id: 'wealth_accelerator',
      title: '🚀 Wealth Accelerator (₹1L + ₹5k/mo @ 12% p.a., 10 Yrs)',
      description: 'Standard equity compounding scenario with monthly contributions over a 10-year horizon.',
      values: {
        principal: 100000,
        monthlyDeposit: 5000,
        rate: 12.0,
        tenureYears: 10,
        compoundingFrequency: 'annually',
        contributionTiming: 'end',
        currency: 'INR',
      },
    },
    {
      id: 'fixed_income_fd',
      title: '🏦 Fixed Deposit Compounding (₹5L Lumpsum @ 7.5% p.a. Quarterly, 5 Yrs)',
      description: 'Bank FD growth compounding quarterly with no recurring monthly deposits.',
      values: {
        principal: 500000,
        monthlyDeposit: 0,
        rate: 7.5,
        tenureYears: 5,
        compoundingFrequency: 'quarterly',
        contributionTiming: 'end',
        currency: 'INR',
      },
    },
    {
      id: 'long_term_builder',
      title: '📈 Long-Term Corpus Builder (₹10k + ₹10k/mo @ 10% p.a., 20 Yrs)',
      description: 'Disciplined 20-year wealth accumulation powered by regular monthly deposits.',
      values: {
        principal: 10000,
        monthlyDeposit: 10000,
        rate: 10.0,
        tenureYears: 20,
        compoundingFrequency: 'monthly',
        contributionTiming: 'end',
        currency: 'INR',
      },
    },
    {
      id: 'daily_micro_saver',
      title: '⚡ Daily Compounding Micro Saver (₹50k + ₹1k/mo @ 8% p.a. Daily, 3 Yrs)',
      description: 'High-frequency daily compounding deposit over a short 3-year term.',
      values: {
        principal: 50000,
        monthlyDeposit: 1000,
        rate: 8.0,
        tenureYears: 3,
        compoundingFrequency: 'daily',
        contributionTiming: 'end',
        currency: 'INR',
      },
    },
  ],
};

export const compoundInterestCalculatorConfig = {
  ...COMPOUND_INTEREST_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateCompoundInterestCalculator,
  primaryResult: {
    key: 'finalCorpus',
    label: 'Accumulated Maturity Corpus',
  },
  ratioBarItems: [
    { key: 'totalPrincipal', label: 'Total Invested Capital', colorClass: 'bg-primary' },
    { key: 'totalInterestEarned', label: 'Total Compound Interest Earned', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'principal', label: 'Initial Principal Deposit' },
    { key: 'totalMonthlyDeposits', label: 'Total Recurring Deposits Paid' },
    { key: 'totalPrincipal', label: 'Total Invested Capital' },
    { key: 'totalInterestEarned', label: 'Total Compound Interest Earned', class: 'text-emerald-600 font-bold' },
    { key: 'effectiveAnnualRate', label: 'Effective Annual Rate (EAR / APY)' },
    { key: 'finalCorpus', label: 'Final Accumulated Corpus', isTotal: true },
  ],
  inputs: [
    {
      id: 'principal',
      type: 'number',
      label: 'Initial Principal Investment',
      min: 0,
      max: 10000000,
      step: 1000,
      prefix: '₹',
      minLabel: '₹0',
      maxLabel: '₹1 Cr',
      default: 100000,
    },
    {
      id: 'monthlyDeposit',
      type: 'number',
      label: 'Additional Monthly Deposit',
      min: 0,
      max: 500000,
      step: 500,
      prefix: '₹',
      minLabel: '₹0',
      maxLabel: '₹5 Lakhs/mo',
      default: 5000,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Nominal Annual Interest Rate (% p.a.)',
      min: 0.1,
      max: 30.0,
      step: 0.1,
      suffix: '%',
      minLabel: '0.1%',
      maxLabel: '30.0%',
      default: 10.0,
    },
    {
      id: 'tenureYears',
      type: 'number',
      label: 'Investment Duration (Years)',
      min: 1,
      max: 40,
      step: 1,
      suffix: ' Yrs',
      minLabel: '1 Yr',
      maxLabel: '40 Yrs',
      default: 10,
    },
  ],
  hasAmortizationTable: true,
};
