/**
 * Cost of Living Calculator Configuration & Presets
 * Sprint 79 / Flagship #86
 */

export const COST_OF_LIVING_CONFIG = {
  id: 'cost-of-living-calculator',
  title: 'Cost of Living Calculator',
  category: 'currency',
  categoryName: 'Currency & Cost Calculators',
  version: '3.0.0',
  author: 'Fintools Find Financial Engineering Team',
  lastUpdated: '2026-08-27',

  defaults: {
    currentLocation: 'Tier-2 City / Suburban',
    targetLocation: 'Metro City (Capital)',
    currentIncome: 100000,
    targetIncome: 0,
    currency: 'INR',
    currentExpenses: {
      housing: 20000,
      utilities: 5000,
      food: 12000,
      transportation: 5000,
      healthcare: 3500,
      lifestyle: 6500,
      family: 0,
      miscellaneous: 3000,
    },
    targetExpenses: {
      housing: 35000,
      utilities: 7500,
      food: 18000,
      transportation: 8000,
      healthcare: 5000,
      lifestyle: 10000,
      family: 0,
      miscellaneous: 4500,
    },
  },

  presets: [
    {
      id: 'metro_upgrade',
      label: 'Tier-2 to Tier-1 Metro',
      icon: '🏙️',
      currentLocation: 'Pune / Jaipur / Kochi',
      targetLocation: 'Mumbai / Bengaluru / Delhi NCR',
      currentIncome: 100000,
      targetIncome: 140000,
      currency: 'INR',
      currentExpenses: {
        housing: 22000,
        utilities: 5500,
        food: 14000,
        transportation: 5000,
        healthcare: 3500,
        lifestyle: 8000,
        family: 0,
        miscellaneous: 4000,
      },
      targetExpenses: {
        housing: 40000,
        utilities: 8000,
        food: 20000,
        transportation: 8500,
        healthcare: 5000,
        lifestyle: 12000,
        family: 0,
        miscellaneous: 5500,
      },
      desc: '₹62k → ₹99k/mo · Tech Metro Career Relocation',
    },
    {
      id: 'family_schooling',
      label: 'Family with 2 Kids',
      icon: '👨‍👩‍👧‍👦',
      currentLocation: 'Suburban Township',
      targetLocation: 'Central City Hub',
      currentIncome: 180000,
      targetIncome: 220000,
      currency: 'INR',
      currentExpenses: {
        housing: 30000,
        utilities: 7000,
        food: 22000,
        transportation: 8000,
        healthcare: 6000,
        lifestyle: 10000,
        family: 20000,
        miscellaneous: 5000,
      },
      targetExpenses: {
        housing: 50000,
        utilities: 10000,
        food: 28000,
        transportation: 12000,
        healthcare: 8000,
        lifestyle: 14000,
        family: 35000,
        miscellaneous: 8000,
      },
      desc: '₹1.08L → ₹1.65L/mo · Schooling & Family Expansion',
    },
    {
      id: 'geo_arbitrage_remote',
      label: 'Remote Work Geo-Arbitrage',
      icon: '🏡',
      currentLocation: 'High-Cost Metro (Bengaluru/Gurugram)',
      targetLocation: 'Coastal / Hometown (Goa/Dehradun/Mysuru)',
      currentIncome: 150000,
      targetIncome: 150000,
      currency: 'INR',
      currentExpenses: {
        housing: 45000,
        utilities: 8500,
        food: 22000,
        transportation: 10000,
        healthcare: 5000,
        lifestyle: 15000,
        family: 0,
        miscellaneous: 6000,
      },
      targetExpenses: {
        housing: 20000,
        utilities: 4500,
        food: 12000,
        transportation: 4000,
        healthcare: 4000,
        lifestyle: 8000,
        family: 0,
        miscellaneous: 3500,
      },
      desc: '₹1.11L → ₹56k/mo · 50% Savings Geo-Arbitrage',
    },
    {
      id: 'us_metro_comparison',
      label: 'US Relocation (Midwest to NY/SF)',
      icon: '🇺🇸',
      currentLocation: 'Austin / Chicago / Dallas',
      targetLocation: 'New York City / San Francisco',
      currentIncome: 8000,
      targetIncome: 12000,
      currency: 'USD',
      currentExpenses: {
        housing: 2200,
        utilities: 350,
        food: 800,
        transportation: 500,
        healthcare: 400,
        lifestyle: 600,
        family: 0,
        miscellaneous: 350,
      },
      targetExpenses: {
        housing: 4200,
        utilities: 500,
        food: 1200,
        transportation: 350,
        healthcare: 500,
        lifestyle: 1000,
        family: 0,
        miscellaneous: 550,
      },
      desc: '$5.2k → $8.3k/mo · US Tech Metro Relocation',
    },
    {
      id: 'frugal_solo_living',
      label: 'Frugal Solo Budgeting',
      icon: '🎯',
      currentLocation: 'Shared Apartment Baseline',
      targetLocation: 'Independent 1BHK Living',
      currentIncome: 60000,
      targetIncome: 60000,
      currency: 'INR',
      currentExpenses: {
        housing: 12000,
        utilities: 2500,
        food: 8000,
        transportation: 3000,
        healthcare: 2000,
        lifestyle: 4000,
        family: 0,
        miscellaneous: 2000,
      },
      targetExpenses: {
        housing: 22000,
        utilities: 4500,
        food: 10000,
        transportation: 4000,
        healthcare: 2500,
        lifestyle: 5000,
        family: 0,
        miscellaneous: 3000,
      },
      desc: '₹33.5k → ₹51k/mo · Shared vs Independent Living',
    },
    {
      id: 'eurozone_relocation',
      label: 'Europe Relocation (South to North)',
      icon: '🇪🇺',
      currentLocation: 'Madrid / Lisbon / Rome',
      targetLocation: 'Berlin / Amsterdam / Dublin',
      currentIncome: 3500,
      targetIncome: 5000,
      currency: 'EUR',
      currentExpenses: {
        housing: 1100,
        utilities: 220,
        food: 450,
        transportation: 120,
        healthcare: 150,
        lifestyle: 400,
        family: 0,
        miscellaneous: 160,
      },
      targetExpenses: {
        housing: 1900,
        utilities: 350,
        food: 650,
        transportation: 180,
        healthcare: 220,
        lifestyle: 600,
        family: 0,
        miscellaneous: 250,
      },
      desc: '€2.6k → €4.15k/mo · European Corridor Move',
    },
  ],
};
