/**
 * Crypto Profit/Loss Calculator Configuration & Educational Presets
 * Sprint 82 / Flagship #89
 * 
 * Note: Presets are representative educational scenarios and realistic market archetypes.
 * They are not real-time live prices.
 */

export const CRYPTO_PROFIT_LOSS_CONFIG = {
  id: 'crypto-profit-loss-calculator',
  title: 'Crypto Profit/Loss Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Quantitative Digital Asset & Investment Advisory Board',
  lastUpdated: '2026-08-27',

  defaults: {
    quantity: 0.5,
    buyPrice: 45000,
    sellPrice: 65000,
    buyFeePct: 0.1,
    sellFeePct: 0.1,
    buyFixedFee: 0,
    sellFixedFee: 0,
    buyGasFee: 5,
    sellGasFee: 5,
    currency: 'USD',
    positionMode: 'UNREALIZED',
    assetName: 'Bitcoin (BTC)',
  },

  presets: [
    {
      id: 'btc_swing_profit',
      label: 'Bitcoin (BTC): Multi-Month Swing Trade',
      icon: '₿',
      assetName: 'Bitcoin (BTC)',
      quantity: 0.25,
      buyPrice: 48000,
      sellPrice: 68000,
      buyFeePct: 0.1,
      sellFeePct: 0.1,
      buyFixedFee: 0,
      sellFixedFee: 0,
      buyGasFee: 5,
      sellGasFee: 5,
      currency: 'USD',
      positionMode: 'REALIZED',
      desc: '0.25 BTC · Bought @ $48k, Sold @ $68k (+41.6% ROI)',
    },
    {
      id: 'eth_defi_gas',
      label: 'Ethereum (ETH): DeFi Trade with Gas Costs',
      icon: 'Ξ',
      assetName: 'Ethereum (ETH)',
      quantity: 2.0,
      buyPrice: 2500,
      sellPrice: 3400,
      buyFeePct: 0.3,
      sellFeePct: 0.3,
      buyFixedFee: 0,
      sellFixedFee: 0,
      buyGasFee: 20,
      sellGasFee: 25,
      currency: 'USD',
      positionMode: 'UNREALIZED',
      desc: '2.0 ETH · Bought @ $2.5k, Current @ $3.4k · $45 Total Gas',
    },
    {
      id: 'sol_low_fee',
      label: 'Solana (SOL): High-Frequency / Low-Fee',
      icon: '◎',
      assetName: 'Solana (SOL)',
      quantity: 40.0,
      buyPrice: 110,
      sellPrice: 165,
      buyFeePct: 0.05,
      sellFeePct: 0.05,
      buyFixedFee: 0,
      sellFixedFee: 0,
      buyGasFee: 0.5,
      sellGasFee: 0.5,
      currency: 'USD',
      positionMode: 'UNREALIZED',
      desc: '40 SOL · Bought @ $110, Current @ $165 (+50% Gain)',
    },
    {
      id: 'btc_inr_corridor',
      label: 'Bitcoin in INR (₹): Indian Rupee Investment',
      icon: '🇮🇳',
      assetName: 'Bitcoin (BTC)',
      quantity: 0.05,
      buyPrice: 4200000,
      sellPrice: 5800000,
      buyFeePct: 0.2,
      sellFeePct: 0.2,
      buyFixedFee: 100,
      sellFixedFee: 100,
      buyGasFee: 500,
      sellGasFee: 500,
      currency: 'INR',
      positionMode: 'REALIZED',
      desc: '0.05 BTC · ₹2.1L Inflow → ₹2.89L Outflow',
    },
    {
      id: 'drawdown_loss',
      label: 'Market Correction / Drawdown Position',
      icon: '📉',
      assetName: 'Altcoin Portfolio',
      quantity: 1000,
      buyPrice: 5.50,
      sellPrice: 3.80,
      buyFeePct: 0.15,
      sellFeePct: 0.15,
      buyFixedFee: 0,
      sellFixedFee: 0,
      buyGasFee: 5,
      sellGasFee: 5,
      currency: 'USD',
      positionMode: 'UNREALIZED',
      desc: '1,000 Units · Bought @ $5.50, Current @ $3.80 (-31.1% Loss)',
    },
    {
      id: 'break_even_scalp',
      label: 'Tight Scalp Trade (Near Break-Even)',
      icon: '⚖️',
      assetName: 'Ethereum (ETH)',
      quantity: 5.0,
      buyPrice: 3000,
      sellPrice: 3015,
      buyFeePct: 0.1,
      sellFeePct: 0.1,
      buyFixedFee: 0,
      sellFixedFee: 0,
      buyGasFee: 10,
      sellGasFee: 10,
      currency: 'USD',
      positionMode: 'REALIZED',
      desc: '5 ETH · $15k Volume · Scalp testing fee break-even',
    },
  ],
};
