/**
 * Crypto Tax Calculator Configuration & Educational Presets
 * Sprint 86 / Flagship #93
 * 
 * Note: Presets represent educational simulation scenarios for modeling purposes.
 * They do not constitute official tax assessments or legal advice.
 */

export const CRYPTO_TAX_CONFIG = {
  id: 'crypto-tax-calculator',
  title: 'Crypto Tax Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Quantitative Digital Asset & Tax Advisory Board',
  lastUpdated: '2026-08-28',

  defaults: {
    jurisdiction: 'GENERIC',
    transactionType: 'SELL',
    assetName: 'Bitcoin (BTC)',
    quantity: 1.0,
    buyPrice: 40000,
    sellPrice: 65000,
    buyDate: '2024-01-15',
    sellDate: '2025-06-20',
    buyFee: 25,
    sellFee: 35,
    shortTermTaxRate: 30.0,
    longTermTaxRate: 15.0,
    incomeTaxRate: 25.0,
    rewardFmv: 3000,
    rewardQuantity: 1.0,
    isRewardSoldLater: false,
    rewardSalePrice: 4500,
    rewardSaleDate: '2025-12-01',
    currency: 'USD',
    costBasisMethod: 'SPECIFIC_ID',
  },

  presets: [
    {
      id: 'us_long_term_btc_gain',
      label: 'United States: Long-Term BTC Sale',
      icon: '🇺🇸',
      jurisdiction: 'US',
      transactionType: 'SELL',
      assetName: 'Bitcoin (BTC)',
      quantity: 0.5,
      buyPrice: 35000,
      sellPrice: 68000,
      buyDate: '2024-02-10',
      sellDate: '2025-05-15',
      buyFee: 20,
      sellFee: 30,
      currency: 'USD',
      desc: '0.5 BTC · Held >1 Year · 15% Long-Term Capital Gains Rate',
    },
    {
      id: 'us_short_term_eth_gain',
      label: 'United States: Short-Term ETH Trade',
      icon: '⚡',
      jurisdiction: 'US',
      transactionType: 'SELL',
      assetName: 'Ethereum (ETH)',
      quantity: 4.0,
      buyPrice: 2200,
      sellPrice: 3400,
      buyDate: '2025-01-10',
      sellDate: '2025-04-18',
      buyFee: 15,
      sellFee: 25,
      currency: 'USD',
      desc: '4 ETH · Held 3 Months · 24% Ordinary Short-Term Income Rate',
    },
    {
      id: 'in_vda_flat_tax',
      label: 'India: Section 115BBH 31.2% Flat Tax',
      icon: '🇮🇳',
      jurisdiction: 'IN',
      transactionType: 'SELL',
      assetName: 'Bitcoin (BTC)',
      quantity: 0.25,
      buyPrice: 3500000,
      sellPrice: 5800000,
      buyDate: '2024-06-01',
      sellDate: '2025-03-15',
      buyFee: 2500,
      sellFee: 3500,
      currency: 'INR',
      desc: '₹5.75L Gain · Flat 30% + 4% Cess (31.2%) · 1% TDS Deducted',
    },
    {
      id: 'de_1yr_tax_free',
      label: 'Germany: 1-Year Holding Tax-Free',
      icon: '🇩🇪',
      jurisdiction: 'DE',
      transactionType: 'SELL',
      assetName: 'Solana (SOL)',
      quantity: 50,
      buyPrice: 60,
      sellPrice: 180,
      buyDate: '2024-01-10',
      sellDate: '2025-03-20',
      buyFee: 10,
      sellFee: 15,
      currency: 'EUR',
      desc: '50 SOL · Held > 365 Days · 100% Tax-Free (§ 23 EStG)',
    },
    {
      id: 'uk_cgt_allowance',
      label: 'United Kingdom: £3,000 CGT Allowance',
      icon: '🇬🇧',
      jurisdiction: 'UK',
      transactionType: 'SELL',
      assetName: 'Ethereum (ETH)',
      quantity: 3.0,
      buyPrice: 1500,
      sellPrice: 3500,
      buyDate: '2024-05-01',
      sellDate: '2025-02-15',
      buyFee: 20,
      sellFee: 25,
      currency: 'GBP',
      desc: '£6,000 Gross Gain · £3,000 Exemption · 20% Higher Rate CGT',
    },
    {
      id: 'au_50pct_cgt_discount',
      label: 'Australia: 50% Long-Term CGT Discount',
      icon: '🇦🇺',
      jurisdiction: 'AU',
      transactionType: 'SELL',
      assetName: 'Bitcoin (BTC)',
      quantity: 0.4,
      buyPrice: 45000,
      sellPrice: 95000,
      buyDate: '2024-01-05',
      sellDate: '2025-04-10',
      buyFee: 30,
      sellFee: 45,
      currency: 'AUD',
      desc: 'Held 15 Mo · 50% CGT Discount Applied on $20,000 Gain',
    },
    {
      id: 'staking_income_recognition',
      label: 'Staking Rewards: Income + Subsequent Sale',
      icon: '🥩',
      jurisdiction: 'US',
      transactionType: 'STAKING_REWARD',
      assetName: 'Ethereum (ETH)',
      rewardQuantity: 2.0,
      rewardFmv: 3000,
      buyDate: '2024-06-01',
      isRewardSoldLater: true,
      rewardSalePrice: 4200,
      rewardSaleDate: '2025-08-15',
      currency: 'USD',
      desc: '2 ETH @ $3k ($6k Income Tax) + Sold @ $4.2k ($2.4k Capital Gain)',
    },
    {
      id: 'crypto_loss_no_tax',
      label: 'Realized Capital Loss (Zero Tax)',
      icon: '📉',
      jurisdiction: 'GENERIC',
      transactionType: 'SELL',
      assetName: 'Altcoin',
      quantity: 100,
      buyPrice: 150,
      sellPrice: 80,
      buyDate: '2024-09-01',
      sellDate: '2025-01-15',
      buyFee: 15,
      sellFee: 15,
      currency: 'USD',
      desc: '$7,030 Realized Loss · $0 Tax Liability · Capital Loss Tracking',
    },
  ],
};
