import { calculateCurrentRatioCalculator } from '../business/current-ratio-calculator.js';

export const CURRENT_RATIO_PRESETS = [
  {
    id: 'heavy_manufacturing',
    name: 'Industrial Manufacturing',
    description: '₹1.50 Cr Current Assets, ₹75L Current Liabilities → 2.00x Current Ratio',
    badge: 'Manufacturing',
    values: {
      calculationMode: 'itemized',
      cashAndEquivalents: 3000000,
      marketableSecurities: 1500000,
      accountsReceivable: 4500000,
      inventory: 5000000,
      prepaidExpenses: 1000000,
      accountsPayable: 3500000,
      shortTermDebt: 2000000,
      currentPortionLongDebt: 1000000,
      accruedExpenses: 1000000,
      targetCurrentRatio: 2.0,
      currencySymbol: '₹',
    },
  },
  {
    id: 'fmcg_distribution',
    name: 'FMCG Wholesale & Distribution',
    description: '₹2.20 Cr Current Assets, ₹1.10 Cr Liabilities → 2.00x Current Ratio',
    badge: 'FMCG',
    values: {
      calculationMode: 'itemized',
      cashAndEquivalents: 4000000,
      marketableSecurities: 2000000,
      accountsReceivable: 8000000,
      inventory: 7000000,
      prepaidExpenses: 1000000,
      accountsPayable: 6000000,
      shortTermDebt: 3000000,
      currentPortionLongDebt: 1000000,
      accruedExpenses: 1000000,
      targetCurrentRatio: 2.0,
      currencySymbol: '₹',
    },
  },
  {
    id: 'saas_tech',
    name: 'Software & Tech Enterprise',
    description: '₹1.80 Cr Current Assets, ₹60L Liabilities → 3.00x Current Ratio',
    badge: 'Technology',
    values: {
      calculationMode: 'itemized',
      cashAndEquivalents: 10000000,
      marketableSecurities: 3000000,
      accountsReceivable: 4500000,
      inventory: 0,
      prepaidExpenses: 500000,
      accountsPayable: 2000000,
      shortTermDebt: 1500000,
      currentPortionLongDebt: 1000000,
      accruedExpenses: 1500000,
      targetCurrentRatio: 2.5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'retail_ecommerce',
    name: 'Retail Store & E-Commerce',
    description: '₹80 Lakhs Current Assets, ₹65L Liabilities → 1.23x Current Ratio',
    badge: 'Retail',
    values: {
      calculationMode: 'itemized',
      cashAndEquivalents: 1500000,
      marketableSecurities: 500000,
      accountsReceivable: 1000000,
      inventory: 4500000,
      prepaidExpenses: 500000,
      accountsPayable: 4000000,
      shortTermDebt: 1500000,
      currentPortionLongDebt: 500000,
      accruedExpenses: 500000,
      targetCurrentRatio: 1.5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'construction_infra',
    name: 'Commercial Construction',
    description: '₹3.50 Cr Current Assets, ₹2.00 Cr Liabilities → 1.75x Current Ratio',
    badge: 'Infrastructure',
    values: {
      calculationMode: 'itemized',
      cashAndEquivalents: 5000000,
      marketableSecurities: 2000000,
      accountsReceivable: 15000000,
      inventory: 11000000,
      prepaidExpenses: 2000000,
      accountsPayable: 12000000,
      shortTermDebt: 5000000,
      currentPortionLongDebt: 1500000,
      accruedExpenses: 1500000,
      targetCurrentRatio: 1.75,
      currencySymbol: '₹',
    },
  },
  {
    id: 'pharma_healthcare',
    name: 'Healthcare & Pharma',
    description: '₹1.20 Cr Current Assets, ₹50L Liabilities → 2.40x Current Ratio',
    badge: 'Healthcare',
    values: {
      calculationMode: 'itemized',
      cashAndEquivalents: 3500000,
      marketableSecurities: 1500000,
      accountsReceivable: 4000000,
      inventory: 2500000,
      prepaidExpenses: 500000,
      accountsPayable: 2500000,
      shortTermDebt: 1000000,
      currentPortionLongDebt: 500000,
      accruedExpenses: 1000000,
      targetCurrentRatio: 2.0,
      currencySymbol: '₹',
    },
  },
];

export const currentRatioCalculatorConfig = {
  title: 'Current Ratio (Working Capital Ratio) Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateCurrentRatioCalculator,
  presets: CURRENT_RATIO_PRESETS,
  defaultTotalCurrentAssets: 15000000,
  defaultTotalCurrentLiabilities: 7500000,
  defaultCashAndEquivalents: 3000000,
  defaultAccountsReceivable: 4500000,
  defaultInventory: 5000000,
  defaultAccountsPayable: 3500000,
  primaryResult: {
    key: 'currentRatio',
    label: 'Current Ratio (Working Capital Ratio)',
  },
  ratioBarItems: [
    { key: 'cashAndEquivalents', label: 'Cash & Equivalents', colorClass: 'bg-primary' },
    { key: 'marketableSecurities', label: 'Marketable Securities', colorClass: 'bg-emerald-500' },
    { key: 'accountsReceivable', label: 'Accounts Receivable', colorClass: 'bg-indigo-500' },
    { key: 'inventory', label: 'Inventories', colorClass: 'bg-amber-500' },
  ],
  summaryItems: [
    { key: 'currentRatio', label: 'Current Ratio', isTotal: true },
    { key: 'netWorkingCapital', label: 'Net Working Capital (NWC)' },
    { key: 'quickRatio', label: 'Quick Ratio (Acid-Test)' },
    { key: 'cashRatio', label: 'Cash Ratio' },
    { key: 'effectiveCurrentAssets', label: 'Total Current Assets' },
    { key: 'effectiveCurrentLiabilities', label: 'Total Current Liabilities' },
  ],
  inputs: [
    {
      id: 'cashAndEquivalents',
      type: 'number',
      label: 'Cash & Cash Equivalents',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 3000000,
    },
    {
      id: 'accountsReceivable',
      type: 'number',
      label: 'Accounts Receivable (Net)',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 4500000,
    },
    {
      id: 'inventory',
      type: 'number',
      label: 'Inventory (Raw/WIP/Finished)',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 5000000,
    },
    {
      id: 'accountsPayable',
      type: 'number',
      label: 'Accounts Payable',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 3500000,
    },
  ],
};
