import { calculateCustomerAcquisitionCostCalculator } from '../business/customer-acquisition-cost-calculator.js';

export const CAC_PRESETS = [
  {
    id: 'b2b_saas',
    name: 'B2B Enterprise SaaS',
    description: '₹15L Spend, 15 Customers (10 Paid, 5 Org) → ₹1.0L Blended CAC (2.5 Mo Payback)',
    badge: 'Enterprise SaaS',
    values: {
      paidAdSpend: 500000,
      salesSalaries: 600000,
      marketingSalaries: 250000,
      softwareTools: 100000,
      agencyFees: 50000,
      paidCustomers: 10,
      organicCustomers: 5,
      monthlyArpu: 50000,
      grossMarginPct: 80,
      customerLifetimeMonths: 36,
      currencySymbol: '₹',
    },
  },
  {
    id: 'b2c_app',
    name: 'B2C Mobile Consumer App',
    description: '₹5L Spend, 2,000 Users (1500 Paid, 500 Org) → ₹250 Blended CAC',
    badge: 'Consumer Mobile',
    values: {
      paidAdSpend: 300000,
      salesSalaries: 50000,
      marketingSalaries: 100000,
      softwareTools: 30000,
      agencyFees: 20000,
      paidCustomers: 1500,
      organicCustomers: 500,
      monthlyArpu: 100,
      grossMarginPct: 80,
      customerLifetimeMonths: 18,
      currencySymbol: '₹',
    },
  },
  {
    id: 'd2c_brand',
    name: 'D2C E-Commerce Brand',
    description: '₹6L Spend, 800 Orders (600 Paid, 200 Org) → ₹750 Blended CAC',
    badge: 'E-Commerce',
    values: {
      paidAdSpend: 400000,
      salesSalaries: 20000,
      marketingSalaries: 80000,
      softwareTools: 40000,
      agencyFees: 60000,
      paidCustomers: 600,
      organicCustomers: 200,
      monthlyArpu: 250,
      grossMarginPct: 50,
      customerLifetimeMonths: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'fintech_neobank',
    name: 'FinTech Neo-Bank Platform',
    description: '₹11L Spend, 700 Users (500 Paid, 200 Org) → ₹1,571 Blended CAC',
    badge: 'FinTech',
    values: {
      paidAdSpend: 600000,
      salesSalaries: 200000,
      marketingSalaries: 150000,
      softwareTools: 80000,
      agencyFees: 70000,
      paidCustomers: 500,
      organicCustomers: 200,
      monthlyArpu: 250,
      grossMarginPct: 75,
      customerLifetimeMonths: 24,
      currencySymbol: '₹',
    },
  },
  {
    id: 'organic_flywheel',
    name: 'Organic Referral Flywheel',
    description: '₹4.5L Spend, 1,000 Users (200 Paid, 800 Org) → ₹450 Blended CAC',
    badge: 'Product-Led Growth',
    values: {
      paidAdSpend: 100000,
      salesSalaries: 100000,
      marketingSalaries: 150000,
      softwareTools: 50000,
      agencyFees: 50000,
      paidCustomers: 200,
      organicCustomers: 800,
      monthlyArpu: 400,
      grossMarginPct: 75,
      customerLifetimeMonths: 24,
      currencySymbol: '₹',
    },
  },
  {
    id: 'agency_retainer',
    name: 'Digital Agency / Retainer',
    description: '₹6L Spend, 20 Clients (15 Paid, 5 Org) → ₹30,000 Blended CAC',
    badge: 'B2B Services',
    values: {
      paidAdSpend: 150000,
      salesSalaries: 250000,
      marketingSalaries: 100000,
      softwareTools: 40000,
      agencyFees: 60000,
      paidCustomers: 15,
      organicCustomers: 5,
      monthlyArpu: 15000,
      grossMarginPct: 60,
      customerLifetimeMonths: 18,
      currencySymbol: '₹',
    },
  },
];

export const customerAcquisitionCostCalculatorConfig = {
  title: 'Customer Acquisition Cost (CAC) & Blended CAC Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateCustomerAcquisitionCostCalculator,
  presets: CAC_PRESETS,
  defaultPaidAdSpend: 300000,
  defaultSalesSalaries: 250000,
  defaultMarketingSalaries: 150000,
  defaultSoftwareTools: 50000,
  defaultAgencyFees: 50000,
  defaultPaidCustomers: 200,
  defaultOrganicCustomers: 100,
  primaryResult: {
    key: 'blendedCac',
    label: 'Blended Customer Acquisition Cost (CAC)',
  },
  ratioBarItems: [
    { key: 'paidAdSpend', label: 'Paid Ad Spend', colorClass: 'bg-primary' },
    { key: 'salesSalaries', label: 'Sales Payroll & Commissions', colorClass: 'bg-indigo-500' },
    { key: 'marketingSalaries', label: 'Marketing Payroll', colorClass: 'bg-emerald-500' },
    { key: 'softwareTools', label: 'SaaS Software & CRM', colorClass: 'bg-amber-500' },
    { key: 'agencyFees', label: 'Agency & Creative', colorClass: 'bg-rose-500' },
  ],
  summaryItems: [
    { key: 'blendedCac', label: 'Blended CAC (Total Spend / Total Customers)', isTotal: true },
    { key: 'paidCac', label: 'Paid CAC (Ad Spend / Paid Customers)' },
    { key: 'cacPaybackMonths', label: 'CAC Payback Period (Months)' },
    { key: 'ltvCacRatio', label: 'LTV:CAC Ratio' },
    { key: 'totalAcquisitionSpend', label: 'Total Acquisition Expenditure' },
  ],
  inputs: [
    {
      id: 'paidAdSpend',
      type: 'number',
      label: 'Paid Advertising Spend (Google, Meta, etc.)',
      min: 0,
      max: 100000000,
      step: 10000,
      prefix: '₹',
      default: 300000,
    },
    {
      id: 'salesSalaries',
      type: 'number',
      label: 'Sales Team Salaries & SDR Commissions',
      min: 0,
      max: 100000000,
      step: 10000,
      prefix: '₹',
      default: 250000,
    },
    {
      id: 'paidCustomers',
      type: 'number',
      label: 'Customers Acquired via Paid Channels',
      min: 0,
      max: 1000000,
      step: 10,
      default: 200,
    },
    {
      id: 'organicCustomers',
      type: 'number',
      label: 'Customers Acquired via Organic / SEO / Referrals',
      min: 0,
      max: 1000000,
      step: 10,
      default: 100,
    },
  ],
};
