import { calculateCustomerLifetimeValueCalculator } from '../business/customer-lifetime-value-calculator.js';

export const CLV_PRESETS = [
  {
    id: 'b2b_saas',
    name: 'B2B Enterprise SaaS',
    description: '₹50K ARPU, 1.5% Churn, 80% Margin, ₹1.2L CAC (22.2x LTV:CAC)',
    badge: 'Enterprise SaaS',
    values: {
      businessModel: 'saas',
      arpu: 50000,
      monthlyChurnPct: 1.5,
      grossMarginPct: 80,
      cac: 120000,
      annualDiscountRate: 10,
      cohortSize: 100,
      currencySymbol: '₹',
    },
  },
  {
    id: 'b2c_app',
    name: 'B2C Mobile Subscription',
    description: '₹499/mo, 5.0% Churn, 85% Margin, ₹2,000 CAC (4.2x LTV:CAC)',
    badge: 'Consumer SaaS',
    values: {
      businessModel: 'saas',
      arpu: 499,
      monthlyChurnPct: 5.0,
      grossMarginPct: 85,
      cac: 2000,
      annualDiscountRate: 10,
      cohortSize: 2000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'd2c_ecommerce',
    name: 'D2C E-Commerce Brand',
    description: '₹2,500 AOV, 3.5 Orders/Yr, 3 Yr Lifespan, 60% Margin, ₹3,500 CAC',
    badge: 'E-Commerce',
    values: {
      businessModel: 'ecommerce',
      aov: 2500,
      purchaseFrequency: 3.5,
      customerLifespanYears: 3,
      grossMarginPct: 60,
      cac: 3500,
      annualDiscountRate: 10,
      cohortSize: 1000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'fintech_platform',
    name: 'FinTech Wealth Platform',
    description: '₹1,200 ARPU, 2.0% Churn, 70% Margin, ₹8,000 CAC (5.2x LTV:CAC)',
    badge: 'FinTech',
    values: {
      businessModel: 'saas',
      arpu: 1200,
      monthlyChurnPct: 2.0,
      grossMarginPct: 70,
      cac: 8000,
      annualDiscountRate: 10,
      cohortSize: 1000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'freemium_sub',
    name: 'Freemium Self-Serve Tool',
    description: '₹999 ARPU, 8.0% Churn, 75% Margin, ₹4,500 CAC (2.1x LTV:CAC)',
    badge: 'Freemium',
    values: {
      businessModel: 'saas',
      arpu: 999,
      monthlyChurnPct: 8.0,
      grossMarginPct: 75,
      cac: 4500,
      annualDiscountRate: 10,
      cohortSize: 1500,
      currencySymbol: '₹',
    },
  },
  {
    id: 'agency_retainer',
    name: 'Digital Agency Retainer',
    description: '₹75,000/mo Retainer, 4.0% Churn, 55% Margin, ₹1.5L CAC (6.9x LTV:CAC)',
    badge: 'Agency / Services',
    values: {
      businessModel: 'saas',
      arpu: 75000,
      monthlyChurnPct: 4.0,
      grossMarginPct: 55,
      cac: 150000,
      annualDiscountRate: 10,
      cohortSize: 50,
      currencySymbol: '₹',
    },
  },
];

export const customerLifetimeValueCalculatorConfig = {
  title: 'Customer Lifetime Value (CLV / LTV) & Unit Economics Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateCustomerLifetimeValueCalculator,
  presets: CLV_PRESETS,
  defaultArpu: 3500,
  defaultMonthlyChurnPct: 3.5,
  defaultGrossMarginPct: 75,
  defaultCac: 15000,
  primaryResult: {
    key: 'netLtv',
    label: 'Net Customer Lifetime Value (LTV)',
  },
  ratioBarItems: [
    { key: 'netLtv', label: 'Net LTV (Margin Adjusted)', colorClass: 'bg-primary' },
    { key: 'cac', label: 'Customer Acquisition Cost (CAC)', colorClass: 'bg-rose-500' },
    { key: 'discountedLtv', label: 'Discounted DCF LTV', colorClass: 'bg-emerald-500' },
  ],
  summaryItems: [
    { key: 'netLtv', label: 'Net Customer Lifetime Value (LTV)', isTotal: true },
    { key: 'ltvCacRatio', label: 'LTV:CAC Ratio' },
    { key: 'cacPaybackMonths', label: 'CAC Payback Period (Months)' },
    { key: 'averageLifespanMonths', label: 'Average Customer Lifespan (Months)' },
    { key: 'discountedLtv', label: 'Discounted Cash Flow (DCF) LTV' },
  ],
  inputs: [
    {
      id: 'arpu',
      type: 'number',
      label: 'Average Monthly Revenue Per User (ARPU)',
      min: 10,
      max: 10000000,
      step: 100,
      prefix: '₹',
      default: 3500,
    },
    {
      id: 'monthlyChurnPct',
      type: 'number',
      label: 'Monthly Churn Rate (%)',
      min: 0.1,
      max: 50,
      step: 0.1,
      suffix: '%',
      default: 3.5,
    },
    {
      id: 'grossMarginPct',
      type: 'number',
      label: 'Gross Margin (%)',
      min: 5,
      max: 100,
      step: 1,
      suffix: '%',
      default: 75,
    },
    {
      id: 'cac',
      type: 'number',
      label: 'Customer Acquisition Cost (CAC)',
      min: 0,
      max: 10000000,
      step: 500,
      prefix: '₹',
      default: 15000,
    },
  ],
};
