/**
 * Dollar Cost Averaging (DCA) Calculator Configuration & Educational Presets
 * Sprint 85 / Flagship #92
 * 
 * Note: Presets represent hypothetical educational simulation archetypes.
 * They are not live data feeds or historical guarantees.
 */

export const DCA_CALCULATOR_CONFIG = {
  id: 'dca-calculator',
  title: 'DCA Calculator (Dollar Cost Averaging)',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Quantitative Digital Asset & Portfolio Engineering Team',
  lastUpdated: '2026-08-28',

  defaults: {
    initialInvestment: 0,
    recurringContribution: 500,
    frequency: 'MONTHLY',
    periods: 12,
    startPrice: 60000,
    endPrice: 90000,
    scenarioMode: 'RISING',
    customPrices: [],
    dipPct: 35,
    feeMode: 'DEDUCTED',
    fixedFee: 0,
    pctFee: 0.25,
    targetExitPrice: null,
    currency: 'USD',
    assetName: 'Bitcoin (BTC)',
  },

  presets: [
    {
      id: 'btc_monthly_rising',
      label: 'Bitcoin (BTC): Monthly Bull Trend',
      icon: '₿',
      assetName: 'Bitcoin (BTC)',
      initialInvestment: 1000,
      recurringContribution: 500,
      frequency: 'MONTHLY',
      periods: 12,
      startPrice: 60000,
      endPrice: 90000,
      scenarioMode: 'RISING',
      feeMode: 'DEDUCTED',
      fixedFee: 0,
      pctFee: 0.25,
      currency: 'USD',
      desc: '$1,000 init + $500/mo · 12 Mo · Price $60k → $90k · 0.25% fee',
    },
    {
      id: 'eth_weekly_volatile',
      label: 'Ethereum (ETH): Weekly Dip & Recovery',
      icon: 'Ξ',
      assetName: 'Ethereum (ETH)',
      initialInvestment: 0,
      recurringContribution: 150,
      frequency: 'WEEKLY',
      periods: 26,
      startPrice: 3200,
      endPrice: 3800,
      scenarioMode: 'VOLATILE',
      dipPct: 40,
      feeMode: 'DEDUCTED',
      fixedFee: 0.50,
      pctFee: 0.20,
      currency: 'USD',
      desc: '$150/wk · 26 Wks · 40% Mid-Term Price Dip & Rebound',
    },
    {
      id: 'sol_biweekly_bear',
      label: 'Solana (SOL): Bi-Weekly Bear Market',
      icon: '◎',
      assetName: 'Solana (SOL)',
      initialInvestment: 500,
      recurringContribution: 200,
      frequency: 'BIWEEKLY',
      periods: 24,
      startPrice: 180,
      endPrice: 100,
      scenarioMode: 'FALLING',
      feeMode: 'DEDUCTED',
      fixedFee: 0,
      pctFee: 0.15,
      currency: 'USD',
      desc: '$500 init + $200 bi-weekly · 24 Periods · $180 → $100 Downward Trend',
    },
    {
      id: 'constant_price_baseline',
      label: 'Constant Price Simulation (Zero Volatility)',
      icon: '⚖️',
      assetName: 'Index Benchmark',
      initialInvestment: 0,
      recurringContribution: 1000,
      frequency: 'MONTHLY',
      periods: 12,
      startPrice: 100,
      endPrice: 100,
      scenarioMode: 'CONSTANT',
      feeMode: 'NONE',
      fixedFee: 0,
      pctFee: 0,
      currency: 'USD',
      desc: '$1,000/mo · 12 Mo · Steady $100 Flat Price · Zero Fees',
    },
    {
      id: 'high_fee_drag_demo',
      label: 'High-Fee vs Low-Fee Impact Modeling',
      icon: '💸',
      assetName: 'Crypto Asset',
      initialInvestment: 0,
      recurringContribution: 100,
      frequency: 'WEEKLY',
      periods: 52,
      startPrice: 50,
      endPrice: 80,
      scenarioMode: 'RISING',
      feeMode: 'SEPARATE',
      fixedFee: 2.50,
      pctFee: 1.5,
      currency: 'USD',
      desc: '$100/wk · 52 Wks · $2.50 Fixed + 1.5% Fee Drag Analysis',
    },
    {
      id: 'daily_micro_dca',
      label: 'Daily Micro-DCA Accumulation',
      icon: '⏱️',
      assetName: 'Bitcoin (BTC)',
      initialInvestment: 0,
      recurringContribution: 25,
      frequency: 'DAILY',
      periods: 90,
      startPrice: 55000,
      endPrice: 70000,
      scenarioMode: 'RISING',
      feeMode: 'DEDUCTED',
      fixedFee: 0,
      pctFee: 0.1,
      currency: 'USD',
      desc: '$25/day · 90 Days · $55k → $70k · Ultra-low friction accumulation',
    },
  ],
};
