import { calculateDebtServiceCoverageRatioCalculator } from '../business/debt-service-coverage-ratio-calculator.js';

export const DSCR_PRESETS = [
  {
    id: 'cre_multifamily',
    name: 'Commercial Real Estate Multifamily',
    description: '₹1.20 Cr Gross Rent, 5% Vacancy, ₹35L OPEX, ₹40L Debt Service → 1.98x DSCR',
    badge: 'Real Estate',
    values: {
      calculationMode: 'real_estate',
      grossRevenue: 12000000,
      vacancyLossPct: 5,
      operatingExpenses: 3500000,
      annualPrincipal: 2500000,
      annualInterest: 1500000,
      annualLeaseObligations: 0,
      targetDscrBenchmark: 1.25,
      loanInterestRate: 8.5,
      loanTenureYears: 15,
      currencySymbol: '₹',
    },
  },
  {
    id: 'corporate_term',
    name: 'Corporate Term Loan & Capex',
    description: '₹80 Lakhs NOI, ₹45L Principal + ₹18L Interest → 1.27x DSCR',
    badge: 'Corporate Lending',
    values: {
      calculationMode: 'direct',
      netOperatingIncome: 8000000,
      annualPrincipal: 4500000,
      annualInterest: 1800000,
      annualLeaseObligations: 0,
      targetDscrBenchmark: 1.25,
      loanInterestRate: 9.0,
      loanTenureYears: 7,
      currencySymbol: '₹',
    },
  },
  {
    id: 'msme_business',
    name: 'Small Business / MSME Loan',
    description: '₹35 Lakhs NOI, ₹14L Principal + ₹8L Interest → 1.59x DSCR',
    badge: 'MSME',
    values: {
      calculationMode: 'direct',
      netOperatingIncome: 3500000,
      annualPrincipal: 1400000,
      annualInterest: 800000,
      annualLeaseObligations: 0,
      targetDscrBenchmark: 1.20,
      loanInterestRate: 10.0,
      loanTenureYears: 5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'industrial_logistics',
    name: 'Industrial Logistics Facility',
    description: '₹2.50 Cr Rent, 3% Vacancy, ₹50L OPEX, ₹1.20 Cr Debt Service → 1.60x DSCR',
    badge: 'Logistics',
    values: {
      calculationMode: 'real_estate',
      grossRevenue: 25000000,
      vacancyLossPct: 3,
      operatingExpenses: 5000000,
      annualPrincipal: 7500000,
      annualInterest: 4500000,
      annualLeaseObligations: 0,
      targetDscrBenchmark: 1.30,
      loanInterestRate: 8.25,
      loanTenureYears: 15,
      currencySymbol: '₹',
    },
  },
  {
    id: 'lbo_acquisition',
    name: 'Leveraged Buyout (LBO)',
    description: '₹5.0 Cr EBITDA/NOI, ₹2.5 Cr Principal + ₹1.3 Cr Interest → 1.32x DSCR',
    badge: 'Private Equity',
    values: {
      calculationMode: 'direct',
      netOperatingIncome: 50000000,
      annualPrincipal: 25000000,
      annualInterest: 13000000,
      annualLeaseObligations: 0,
      targetDscrBenchmark: 1.25,
      loanInterestRate: 9.5,
      loanTenureYears: 7,
      currencySymbol: '₹',
    },
  },
  {
    id: 'healthcare_practice',
    name: 'Healthcare & Medical Practice',
    description: '₹90 Lakhs Revenue, ₹30L OPEX, ₹35L Debt Service → 1.59x DSCR',
    badge: 'Healthcare',
    values: {
      calculationMode: 'itemized',
      grossRevenue: 9000000,
      vacancyLossPct: 4,
      operatingExpenses: 3000000,
      annualPrincipal: 2200000,
      annualInterest: 1300000,
      annualLeaseObligations: 0,
      targetDscrBenchmark: 1.25,
      loanInterestRate: 8.75,
      loanTenureYears: 10,
      currencySymbol: '₹',
    },
  },
];

export const debtServiceCoverageRatioCalculatorConfig = {
  title: 'Debt Service Coverage Ratio (DSCR) Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateDebtServiceCoverageRatioCalculator,
  presets: DSCR_PRESETS,
  defaultNetOperatingIncome: 6000000,
  defaultGrossRevenue: 10000000,
  defaultAnnualPrincipal: 2500000,
  defaultAnnualInterest: 1500000,
  primaryResult: {
    key: 'dscr',
    label: 'Debt Service Coverage Ratio (DSCR)',
  },
  ratioBarItems: [
    { key: 'annualPrincipal', label: 'Principal Debt Repayment', colorClass: 'bg-primary' },
    { key: 'annualInterest', label: 'Interest Expense', colorClass: 'bg-amber-500' },
    { key: 'annualLeaseObligations', label: 'Lease Obligations', colorClass: 'bg-indigo-500' },
    { key: 'cashFlowSurplus', label: 'Free Cash Flow Surplus', colorClass: 'bg-emerald-500' },
  ],
  summaryItems: [
    { key: 'dscr', label: 'Debt Service Coverage Ratio', isTotal: true },
    { key: 'effectiveNoi', label: 'Net Operating Income (NOI)' },
    { key: 'totalDebtService', label: 'Total Annual Debt Service' },
    { key: 'cashFlowSurplus', label: 'Net Free Cash Flow Cushion' },
    { key: 'maxSupportableLoanAmount', label: 'Max Supportable Loan Capacity' },
  ],
  inputs: [
    {
      id: 'netOperatingIncome',
      type: 'number',
      label: 'Net Operating Income (NOI)',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 6000000,
    },
    {
      id: 'annualPrincipal',
      type: 'number',
      label: 'Annual Principal Debt Repayments',
      min: 0,
      max: 5000000000,
      step: 100000,
      prefix: '₹',
      default: 2500000,
    },
    {
      id: 'annualInterest',
      type: 'number',
      label: 'Annual Interest Expense',
      min: 0,
      max: 5000000000,
      step: 100000,
      prefix: '₹',
      default: 1500000,
    },
    {
      id: 'targetDscrBenchmark',
      type: 'number',
      label: 'Target Lender DSCR Covenant',
      min: 0.5,
      max: 3.0,
      step: 0.05,
      suffix: 'x',
      default: 1.25,
    },
  ],
};
