import { calculateDepreciationCalculator } from '../business/depreciation-calculator.js';

export const DEPRECIATION_PRESETS = [
  {
    id: 'commercial_vehicle',
    name: 'Commercial Delivery Van (6 Yrs)',
    description: '₹12 Lakhs Fleet Delivery Van (6 Years Useful Life, 5% Scrap Value)',
    badge: 'Vehicles',
    values: {
      assetCost: 1200000,
      salvageValue: 60000,
      usefulLife: 6,
      method: 'slm',
      taxRate: 25,
      currencySymbol: '₹',
    },
  },
  {
    id: 'plant_machinery',
    name: 'Factory CNC Machine (15 Yrs)',
    description: '₹50 Lakhs Heavy Industrial Machinery (15 Years Life, WDV Method)',
    badge: 'Industrial',
    values: {
      assetCost: 5000000,
      salvageValue: 250000,
      usefulLife: 15,
      method: 'wdv',
      taxRate: 30,
      currencySymbol: '₹',
    },
  },
  {
    id: 'computer_servers',
    name: 'Cloud IT Servers & Laptops (3 Yrs)',
    description: '₹15 Lakhs High-Performance Data Center Servers (3 Years Life, DDB)',
    badge: 'IT Hardware',
    values: {
      assetCost: 1500000,
      salvageValue: 30000,
      usefulLife: 3,
      method: 'ddb',
      taxRate: 25,
      currencySymbol: '₹',
    },
  },
  {
    id: 'office_furniture',
    name: 'Corporate Office Fitout (10 Yrs)',
    description: '₹8 Lakhs Workstations & Ergonomic Furniture (10 Years, SLM)',
    badge: 'Office',
    values: {
      assetCost: 800000,
      salvageValue: 40000,
      usefulLife: 10,
      method: 'slm',
      taxRate: 25,
      currencySymbol: '₹',
    },
  },
  {
    id: 'commercial_building',
    name: 'Commercial Warehouse Building (30 Yrs)',
    description: '₹2 Crores Logistics Warehouse (30 Years Useful Life, 10% Residual)',
    badge: 'Real Estate',
    values: {
      assetCost: 20000000,
      salvageValue: 2000000,
      usefulLife: 30,
      method: 'slm',
      taxRate: 25,
      currencySymbol: '₹',
    },
  },
  {
    id: 'units_production',
    name: 'Printing Press (Activity-Based)',
    description: '₹25 Lakhs Offset Printing Press (500,000 Total Lifetime Prints)',
    badge: 'Activity',
    values: {
      assetCost: 2500000,
      salvageValue: 100000,
      usefulLife: 5,
      method: 'units',
      totalUnits: 500000,
      firstYearUnits: 120000,
      taxRate: 25,
      currencySymbol: '₹',
    },
  },
];

export const depreciationCalculatorConfig = {
  title: 'Asset Depreciation & Capital Amortization Schedule',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateDepreciationCalculator,
  presets: DEPRECIATION_PRESETS,
  defaultAssetCost: 500000,
  defaultSalvageValue: 50000,
  defaultUsefulLife: 5,
  defaultMethod: 'slm',
  defaultTaxRate: 25,
  primaryResult: {
    key: 'firstYearDepreciation',
    label: 'Year 1 Depreciation Expense',
  },
  ratioBarItems: [
    { key: 'depreciableAmount', label: 'Depreciable Asset Cost', colorClass: 'bg-primary' },
    { key: 'salvageValue', label: 'Estimated Residual Scrap Value', colorClass: 'bg-amber-500' },
  ],
  summaryItems: [
    { key: 'assetCost', label: 'Initial Asset Purchase Cost' },
    { key: 'salvageValue', label: 'Residual / Salvage Value' },
    { key: 'depreciableAmount', label: 'Total Depreciable Base' },
    { key: 'firstYearDepreciation', label: 'Year 1 Depreciation Write-off' },
    { key: 'totalTaxShield', label: 'Total Cumulative Tax Shield Savings', isTotal: true },
  ],
  inputs: [
    {
      id: 'assetCost',
      type: 'number',
      label: 'Asset Purchase Cost',
      min: 1000,
      max: 500000000,
      step: 10000,
      prefix: '₹',
      minLabel: '₹1,000',
      maxLabel: '₹50 Crores',
      default: 500000,
    },
    {
      id: 'salvageValue',
      type: 'number',
      label: 'Estimated Salvage / Scrap Value',
      min: 0,
      max: 50000000,
      step: 5000,
      prefix: '₹',
      default: 50000,
    },
    {
      id: 'usefulLife',
      type: 'number',
      label: 'Useful Lifespan (Years)',
      min: 1,
      max: 50,
      step: 1,
      suffix: 'Yrs',
      default: 5,
    },
    {
      id: 'method',
      type: 'select',
      label: 'Depreciation Method',
      default: 'slm',
    },
    {
      id: 'taxRate',
      type: 'number',
      label: 'Corporate Tax Rate (%)',
      min: 0,
      max: 50,
      step: 1,
      suffix: '%',
      default: 25,
    },
  ],
  hasAmortizationTable: true,
};
