import { calculateEducationLoan } from '../loans/education-loan-calculator.js';

export const educationLoanCalculatorConfig = {
  title: 'Education Loan & Moratorium Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateEducationLoan,
  primaryResult: {
    key: 'emi',
    label: 'Post-Study Monthly EMI',
  },
  ratioBarItems: [
    { key: 'loanAmount', label: 'Borrowed Principal', colorClass: 'bg-primary' },
    { key: 'totalInterest', label: 'Total Interest', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'loanAmount', label: 'Original Education Loan Amount' },
    { key: 'moratoriumInterest', label: 'Accrued Moratorium Interest' },
    { key: 'totalPrincipalAtRepayment', label: 'Principal at Start of Repayment' },
    { key: 'totalInterest', label: 'Total Cumulative Interest', class: 'text-semantic-down' },
    { key: 'totalPayment', label: 'Total Repayment Outflow', isTotal: true },
  ],
  inputs: [
    {
      id: 'amount',
      type: 'number',
      label: 'Education Loan Amount',
      min: 50000,
      max: 15000000,
      step: 50000,
      prefix: '₹',
      minLabel: '₹50K',
      maxLabel: '₹1.5 Cr',
      default: 1000000,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (p.a.)',
      min: 5,
      max: 20,
      step: 0.1,
      suffix: '%',
      minLabel: '5%',
      maxLabel: '20%',
      default: 9.5,
    },
    {
      id: 'moratoriumYears',
      type: 'number',
      label: 'Moratorium / Study Period (Years)',
      min: 0,
      max: 7,
      step: 1,
      suffix: 'Yrs',
      minLabel: '0 Yrs',
      maxLabel: '7 Yrs',
      default: 4,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Repayment Tenure (Post-Study)',
      maxYears: 15,
      maxMonths: 180,
      default: 10,
    },
  ],
  hasAmortizationTable: true,
};