import { calculateEquityDilutionCalculator } from '../business/equity-dilution-calculator.js';

export const EQUITY_DILUTION_PRESETS = [
  {
    id: 'seed_round',
    name: 'Seed Venture Round',
    description: '₹5 Cr on ₹20 Cr Pre + 10% ESOP Shuffle → 70.0% Founder Ownership',
    badge: 'Seed Round',
    values: {
      preMoneyValuation: 20000000,
      investmentAmount: 5000000,
      founderInitialOwnershipPct: 100,
      targetEsopPoolPct: 10,
      existingEsopPoolPct: 0,
      esopPoolTiming: 'pre_money',
      existingShares: 10000000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'pre_seed_angel',
    name: 'Pre-Seed Angel Round',
    description: '₹1 Cr on ₹6 Cr Pre + 5% ESOP → 80.7% Founder Ownership',
    badge: 'Pre-Seed',
    values: {
      preMoneyValuation: 6000000,
      investmentAmount: 1000000,
      founderInitialOwnershipPct: 100,
      targetEsopPoolPct: 5,
      existingEsopPoolPct: 0,
      esopPoolTiming: 'pre_money',
      existingShares: 10000000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'series_a_growth',
    name: 'Series A Growth Round',
    description: '₹25 Cr on ₹100 Cr Pre + 12% ESOP Top-Up (From 70% Base)',
    badge: 'Series A',
    values: {
      preMoneyValuation: 100000000,
      investmentAmount: 25000000,
      founderInitialOwnershipPct: 70,
      targetEsopPoolPct: 12,
      existingEsopPoolPct: 5,
      esopPoolTiming: 'pre_money',
      existingShares: 12500000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'series_b_expansion',
    name: 'Series B Expansion',
    description: '₹75 Cr on ₹350 Cr Pre (From 50% Founder Base)',
    badge: 'Series B',
    values: {
      preMoneyValuation: 350000000,
      investmentAmount: 75000000,
      founderInitialOwnershipPct: 50,
      targetEsopPoolPct: 10,
      existingEsopPoolPct: 8,
      esopPoolTiming: 'pre_money',
      existingShares: 16000000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'post_money_safe',
    name: 'Post-Money SAFE Round',
    description: '₹2 Cr Investment with Pro-Rata ESOP (Post-Money Structuring)',
    badge: 'SAFE Note',
    values: {
      preMoneyValuation: 12000000,
      investmentAmount: 2000000,
      founderInitialOwnershipPct: 100,
      targetEsopPoolPct: 8,
      existingEsopPoolPct: 0,
      esopPoolTiming: 'post_money',
      existingShares: 10000000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'esop_carveout',
    name: 'Bootstrapped ESOP Carveout',
    description: '10% Unallocated ESOP Pool Creation with Zero Investment Dilution',
    badge: 'ESOP Pool',
    values: {
      preMoneyValuation: 10000000,
      investmentAmount: 0,
      founderInitialOwnershipPct: 100,
      targetEsopPoolPct: 10,
      existingEsopPoolPct: 0,
      esopPoolTiming: 'pre_money',
      existingShares: 10000000,
      currencySymbol: '₹',
    },
  },
];

export const equityDilutionCalculatorConfig = {
  title: 'Equity Dilution & Cap Table Waterfall Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateEquityDilutionCalculator,
  presets: EQUITY_DILUTION_PRESETS,
  defaultPreMoneyValuation: 20000000,
  defaultInvestmentAmount: 5000000,
  defaultFounderInitialOwnershipPct: 100,
  defaultTargetEsopPoolPct: 10,
  defaultExistingEsopPoolPct: 0,
  primaryResult: {
    key: 'founderPostRoundPct',
    label: 'Founding Team Post-Round Ownership (%)',
  },
  ratioBarItems: [
    { key: 'founderPostRoundPct', label: 'Founding Team', colorClass: 'bg-primary' },
    { key: 'investorPostRoundPct', label: 'New Round Investors', colorClass: 'bg-emerald-500' },
    { key: 'esopPostRoundPct', label: 'ESOP Option Pool', colorClass: 'bg-indigo-500' },
  ],
  summaryItems: [
    { key: 'founderPostRoundPct', label: 'Founder Post-Round Ownership (%)', isTotal: true },
    { key: 'postMoneyValuation', label: 'Post-Money Valuation' },
    { key: 'founderPostRoundValue', label: 'Founder Post-Round Stake Value' },
    { key: 'founderDilutionPct', label: 'Effective Round Dilution (%)' },
    { key: 'sharePrice', label: 'Price Per Share' },
  ],
  inputs: [
    {
      id: 'preMoneyValuation',
      type: 'number',
      label: 'Pre-Money Valuation',
      min: 10000,
      max: 10000000000,
      step: 500000,
      prefix: '₹',
      default: 20000000,
    },
    {
      id: 'investmentAmount',
      type: 'number',
      label: 'Investment Capital Raised',
      min: 0,
      max: 5000000000,
      step: 250000,
      prefix: '₹',
      default: 5000000,
    },
    {
      id: 'founderInitialOwnershipPct',
      type: 'number',
      label: 'Founder Pre-Round Ownership (%)',
      min: 1,
      max: 100,
      step: 1,
      suffix: '%',
      default: 100,
    },
    {
      id: 'targetEsopPoolPct',
      type: 'number',
      label: 'Target Post-Round ESOP Pool (%)',
      min: 0,
      max: 30,
      step: 1,
      suffix: '%',
      default: 10,
    },
  ],
};
