import { calculateFdCalculator } from '../savings/fd-calculator.js';

export const FD_CONFIG = {
  id: 'fd-calculator',
  title: 'Fixed Deposit (FD) Calculator',
  category: 'Deposit & Savings Calculators',
  categorySlug: 'savings',
  defaultPrincipal: 100000,
  defaultRate: 7.0,
  defaultTenureYears: 3,

  presets: [
    {
      id: 'standard_1y_cumulative',
      title: '📈 Standard 1-Year Cumulative FD (₹1 Lakh @ 7.0%)',
      description: 'Standard 1-year cumulative fixed deposit with quarterly compounding interest.',
      values: {
        amount: 100000,
        rate: 7.0,
        tenure: 1,
        tenureType: 'years',
        payoutType: 'cumulative',
        isSeniorCitizen: false,
        hasPan: true,
        currency: 'INR',
      },
    },
    {
      id: 'senior_citizen_3y',
      title: '👴 Senior Citizen 3-Year FD (₹5 Lakhs @ 7.5%)',
      description: '3-year senior citizen deposit with +0.50% bonus rate and ₹50,000 Section 194A TDS threshold.',
      values: {
        amount: 500000,
        rate: 7.0,
        tenure: 3,
        tenureType: 'years',
        payoutType: 'cumulative',
        isSeniorCitizen: true,
        hasPan: true,
        currency: 'INR',
      },
    },
    {
      id: 'tax_saver_5y',
      title: '🛡️ 5-Year Tax-Saver FD (₹1.5 Lakhs @ 7.25%)',
      description: '5-year statutory lock-in deposit eligible for Section 80C tax deduction.',
      values: {
        amount: 150000,
        rate: 7.25,
        tenure: 5,
        tenureType: 'years',
        payoutType: 'cumulative',
        isSeniorCitizen: false,
        hasPan: true,
        currency: 'INR',
      },
    },
    {
      id: 'monthly_income_fd',
      title: '💵 Monthly Income Interest Payout (₹10 Lakhs @ 7.0%)',
      description: 'Fixed deposit generating guaranteed monthly interest income payouts for cash flow needs.',
      values: {
        amount: 1000000,
        rate: 7.0,
        tenure: 3,
        tenureType: 'years',
        payoutType: 'monthly',
        isSeniorCitizen: false,
        hasPan: true,
        currency: 'INR',
      },
    },
  ],

  benchmarks: {
    standardBankFdRate: 7.0,
    seniorCitizenBonus: 0.50,
    superSeniorCitizenBonus: 0.75,
    sec194aGeneralThreshold: 40000,
    sec194aSeniorThreshold: 50000,
    sec206aaTdsRateNoPan: 20,
    sec194aTdsRateWithPan: 10,
  },
};

export const fdCalculatorConfig = {
  ...FD_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateFdCalculator,
  primaryResult: {
    key: 'maturityValue',
    label: 'Maturity Value',
  },
  ratioBarItems: [
    { key: 'principal', label: 'Principal Deposit', colorClass: 'bg-primary' },
    { key: 'totalInterest', label: 'Total Interest Earned', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'principal', label: 'Principal Deposit Amount' },
    { key: 'totalInterest', label: 'Total Cumulative Interest Earned', class: 'text-semantic-up' },
    { key: 'estimatedTdsAmount', label: 'Estimated Section 194A TDS Tax', class: 'text-semantic-down' },
    { key: 'maturityValue', label: 'Gross Maturity Value', isTotal: true },
  ],
  inputs: [
    {
      id: 'amount',
      type: 'number',
      label: 'Deposit Amount (₹)',
      min: 1000,
      max: 10000000,
      step: 5000,
      prefix: '₹',
      minLabel: '₹1K',
      maxLabel: '₹1 Cr',
      default: 100000,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (% p.a.)',
      min: 1,
      max: 20,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '20%',
      default: 7.0,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Deposit Tenure',
      maxYears: 10,
      maxMonths: 120,
      default: 3,
    },
  ],
  hasAmortizationTable: false,
};
