import { calculateFdVsDebtFundCalculator } from '../savings/fd-vs-debt-fund-calculator.js';

export const FD_VS_DEBT_FUND_CONFIG = {
  id: 'fd-vs-debt-fund-calculator',
  title: 'FD vs Debt Mutual Fund Calculator (Post-Tax Fixed Income Decision Engine)',
  category: 'Savings Calculators',
  categorySlug: 'savings',

  defaultDepositAmount: 500000,
  defaultTenureYears: 3,
  defaultFdInterestRate: 7.0,
  defaultDebtFundReturnRate: 7.5,
  defaultArbitrageReturnRate: 6.8,
  defaultTaxSlabRate: 30.0,
  defaultCessRate: 4.0,

  taxRulesFY2526: {
    financialYear: 'FY 2025-26 (AY 2026-27)',
    section56FdContext: 'Bank Fixed Deposit interest is taxed as "Income from Other Sources" at user\'s marginal slab rate + 4% Health & Education Cess.',
    section50aaDebtContext: 'Specified Debt Mutual Funds (equity <= 35%) purchased on/after April 1, 2023 are taxed at slab rates upon redemption (Section 50AA). Benefit: Tax Deferral during tenure.',
    section112aArbitrageContext: 'Equity Arbitrage Funds (equity >= 65%) qualify for equity tax rates: 20% STCG (<=1 Yr) or 12.5% LTCG (>1 Yr) above ₹1.25 Lakh annual exemption limit (Finance Bill 2024).',
    ltcgExemptionLimit: 125000,
    ltcgRatePct: 12.5,
    stcgEquityRatePct: 20.0,
    cessRatePct: 4.0,
  },

  presets: [
    {
      id: 'hni_30_slab_3y',
      title: '💼 HNI 30% Tax Slab (₹5L Deposit, 3 Yrs)',
      description: 'Standard 3-year fixed income allocation evaluating FD vs Debt Fund vs Arbitrage Fund for a 30% slab investor.',
      values: {
        depositAmount: 500000,
        tenureYears: 3,
        fdInterestRate: 7.0,
        debtFundReturnRate: 7.5,
        arbitrageReturnRate: 6.8,
        taxSlabRate: 30.0,
        currency: 'INR',
      },
    },
    {
      id: 'senior_citizen_15_slab',
      title: '👴 Senior Citizen High FD Rate (₹10L Deposit @ 7.75% FD)',
      description: 'Senior citizen deposit evaluating higher bank FD rates against debt mutual fund returns.',
      values: {
        depositAmount: 1000000,
        tenureYears: 5,
        fdInterestRate: 7.75,
        debtFundReturnRate: 7.5,
        arbitrageReturnRate: 6.8,
        taxSlabRate: 15.0,
        currency: 'INR',
      },
    },
    {
      id: 'moderate_20_slab_5y',
      title: '🏢 Mid-Slab Investor (₹3L Deposit, 5 Yrs @ 20% Slab)',
      description: '5-year wealth accumulation comparing tax deferral in debt funds against bank FDs.',
      values: {
        depositAmount: 300000,
        tenureYears: 5,
        fdInterestRate: 7.0,
        debtFundReturnRate: 7.5,
        arbitrageReturnRate: 6.8,
        taxSlabRate: 20.0,
        currency: 'INR',
      },
    },
    {
      id: 'large_wealth_50l_3y',
      title: '📈 Wealth Preservation (₹50L Deposit, 3 Yrs @ 30% Slab)',
      description: 'Large capital allocation testing Section 112A ₹1.25L exemption threshold benefits of Arbitrage Funds.',
      values: {
        depositAmount: 5000000,
        tenureYears: 3,
        fdInterestRate: 7.25,
        debtFundReturnRate: 7.5,
        arbitrageReturnRate: 7.0,
        taxSlabRate: 30.0,
        currency: 'INR',
      },
    },
  ],
};

export const fdVsDebtFundCalculatorConfig = {
  ...FD_VS_DEBT_FUND_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateFdVsDebtFundCalculator,
  primaryResult: {
    key: 'postTaxAdvantage',
    label: 'Post-Tax Advantage',
  },
  ratioBarItems: [
    { key: 'postTaxFdValue', label: 'Bank Fixed Deposit', colorClass: 'bg-emerald-500' },
    { key: 'postTaxDebtFundValue', label: 'Debt Mutual Fund', colorClass: 'bg-blue-500' },
    { key: 'postTaxArbitrageValue', label: 'Arbitrage Mutual Fund', colorClass: 'bg-purple-500' },
  ],
  summaryItems: [
    { key: 'winningOption', label: 'Highest Post-Tax Maturity' },
    { key: 'postTaxAdvantage', label: 'Post-Tax Advantage', isTotal: true },
    { key: 'postTaxFdValue', label: 'Bank FD Post-Tax Maturity' },
    { key: 'postTaxDebtFundValue', label: 'Debt Mutual Fund Post-Tax Maturity' },
    { key: 'postTaxArbitrageValue', label: 'Arbitrage Fund Post-Tax Maturity' },
    { key: 'postTaxFdCagr', label: 'Bank FD Post-Tax CAGR' },
    { key: 'postTaxDebtCagr', label: 'Debt Fund Post-Tax CAGR' },
    { key: 'postTaxArbitrageCagr', label: 'Arbitrage Fund Post-Tax CAGR' },
  ],
  inputs: [
    {
      id: 'depositAmount',
      type: 'number',
      label: 'Investment Principal Amount',
      min: 10000,
      max: 100000000,
      step: 10000,
      prefix: '₹',
      minLabel: '₹10k',
      maxLabel: '₹10 Cr',
      default: 500000,
    },
    {
      id: 'tenureYears',
      type: 'number',
      label: 'Investment Horizon (Years)',
      min: 1,
      max: 30,
      step: 1,
      minLabel: '1 Yr',
      maxLabel: '30 Yrs',
      default: 3,
    },
    {
      id: 'fdInterestRate',
      type: 'number',
      label: 'Bank FD Interest Rate (% p.a.)',
      min: 1.0,
      max: 20.0,
      step: 0.1,
      suffix: '%',
      minLabel: '1.0%',
      maxLabel: '20.0%',
      default: 7.0,
    },
    {
      id: 'debtFundReturnRate',
      type: 'number',
      label: 'Debt Mutual Fund Return (% p.a.)',
      min: 1.0,
      max: 25.0,
      step: 0.1,
      suffix: '%',
      minLabel: '1.0%',
      maxLabel: '25.0%',
      default: 7.5,
    },
    {
      id: 'arbitrageReturnRate',
      type: 'number',
      label: 'Arbitrage Fund Return (% p.a.)',
      min: 1.0,
      max: 20.0,
      step: 0.1,
      suffix: '%',
      minLabel: '1.0%',
      maxLabel: '20.0%',
      default: 6.8,
    },
    {
      id: 'taxSlabRate',
      type: 'number',
      label: 'User Income Tax Slab Rate (%)',
      min: 0,
      max: 40.0,
      step: 5.0,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '40%',
      default: 30.0,
    },
  ],
};
