import { calculateFireCalculator } from '../retirement/fire-calculator.js';

export const fireCalculatorConfig = {
  title: 'FIRE Retirement Details',
  currency: 'USD',
  currencySymbol: '$',
  calculateFn: calculateFireCalculator,
  primaryResult: {
    key: 'targetFireCorpus',
    label: 'Target Financial Independence (FI) Corpus',
  },
  ratioBarItems: [
    { key: 'targetFireCorpus', label: 'Target FI Number', colorClass: 'bg-primary' },
    { key: 'projectedPortfolio', label: 'Projected Portfolio Balance', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'yearsToFire', label: 'Years Remaining Until FIRE Retirement' },
    { key: 'futureAnnualExpenses', label: 'Inflation-Adjusted Annual Expenses at FIRE' },
    { key: 'targetFireCorpus', label: 'Target FIRE Corpus (FI Number - Trinity 4% Rule)', isTotal: true },
    { key: 'projectedPortfolio', label: 'Projected Portfolio at FIRE Age', class: 'text-semantic-up' },
    { key: 'fireSurplusOrDeficit', label: 'FIRE Capital Surplus / (Shortfall)' },
  ],
  inputs: [
    {
      id: 'annualExpenses',
      type: 'number',
      label: 'Current Annual Living Expenses ($)',
      min: 10000,
      max: 500000,
      step: 2500,
      prefix: '$',
      minLabel: '$10K',
      maxLabel: '$500K',
      default: 40000,
    },
    {
      id: 'currentAge',
      type: 'number',
      label: 'Current Age (Years)',
      min: 18,
      max: 60,
      step: 1,
      suffix: 'Yrs',
      minLabel: '18 Yrs',
      maxLabel: '60 Yrs',
      default: 30,
    },
    {
      id: 'targetFireAge',
      type: 'number',
      label: 'Target FIRE Retirement Age (Years)',
      min: 30,
      max: 65,
      step: 1,
      suffix: 'Yrs',
      minLabel: '30 Yrs',
      maxLabel: '65 Yrs',
      default: 45,
    },
    {
      id: 'currentPortfolio',
      type: 'number',
      label: 'Current Existing Portfolio Balance ($)',
      min: 0,
      max: 2000000,
      step: 10000,
      prefix: '$',
      minLabel: '$0',
      maxLabel: '$2M',
      default: 100000,
    },
    {
      id: 'annualSavings',
      type: 'number',
      label: 'Annual Contribution Savings ($)',
      min: 1000,
      max: 200000,
      step: 2500,
      prefix: '$',
      minLabel: '$1K',
      maxLabel: '$200K',
      default: 30000,
    },
    {
      id: 'swrPercent',
      type: 'number',
      label: 'Safe Withdrawal Rate - SWR (%)',
      min: 2,
      max: 8,
      step: 0.25,
      suffix: '%',
      minLabel: '2%',
      maxLabel: '8%',
      default: 4,
    },
    {
      id: 'inflationRate',
      type: 'number',
      label: 'Expected Inflation Rate (%)',
      min: 1,
      max: 10,
      step: 0.5,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '10%',
      default: 3,
    },
    {
      id: 'expectedReturn',
      type: 'number',
      label: 'Expected Investment Growth (%)',
      min: 3,
      max: 15,
      step: 0.5,
      suffix: '%',
      minLabel: '3%',
      maxLabel: '15%',
      default: 8,
    },
  ],
  hasAmortizationTable: false,
};