/**
 * Gas Fee Calculator Configuration & Educational Presets
 * Sprint 89 / Flagship #96
 * 
 * Note: Presets represent educational hypothetical EVM scenarios.
 * They do not constitute live RPC gas prices or current network congestion data.
 */

export const GAS_FEE_CONFIG = {
  id: 'gas-fee-calculator',
  title: 'Gas Fee Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Blockchain Economics Research Board',
  lastUpdated: '2026-08-28',

  defaults: {
    feeModel: 'EIP_1559',
    transactionType: 'SIMPLE_TRANSFER',
    gasLimit: 21000,
    gasUsed: 21000,
    baseFeeGwei: 20,
    priorityFeeGwei: 2,
    maxFeeGwei: 35,
    legacyGasPriceGwei: 25,
    nativeTokenPrice: 2500,
    nativeTokenSymbol: 'ETH',
    currency: 'USD',
    transactionCount: 1,
    transactionValueFiat: 500,
    maxAcceptableCostPct: 2.0,
    gasBudgetFiat: 100,
  },

  presets: [
    {
      id: 'simple_eth_transfer',
      label: 'Simple ETH Transfer (21k Gas)',
      icon: '💸',
      feeModel: 'EIP_1559',
      transactionType: 'SIMPLE_TRANSFER',
      gasLimit: 21000,
      gasUsed: 21000,
      baseFeeGwei: 15,
      priorityFeeGwei: 1.5,
      maxFeeGwei: 25,
      nativeTokenPrice: 2500,
      nativeTokenSymbol: 'ETH',
      currency: 'USD',
      transactionCount: 1,
      transactionValueFiat: 500,
      desc: 'Standard Peer-to-Peer Transfer · 21,000 Fixed Gas Units',
    },
    {
      id: 'erc20_token_transfer',
      label: 'ERC-20 Transfer (USDT/USDC)',
      icon: '🪙',
      feeModel: 'EIP_1559',
      transactionType: 'ERC20_TRANSFER',
      gasLimit: 65000,
      gasUsed: 45000,
      baseFeeGwei: 20,
      priorityFeeGwei: 2.0,
      maxFeeGwei: 35,
      nativeTokenPrice: 2500,
      nativeTokenSymbol: 'ETH',
      currency: 'USD',
      transactionCount: 1,
      transactionValueFiat: 1000,
      desc: 'Token Smart Contract Transfer · 45k Consumed / 65k Limit',
    },
    {
      id: 'uniswap_v3_swap',
      label: 'Uniswap v3 DEX Swap',
      icon: '🦄',
      feeModel: 'EIP_1559',
      transactionType: 'DEX_SWAP',
      gasLimit: 180000,
      gasUsed: 130000,
      baseFeeGwei: 25,
      priorityFeeGwei: 2.5,
      maxFeeGwei: 45,
      nativeTokenPrice: 2500,
      nativeTokenSymbol: 'ETH',
      currency: 'USD',
      transactionCount: 1,
      transactionValueFiat: 2500,
      desc: 'Multi-Hop Concentrated Liquidity Swap · 130k Gas Consumed',
    },
    {
      id: 'nft_mint_opensea',
      label: 'NFT Mint / Trade',
      icon: '🖼️',
      feeModel: 'EIP_1559',
      transactionType: 'NFT_MINT',
      gasLimit: 200000,
      gasUsed: 150000,
      baseFeeGwei: 35,
      priorityFeeGwei: 3.0,
      maxFeeGwei: 60,
      nativeTokenPrice: 2500,
      nativeTokenSymbol: 'ETH',
      currency: 'USD',
      transactionCount: 1,
      transactionValueFiat: 300,
      desc: 'ERC-721 / ERC-1155 Smart Contract Minting Execution',
    },
    {
      id: 'defi_yield_harvest',
      label: 'DeFi Interaction / Harvest',
      icon: '🌾',
      feeModel: 'EIP_1559',
      transactionType: 'DEFI_INTERACTION',
      gasLimit: 350000,
      gasUsed: 260000,
      baseFeeGwei: 30,
      priorityFeeGwei: 3.0,
      maxFeeGwei: 55,
      nativeTokenPrice: 2500,
      nativeTokenSymbol: 'ETH',
      currency: 'USD',
      transactionCount: 1,
      transactionValueFiat: 5000,
      desc: 'Complex Liquidity Staking & Yield Harvesting Protocol Call',
    },
    {
      id: 'high_congestion_spike',
      label: 'High Gas Congestion Surge',
      icon: '⚡',
      feeModel: 'EIP_1559',
      transactionType: 'DEX_SWAP',
      gasLimit: 250000,
      gasUsed: 180000,
      baseFeeGwei: 120,
      priorityFeeGwei: 15.0,
      maxFeeGwei: 200,
      nativeTokenPrice: 2500,
      nativeTokenSymbol: 'ETH',
      currency: 'USD',
      transactionCount: 1,
      transactionValueFiat: 2000,
      desc: 'High Network Demand Spike · 135 Gwei Effective Gas Price',
    },
  ],
};
