import { calculateGoalSipCalculator } from '../investment/goal-sip-calculator.js';

export const GOAL_SIP_CONFIG = {
  id: 'goal-sip-calculator',
  title: 'Goal-Based SIP Calculator (Target Corpus Reverse Solver)',
  category: 'Investment Calculators',
  categorySlug: 'investment',

  defaultTargetGoal: 5000000,
  defaultTenureYears: 10,
  defaultExpectedReturnRate: 12.0,
  defaultInflationRate: 6.0,
  defaultStepUpRate: 10.0,
  defaultAdjustForInflation: true,

  rateConvention: 'Monthly Compounding (r / 12 / 100) with Beginning-of-Month SIP Annuity Due Convention',

  presets: [
    {
      id: 'child_education_15y',
      title: '🎓 Child Higher Education Goal (₹25L in 15 Yrs @ 12% Return, 6% Infl)',
      description: 'Calculate monthly SIP needed for a ₹25 Lakh degree in 15 years adjusted for inflation.',
      values: {
        targetGoal: 2500000,
        tenureYears: 15,
        expectedReturnRate: 12.0,
        inflationRate: 6.0,
        stepUpRate: 10.0,
        adjustForInflation: true,
        currency: 'INR',
      },
    },
    {
      id: 'home_downpayment_7y',
      title: '🏠 Home Down Payment Goal (₹50L in 7 Yrs @ 12% Return, 6% Infl)',
      description: 'Determine monthly investment to accumulate a ₹50 Lakh property down payment.',
      values: {
        targetGoal: 5000000,
        tenureYears: 7,
        expectedReturnRate: 12.0,
        inflationRate: 6.0,
        stepUpRate: 10.0,
        adjustForInflation: true,
        currency: 'INR',
      },
    },
    {
      id: 'child_marriage_10y',
      title: '💒 Child Marriage Goal (₹30L in 10 Yrs @ 12% Return, 6% Infl)',
      description: 'Reverse engineer monthly SIP for a ₹30 Lakh marriage goal in 10 years.',
      values: {
        targetGoal: 3000000,
        tenureYears: 10,
        expectedReturnRate: 12.0,
        inflationRate: 6.0,
        stepUpRate: 10.0,
        adjustForInflation: true,
        currency: 'INR',
      },
    },
    {
      id: 'retirement_corpus_20y',
      title: '🏖️ Retirement Target Corpus (₹1 Cr in 20 Yrs @ 12% Return, 6% Infl)',
      description: 'Solve monthly investment required to reach a ₹1 Crore retirement target.',
      values: {
        targetGoal: 10000000,
        tenureYears: 20,
        expectedReturnRate: 12.0,
        inflationRate: 6.0,
        stepUpRate: 10.0,
        adjustForInflation: true,
        currency: 'INR',
      },
    },
  ],
};

export const goalSipCalculatorConfig = {
  ...GOAL_SIP_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateGoalSipCalculator,
  primaryResult: {
    key: 'requiredMonthlySip',
    label: 'Required Monthly SIP',
  },
  ratioBarItems: [
    { key: 'totalInvested', label: 'Total Principal Invested', colorClass: 'bg-primary' },
    { key: 'wealthGain', label: 'Estimated Wealth Returns', colorClass: 'bg-emerald-500' },
  ],
  summaryItems: [
    { key: 'targetGoal', label: 'Target Present Goal Today' },
    { key: 'inflatedTargetGoal', label: 'Inflation-Adjusted Target Goal' },
    { key: 'tenureYears', label: 'Investment Duration (Years)' },
    { key: 'expectedReturnRate', label: 'Expected Annual Return (% p.a.)' },
    { key: 'requiredMonthlySip', label: 'Required Fixed Monthly SIP', isTotal: true },
    { key: 'stepUpStartingSip', label: 'Starting SIP with 10% Annual Step-Up' },
    { key: 'totalInvested', label: 'Total Principal Invested' },
    { key: 'wealthGain', label: 'Estimated Wealth Returns' },
  ],
  inputs: [
    {
      id: 'targetGoal',
      type: 'number',
      label: 'Target Goal Amount Today',
      min: 100000,
      max: 500000000,
      step: 100000,
      prefix: '₹',
      minLabel: '₹1 Lakh',
      maxLabel: '₹50 Cr',
      default: 5000000,
    },
    {
      id: 'tenureYears',
      type: 'number',
      label: 'Time Horizon (Years)',
      min: 1,
      max: 50,
      step: 1,
      minLabel: '1 Yr',
      maxLabel: '50 Yrs',
      default: 10,
    },
    {
      id: 'expectedReturnRate',
      type: 'number',
      label: 'Expected Return Rate (% p.a.)',
      min: 1,
      max: 30.0,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '30%',
      default: 12.0,
    },
    {
      id: 'inflationRate',
      type: 'number',
      label: 'Assumed Annual Inflation Rate (% p.a.)',
      min: 0,
      max: 30.0,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '30%',
      default: 6.0,
    },
    {
      id: 'stepUpRate',
      type: 'number',
      label: 'Annual Step-Up Rate (% p.a.)',
      min: 0,
      max: 50.0,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '50%',
      default: 10.0,
    },
  ],
};
