import { calculateHomeLoan } from '../loans/home-loan-calculator.js';

export const homeLoanCalculatorConfig = {
  title: 'Home Loan & Property Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateHomeLoan,
  primaryResult: {
    key: 'emi',
    label: 'Monthly Home Loan EMI',
  },
  ratioBarItems: [
    { key: 'loanAmount', label: 'Loan Principal', colorClass: 'bg-primary' },
    { key: 'totalInterest', label: 'Total Interest', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'downPaymentAmount', label: 'Down Payment Required' },
    { key: 'loanAmount', label: 'Net Borrowed Loan Principal' },
    { key: 'totalInterest', label: 'Total Interest Payable', class: 'text-semantic-down' },
    { key: 'processingFee', label: 'Est. Processing Fee' },
    { key: 'totalPayment', label: 'Total Payment Outflow', isTotal: true },
  ],
  inputs: [
    {
      id: 'propertyValue',
      type: 'number',
      label: 'Home Property Price',
      min: 500000,
      max: 100000000,
      step: 100000,
      prefix: '₹',
      minLabel: '₹5L',
      maxLabel: '₹10 Cr',
      default: 5000000,
    },
    {
      id: 'downPaymentPct',
      type: 'number',
      label: 'Down Payment (%)',
      min: 0,
      max: 90,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '90%',
      default: 20,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (p.a.)',
      min: 1,
      max: 20,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '20%',
      default: 8.5,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Loan Tenure',
      maxYears: 30,
      maxMonths: 360,
      default: 20,
    },
    {
      id: 'processingFeePct',
      type: 'number',
      label: 'Bank Processing Fee (%)',
      min: 0,
      max: 3,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '3%',
      default: 0.5,
    },
  ],
  hasAmortizationTable: true,
};