/**
 * Impermanent Loss Calculator Configuration & Educational Presets
 * Sprint 87 / Flagship #94
 * 
 * Educational simulation presets for 50/50 constant-product Automated Market Makers (AMMs).
 * Presets represent hypothetical analytical scenarios and do not constitute real-time pool metrics or investment advice.
 */

export const IMPERMANENT_LOSS_CONFIG = {
  id: 'impermanent-loss-calculator',
  title: 'Impermanent Loss Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find DeFi Quantitative Research Board',
  lastUpdated: '2026-08-28',

  defaults: {
    tokenAName: 'Ethereum (ETH)',
    tokenBName: 'USDC / USD',
    initialPriceA: 2000,
    finalPriceA: 4000,
    initialPriceB: 1.0,
    finalPriceB: 1.0,
    initialInvestment: 10000,
    feeAprPct: 15,
    feeRevenueAmount: 0,
    holdingDays: 90,
    currency: 'USD',
    calculationMode: 'EXPLICIT_PRICES',
    priceChangePctA: 100,
    priceChangePctB: 0,
  },

  presets: [
    {
      id: 'eth_2x_bull_move',
      label: '2x Token Surge (ETH / USDC)',
      icon: '🚀',
      tokenAName: 'Ethereum (ETH)',
      tokenBName: 'USDC / USD',
      initialPriceA: 2000,
      finalPriceA: 4000,
      initialPriceB: 1.0,
      finalPriceB: 1.0,
      initialInvestment: 10000,
      feeAprPct: 15,
      holdingDays: 90,
      currency: 'USD',
      calculationMode: 'EXPLICIT_PRICES',
      desc: 'ETH doubles ($2k to $4k) · -5.72% IL · 15% Fee APR over 90 Days',
    },
    {
      id: 'sol_4x_parabolic_surge',
      label: '4x Parabolic Divergence',
      icon: '📈',
      tokenAName: 'Solana (SOL)',
      tokenBName: 'USDC / USD',
      initialPriceA: 50,
      finalPriceA: 200,
      initialPriceB: 1.0,
      finalPriceB: 1.0,
      initialInvestment: 10000,
      feeAprPct: 30,
      holdingDays: 180,
      currency: 'USD',
      calculationMode: 'EXPLICIT_PRICES',
      desc: 'SOL surges 4x ($50 to $200) · -20.00% IL · High Fee Pool',
    },
    {
      id: 'market_50pct_drawdown',
      label: '50% Market Drawdown',
      icon: '📉',
      tokenAName: 'Ethereum (ETH)',
      tokenBName: 'USDC / USD',
      initialPriceA: 3000,
      finalPriceA: 1500,
      initialPriceB: 1.0,
      finalPriceB: 1.0,
      initialInvestment: 10000,
      feeAprPct: 10,
      holdingDays: 60,
      currency: 'USD',
      calculationMode: 'EXPLICIT_PRICES',
      desc: 'ETH drops 50% ($3k to $1.5k) · -5.72% IL · Downside Rebalancing',
    },
    {
      id: 'high_yield_offset',
      label: 'High Trading Fee Offset',
      icon: '💰',
      tokenAName: 'New Token (ABC)',
      tokenBName: 'USDC / USD',
      initialPriceA: 10,
      finalPriceA: 25,
      initialPriceB: 1.0,
      finalPriceB: 1.0,
      initialInvestment: 10000,
      feeAprPct: 60,
      holdingDays: 120,
      currency: 'USD',
      calculationMode: 'EXPLICIT_PRICES',
      desc: '2.5x Move (-9.6% IL) fully offset by 60% Fee APR (Net LP Win!)',
    },
    {
      id: 'stable_pair_low_il',
      label: 'Stablecoin Pair (USDC / USDT)',
      icon: '⚖️',
      tokenAName: 'USDC',
      tokenBName: 'USDT',
      initialPriceA: 1.0,
      finalPriceA: 1.002,
      initialPriceB: 1.0,
      finalPriceB: 0.999,
      initialInvestment: 25000,
      feeAprPct: 8,
      holdingDays: 365,
      currency: 'USD',
      calculationMode: 'EXPLICIT_PRICES',
      desc: 'Pegged 1:1 Assets · Negligible <0.01% IL · Pure Fee Accumulation',
    },
    {
      id: 'symmetric_crypto_pair',
      label: 'Symmetric Crypto Pair (ETH / BTC)',
      icon: '🔄',
      tokenAName: 'Ethereum (ETH)',
      tokenBName: 'Bitcoin (BTC)',
      initialPriceA: 3000,
      finalPriceA: 4500,
      initialPriceB: 60000,
      finalPriceB: 90000,
      initialInvestment: 20000,
      feeAprPct: 12,
      holdingDays: 90,
      currency: 'USD',
      calculationMode: 'EXPLICIT_PRICES',
      desc: 'Both tokens appreciate +50% · 0.00% IL · Relative Ratio Constant',
    },
  ],
};
