import { calculateIrrCalculator } from '../business/irr-calculator.js';

export const IRR_PRESETS = [
  {
    id: 'saas_expansion',
    name: 'Tech SaaS Expansion',
    description: '₹10L CapEx, scaling annual cash flows over 5 years @ 10% Hurdle',
    badge: 'High ROI',
    values: {
      initialInvestment: 1000000,
      cashFlows: [250000, 350000, 400000, 450000, 500000],
      hurdleRate: 10,
      reinvestmentRate: 10,
      financingRate: 8,
      currencySymbol: '₹',
    },
  },
  {
    id: 'manufacturing_automation',
    name: 'Manufacturing Robotics',
    description: '₹50L CNC plant automation with steady operational cost savings @ 12% WACC',
    badge: 'Industrial',
    values: {
      initialInvestment: 5000000,
      cashFlows: [1200000, 1500000, 1800000, 2000000, 2200000],
      hurdleRate: 12,
      reinvestmentRate: 10,
      financingRate: 9,
      currencySymbol: '₹',
    },
  },
  {
    id: 'commercial_real_estate',
    name: 'Commercial Real Estate Syndication',
    description: '₹1 Cr acquisition with 5-yr rental yield + ₹1.2 Cr exit terminal value @ 9% Hurdle',
    badge: 'Real Estate',
    values: {
      initialInvestment: 10000000,
      cashFlows: [900000, 1000000, 1100000, 1200000, 13200000],
      hurdleRate: 9,
      reinvestmentRate: 8,
      financingRate: 8.5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'solar_renewable',
    name: 'Commercial Solar Rooftop Farm',
    description: '₹80L solar installation generating 7 years of power feed-in tariffs @ 8% Hurdle',
    badge: 'Clean Tech',
    values: {
      initialInvestment: 8000000,
      cashFlows: [1500000, 1600000, 1700000, 1750000, 1800000, 1850000, 1900000],
      hurdleRate: 8,
      reinvestmentRate: 8,
      financingRate: 7.5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'retail_storefront',
    name: 'Retail Storefront Rollout',
    description: '₹20L interior buildout and inventory rollout with 5-yr ramp @ 11% Hurdle',
    badge: 'Retail',
    values: {
      initialInvestment: 2000000,
      cashFlows: [400000, 600000, 700000, 800000, 900000],
      hurdleRate: 11,
      reinvestmentRate: 10,
      financingRate: 9.5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'stressed_turnaround',
    name: 'High Hurdle / Turnaround',
    description: '₹25L risky plant refurbishment requiring an aggressive 18% Hurdle rate',
    badge: 'High Risk',
    values: {
      initialInvestment: 2500000,
      cashFlows: [350000, 450000, 600000, 750000, 900000],
      hurdleRate: 18,
      reinvestmentRate: 10,
      financingRate: 12,
      currencySymbol: '₹',
    },
  },
];

export const irrCalculatorConfig = {
  title: 'Internal Rate of Return (IRR), MIRR & Hurdle Rate Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateIrrCalculator,
  presets: IRR_PRESETS,
  defaultInitialInvestment: 1000000,
  defaultHurdleRate: 10,
  defaultReinvestmentRate: 10,
  defaultFinancingRate: 8,
  primaryResult: {
    key: 'irrPercentage',
    label: 'Internal Rate of Return (IRR)',
  },
  ratioBarItems: [
    { key: 'initialInvestment', label: 'Initial Outlay (CapEx)', colorClass: 'bg-rose-500' },
    { key: 'totalInflows', label: 'Total Undiscounted Inflows', colorClass: 'bg-primary' },
  ],
  summaryItems: [
    { key: 'irrPercentage', label: 'Internal Rate of Return (IRR)', isTotal: true },
    { key: 'mirrPercentage', label: 'Modified Internal Rate of Return (MIRR)' },
    { key: 'npvAtHurdle', label: 'Net Present Value (NPV @ Hurdle Rate)' },
    { key: 'profitabilityIndex', label: 'Profitability Index (PI)' },
    { key: 'irrSpread', label: 'IRR Hurdle Rate Spread' },
  ],
  inputs: [
    {
      id: 'initialInvestment',
      type: 'number',
      label: 'Initial Capital Outlay (Year 0 CapEx)',
      min: 0,
      max: 1000000000,
      step: 50000,
      prefix: '₹',
      default: 1000000,
    },
    {
      id: 'hurdleRate',
      type: 'number',
      label: 'Hurdle Rate / Cost of Capital (WACC)',
      min: 0,
      max: 50,
      step: 0.5,
      suffix: '%',
      default: 10,
    },
    {
      id: 'reinvestmentRate',
      type: 'number',
      label: 'MIRR Inflow Reinvestment Rate',
      min: 0,
      max: 50,
      step: 0.5,
      suffix: '%',
      default: 10,
    },
    {
      id: 'financingRate',
      type: 'number',
      label: 'MIRR Debt Financing Cost Rate',
      min: 0,
      max: 50,
      step: 0.5,
      suffix: '%',
      default: 8,
    },
  ],
};
