import { calculateLoanEligibility } from '../loans/loan-eligibility-calculator.js';

export const loanEligibilityCalculatorConfig = {
  title: 'Income & Debt Obligations',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateLoanEligibility,
  primaryResult: {
    key: 'maxLoanAmount',
    label: 'Maximum Eligible Loan Amount',
  },
  ratioBarItems: [
    { key: 'maxLoanAmount', label: 'Max Borrowable Principal', colorClass: 'bg-primary' },
    { key: 'totalInterest', label: 'Total Interest', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'maxTotalEmiAllowed', label: 'Max Total EMI Allowed (FOIR Limit)' },
    { key: 'maxEmiCapacity', label: 'Max Available Monthly EMI Capacity', class: 'text-semantic-up' },
    { key: 'maxLoanAmount', label: 'Maximum Loan Amount Eligibility', isTotal: true },
  ],
  inputs: [
    {
      id: 'grossMonthlyIncome',
      type: 'number',
      label: 'Gross Monthly Take-Home Income',
      min: 10000,
      max: 2000000,
      step: 5000,
      prefix: '₹',
      minLabel: '₹10K',
      maxLabel: '₹20L',
      default: 100000,
    },
    {
      id: 'existingEmis',
      type: 'number',
      label: 'Existing Monthly EMI Obligations',
      min: 0,
      max: 1000000,
      step: 2500,
      prefix: '₹',
      minLabel: '₹0',
      maxLabel: '₹10L',
      default: 10000,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (p.a.)',
      min: 1,
      max: 25,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '25%',
      default: 8.5,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Desired Loan Tenure',
      maxYears: 30,
      maxMonths: 360,
      default: 20,
    },
    {
      id: 'foirPct',
      type: 'number',
      label: 'Bank FOIR Limit (%)',
      min: 20,
      max: 70,
      step: 5,
      suffix: '%',
      minLabel: '20%',
      maxLabel: '70%',
      default: 50,
    },
  ],
  hasAmortizationTable: false,
};