import { calculateLoanPrepayment } from '../loans/loan-prepayment-calculator.js';

export const loanPrepaymentCalculatorConfig = {
  title: 'Loan & Prepayment Parameters',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateLoanPrepayment,
  primaryResult: {
    key: 'interestSaved',
    label: 'Total Interest Saved',
  },
  ratioBarItems: [
    { key: 'newInterest', label: 'Reduced Interest', colorClass: 'bg-primary' },
    { key: 'interestSaved', label: 'Interest Saved', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'originalInterest', label: 'Original Interest Without Prepayment' },
    { key: 'newInterest', label: 'New Interest Payable' },
    { key: 'interestSaved', label: 'Total Interest Savings', class: 'text-semantic-up font-bold' },
    { key: 'monthsSaved', label: 'Tenure Reduced (Months Saved)', class: 'text-primary font-bold' },
    { key: 'totalPayment', label: 'New Net Outflow', isTotal: true },
  ],
  inputs: [
    {
      id: 'amount',
      type: 'number',
      label: 'Original Loan Principal',
      min: 100000,
      max: 50000000,
      step: 50000,
      prefix: '₹',
      minLabel: '₹1L',
      maxLabel: '₹5 Cr',
      default: 2000000,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (p.a.)',
      min: 1,
      max: 25,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '25%',
      default: 8.5,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Original Loan Tenure',
      maxYears: 30,
      maxMonths: 360,
      default: 20,
    },
    {
      id: 'prepaymentAmount',
      type: 'number',
      label: 'One-Time Lump-Sum Prepayment',
      min: 10000,
      max: 10000000,
      step: 10000,
      prefix: '₹',
      minLabel: '₹10K',
      maxLabel: '₹1 Cr',
      default: 200000,
    },
    {
      id: 'prepaymentMonth',
      type: 'number',
      label: 'Prepayment Month (e.g. Month 12)',
      min: 1,
      max: 360,
      step: 1,
      suffix: 'Mo',
      minLabel: '1st Mo',
      maxLabel: '360th Mo',
      default: 12,
    },
  ],
  hasAmortizationTable: false,
};