/**
 * Mining Profitability Calculator Configuration & Educational Presets
 * Sprint 83 / Flagship #90
 * 
 * Note: Presets are representative structural hardware and network archetypes
 * based on published manufacturer specifications and baseline reference metrics.
 * They are not real-time live data feeds.
 */

export const MINING_PROFITABILITY_CONFIG = {
  id: 'mining-profitability-calculator',
  title: 'Mining Profitability Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Quantitative Digital Asset & Blockchain Engineering Board',
  lastUpdated: '2026-08-27',

  defaults: {
    hashrate: 200,
    hashrateUnit: 'TH',
    powerWatts: 3500,
    electricityCost: 0.06,
    cryptoPrice: 65000,
    uptimePct: 99,
    poolFeePct: 2.0,
    hardwareCost: 3500,
    otherDailyCost: 0,
    networkHashrate: 650,
    networkHashrateUnit: 'EH',
    blockReward: 3.125,
    blocksPerDay: 144,
    txFeesPerBlock: 0.25,
    currency: 'USD',
    assetName: 'Bitcoin (BTC)',
  },

  presets: [
    {
      id: 'btc_industrial_s21',
      label: 'Bitcoin (BTC): Next-Gen Industrial ASIC',
      icon: '🏭',
      assetName: 'Bitcoin (BTC)',
      hashrate: 234,
      hashrateUnit: 'TH',
      powerWatts: 3510,
      electricityCost: 0.05,
      cryptoPrice: 65000,
      uptimePct: 99,
      poolFeePct: 1.5,
      hardwareCost: 4200,
      otherDailyCost: 0.5,
      networkHashrate: 650,
      networkHashrateUnit: 'EH',
      blockReward: 3.125,
      blocksPerDay: 144,
      txFeesPerBlock: 0.25,
      currency: 'USD',
      desc: '234 TH/s · 3.51 kW (15 J/TH) · $0.05/kWh Industrial',
    },
    {
      id: 'btc_residential_s19',
      label: 'Bitcoin (BTC): Retail / Home Miner',
      icon: '🏠',
      assetName: 'Bitcoin (BTC)',
      hashrate: 140,
      hashrateUnit: 'TH',
      powerWatts: 3010,
      electricityCost: 0.12,
      cryptoPrice: 65000,
      uptimePct: 98,
      poolFeePct: 2.0,
      hardwareCost: 2400,
      otherDailyCost: 0,
      networkHashrate: 650,
      networkHashrateUnit: 'EH',
      blockReward: 3.125,
      blocksPerDay: 144,
      txFeesPerBlock: 0.25,
      currency: 'USD',
      desc: '140 TH/s · 3.01 kW (21.5 J/TH) · $0.12/kWh Residential',
    },
    {
      id: 'ltc_doge_scrypt',
      label: 'Litecoin & Dogecoin (Scrypt ASIC)',
      icon: '🐕',
      assetName: 'Litecoin (LTC + DOGE)',
      hashrate: 9.5,
      hashrateUnit: 'GH',
      powerWatts: 3425,
      electricityCost: 0.06,
      cryptoPrice: 85,
      uptimePct: 99,
      poolFeePct: 2.0,
      hardwareCost: 3200,
      otherDailyCost: 0.2,
      networkHashrate: 1.2,
      networkHashrateUnit: 'PH',
      blockReward: 6.25,
      blocksPerDay: 576,
      txFeesPerBlock: 0.05,
      currency: 'USD',
      desc: '9.5 GH/s · 3.42 kW · Merged LTC/DOGE Scrypt Mining',
    },
    {
      id: 'kas_kheavyhash',
      label: 'Kaspa (KAS kHeavyHash ASIC)',
      icon: '⚡',
      assetName: 'Kaspa (KAS)',
      hashrate: 10,
      hashrateUnit: 'TH',
      powerWatts: 3400,
      electricityCost: 0.055,
      cryptoPrice: 0.16,
      uptimePct: 99,
      poolFeePct: 1.0,
      hardwareCost: 3800,
      otherDailyCost: 0.3,
      networkHashrate: 450,
      networkHashrateUnit: 'PH',
      blockReward: 110,
      blocksPerDay: 86400,
      txFeesPerBlock: 0.01,
      currency: 'USD',
      desc: '10 TH/s · 3.4 kW · 1 BPS High-Speed PoW',
    },
    {
      id: 'xmr_randomx_cpu',
      label: 'Monero (XMR RandomX CPU)',
      icon: '🔒',
      assetName: 'Monero (XMR)',
      hashrate: 20,
      hashrateUnit: 'KH',
      powerWatts: 150,
      electricityCost: 0.10,
      cryptoPrice: 160,
      uptimePct: 99,
      poolFeePct: 1.0,
      hardwareCost: 650,
      otherDailyCost: 0,
      networkHashrate: 2.8,
      networkHashrateUnit: 'GH',
      blockReward: 0.6,
      blocksPerDay: 720,
      txFeesPerBlock: 0.002,
      currency: 'USD',
      desc: '20 kH/s · 150W · ASIC-Resistant CPU Rig',
    },
    {
      id: 'unprofitable_high_power',
      label: 'Unprofitable / High Power Demo',
      icon: '📉',
      assetName: 'Legacy ASIC Rig',
      hashrate: 110,
      hashrateUnit: 'TH',
      powerWatts: 3250,
      electricityCost: 0.18,
      cryptoPrice: 60000,
      uptimePct: 95,
      poolFeePct: 2.5,
      hardwareCost: 1500,
      otherDailyCost: 1.0,
      networkHashrate: 650,
      networkHashrateUnit: 'EH',
      blockReward: 3.125,
      blocksPerDay: 144,
      txFeesPerBlock: 0.25,
      currency: 'USD',
      desc: '110 TH/s · 3.25 kW · $0.18/kWh (Demonstrating Negative Margin)',
    },
  ],
};
