import { calculateMrrArrCalculator } from '../business/mrr-arr-calculator.js';

export const MRR_PRESETS = [
  {
    id: 'seed_saas',
    name: 'Seed-Stage SaaS',
    description: '₹2.5L MRR, ₹50K New, ₹20K Exp, ₹25K Losses → ₹36L Run-Rate ARR',
    badge: 'Seed Stage',
    values: {
      startingMrr: 250000,
      newMrr: 50000,
      expansionMrr: 20000,
      reactivationMrr: 5000,
      contractionMrr: 10000,
      churnedMrr: 15000,
      valuationMultiple: 8,
      currencySymbol: '₹',
    },
  },
  {
    id: 'growth_scaleup',
    name: 'Series A Scaleup',
    description: '₹25L MRR, ₹4L New, ₹2.5L Exp, ₹2.5L Losses → ₹3.54 Cr Run-Rate ARR',
    badge: 'Series A Scaleup',
    values: {
      startingMrr: 2500000,
      newMrr: 400000,
      expansionMrr: 250000,
      reactivationMrr: 50000,
      contractionMrr: 100000,
      churnedMrr: 150000,
      valuationMultiple: 10,
      currencySymbol: '₹',
    },
  },
  {
    id: 'enterprise_saas',
    name: 'Enterprise B2B Tier',
    description: '₹1.50 Cr MRR, ₹15L New, ₹20L Exp → ₹20.88 Cr Run-Rate ARR',
    badge: 'Enterprise SaaS',
    values: {
      startingMrr: 15000000,
      newMrr: 1500000,
      expansionMrr: 2000000,
      reactivationMrr: 200000,
      contractionMrr: 500000,
      churnedMrr: 800000,
      valuationMultiple: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'expansion_flywheel',
    name: 'Elite Expansion Flywheel',
    description: '₹50L MRR, ₹12L Expansion (118% NRR, 6.0x Quick Ratio)',
    badge: 'Elite NRR',
    values: {
      startingMrr: 5000000,
      newMrr: 600000,
      expansionMrr: 1200000,
      reactivationMrr: 100000,
      contractionMrr: 100000,
      churnedMrr: 200000,
      valuationMultiple: 14,
      currencySymbol: '₹',
    },
  },
  {
    id: 'churn_leaking',
    name: 'High Churn Turnaround',
    description: '₹10L MRR, ₹2L Losses (82% NRR, 0.6x Quick Ratio Alert)',
    badge: 'Turnaround',
    values: {
      startingMrr: 1000000,
      newMrr: 100000,
      expansionMrr: 20000,
      reactivationMrr: 10000,
      contractionMrr: 80000,
      churnedMrr: 120000,
      valuationMultiple: 5,
      currencySymbol: '₹',
    },
  },
  {
    id: 'micro_saas',
    name: 'Bootstrapped Micro-SaaS',
    description: '₹75K MRR, ₹15K New, ₹5K Exp → ₹10.9L Run-Rate ARR',
    badge: 'Micro-SaaS',
    values: {
      startingMrr: 75000,
      newMrr: 15000,
      expansionMrr: 5000,
      reactivationMrr: 2000,
      contractionMrr: 2000,
      churnedMrr: 4000,
      valuationMultiple: 6,
      currencySymbol: '₹',
    },
  },
];

export const mrrArrCalculatorConfig = {
  title: 'MRR / ARR & SaaS Net New Waterfall Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateMrrArrCalculator,
  presets: MRR_PRESETS,
  defaultStartingMrr: 1000000,
  defaultNewMrr: 150000,
  defaultExpansionMrr: 80000,
  defaultReactivationMrr: 20000,
  defaultContractionMrr: 30000,
  defaultChurnedMrr: 40000,
  primaryResult: {
    key: 'endingMrr',
    label: 'Ending Monthly Recurring Revenue (MRR)',
  },
  ratioBarItems: [
    { key: 'newMrr', label: 'New Acquisition MRR', colorClass: 'bg-primary' },
    { key: 'expansionMrr', label: 'Expansion MRR', colorClass: 'bg-emerald-500' },
    { key: 'reactivationMrr', label: 'Reactivation MRR', colorClass: 'bg-indigo-500' },
    { key: 'contractionMrr', label: 'Contraction Loss', colorClass: 'bg-amber-500' },
    { key: 'churnedMrr', label: 'Churned Account Loss', colorClass: 'bg-rose-500' },
  ],
  summaryItems: [
    { key: 'endingMrr', label: 'Ending Monthly Recurring Revenue (MRR)', isTotal: true },
    { key: 'runRateArr', label: 'Run-Rate Annual Recurring Revenue (ARR)' },
    { key: 'netNewMrr', label: 'Net New MRR Added' },
    { key: 'nrrPct', label: 'Net Revenue Retention (NRR %)' },
    { key: 'quickRatio', label: 'SaaS Quick Ratio' },
  ],
  inputs: [
    {
      id: 'startingMrr',
      type: 'number',
      label: 'Starting MRR at Beginning of Period',
      min: 0,
      max: 1000000000,
      step: 25000,
      prefix: '₹',
      default: 1000000,
    },
    {
      id: 'newMrr',
      type: 'number',
      label: 'New Customer Acquisition MRR',
      min: 0,
      max: 500000000,
      step: 10000,
      prefix: '₹',
      default: 150000,
    },
    {
      id: 'expansionMrr',
      type: 'number',
      label: 'Expansion & Account Upsell MRR',
      min: 0,
      max: 500000000,
      step: 10000,
      prefix: '₹',
      default: 80000,
    },
    {
      id: 'churnedMrr',
      type: 'number',
      label: 'Churned Account Revenue Loss',
      min: 0,
      max: 500000000,
      step: 10000,
      prefix: '₹',
      default: 40000,
    },
  ],
};
