/**
 * Configuration, educational presets, metadata, and default parameters for NFT Royalty Calculator.
 */

import {
  ROYALTY_BASIS_MODELS,
  SALE_TYPES,
  FIAT_CURRENCIES,
  CRYPTO_DENOMINATIONS,
} from '../crypto/nft-royalty-calculator.js';

export const NFT_ROYALTY_CONFIG = {
  id: 'nft-royalty-calculator',
  name: 'NFT Royalty Calculator',
  slug: 'nft-royalty-calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  metaTitle: 'NFT Royalty Calculator: Creator Earnings & Secondary Resale Fee Engine',
  metaDescription: 'Calculate NFT creator royalties, marketplace fees, seller net proceeds, lifetime multi-sale resale earnings, and marketplace enforcement risks.',
  
  defaults: {
    salePrice: 2.0,
    royaltyPct: 5.0,
    marketplaceFeePct: 2.5,
    otherFees: 0.005,
    enforcementPct: 100,
    royaltyBasis: 'GROSS_SALE_PRICE',
    saleType: 'SECONDARY_RESALE',
    currency: 'USD',
    cryptoDenomination: 'ETH',
    cryptoPriceFiat: 2500,
  },

  presets: [
    {
      id: 'standard_secondary_5pct',
      label: 'Standard 5% Royalty',
      icon: '🎨',
      desc: 'Standard secondary resale on Ethereum (2.0 ETH, 5% royalty, 2.5% marketplace fee).',
      salePrice: 2.0,
      royaltyPct: 5.0,
      marketplaceFeePct: 2.5,
      otherFees: 0.005,
      enforcementPct: 100,
      royaltyBasis: 'GROSS_SALE_PRICE',
      saleType: 'SECONDARY_RESALE',
      cryptoDenomination: 'ETH',
      cryptoPriceFiat: 2500,
      currency: 'USD',
    },
    {
      id: 'primary_mint',
      label: 'Primary Mint / Initial Sale',
      icon: '🚀',
      desc: 'Initial collection launch: Creator retains 100% of proceeds minus 2.5% platform fee.',
      salePrice: 1.0,
      royaltyPct: 0,
      marketplaceFeePct: 2.5,
      otherFees: 0.01,
      enforcementPct: 100,
      royaltyBasis: 'GROSS_SALE_PRICE',
      saleType: 'PRIMARY_MINT',
      cryptoDenomination: 'ETH',
      cryptoPriceFiat: 2500,
      currency: 'USD',
    },
    {
      id: 'high_marketplace_fee',
      label: 'High Marketplace Fee (5%)',
      icon: '🏛️',
      desc: 'Curated platform with 5% marketplace fee, 7.5% royalty, and gross basis deduction.',
      salePrice: 10.0,
      royaltyPct: 7.5,
      marketplaceFeePct: 5.0,
      otherFees: 0.02,
      enforcementPct: 100,
      royaltyBasis: 'GROSS_SALE_PRICE',
      saleType: 'SECONDARY_RESALE',
      cryptoDenomination: 'SOL',
      cryptoPriceFiat: 140,
      currency: 'USD',
    },
    {
      id: 'creator_lifetime_resales',
      label: 'Creator Lifetime Resales',
      icon: '📈',
      desc: 'Simulate cumulative creator royalty revenue across a 5-step appreciating secondary trajectory.',
      salePrice: 3.5,
      royaltyPct: 7.0,
      marketplaceFeePct: 2.5,
      otherFees: 0.008,
      enforcementPct: 100,
      royaltyBasis: 'GROSS_SALE_PRICE',
      saleType: 'SECONDARY_RESALE',
      cryptoDenomination: 'ETH',
      cryptoPriceFiat: 2500,
      currency: 'USD',
    },
    {
      id: 'zero_royalty_marketplace',
      label: 'Zero-Royalty Marketplace',
      icon: '⚡',
      desc: 'Optional tipping platform (0% enforcement) where creator receives $0 from secondary trade.',
      salePrice: 2.5,
      royaltyPct: 5.0,
      marketplaceFeePct: 0.5,
      otherFees: 0.003,
      enforcementPct: 0,
      royaltyBasis: 'GROSS_SALE_PRICE',
      saleType: 'SECONDARY_RESALE',
      cryptoDenomination: 'ETH',
      cryptoPriceFiat: 2500,
      currency: 'USD',
    },
    {
      id: 'royalty_enforcement_risk',
      label: 'Enforcement Risk (50%)',
      icon: '🛡️',
      desc: 'Mixed marketplace environment where only 50% of secondary volume honors creator royalties.',
      salePrice: 4.0,
      royaltyPct: 6.0,
      marketplaceFeePct: 2.0,
      otherFees: 0.005,
      enforcementPct: 50,
      royaltyBasis: 'GROSS_SALE_PRICE',
      saleType: 'SECONDARY_RESALE',
      cryptoDenomination: 'ETH',
      cryptoPriceFiat: 2500,
      currency: 'USD',
    },
  ],

  royaltyBasisModels: ROYALTY_BASIS_MODELS,
  saleTypes: SALE_TYPES,
  fiatCurrencies: FIAT_CURRENCIES,
  cryptoDenominations: CRYPTO_DENOMINATIONS,
};
