import { calculateNpsCalculator } from '../retirement/nps-calculator.js';

export const npsCalculatorConfig = {
  title: 'NPS Retirement Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateNpsCalculator,
  primaryResult: {
    key: 'totalMaturityCorpus',
    label: 'Total NPS Maturity Corpus (Age 60)',
  },
  ratioBarItems: [
    { key: 'lumpSumAmount', label: 'Tax-Free Lump Sum (60%)', colorClass: 'bg-semantic-up' },
    { key: 'annuityCorpus', label: 'Annuity Pension Corpus (40%)', colorClass: 'bg-primary' },
  ],
  summaryItems: [
    { key: 'totalInvestment', label: 'Total Out-of-Pocket Contribution' },
    { key: 'interestEarned', label: 'Total Investment Wealth Growth' },
    { key: 'totalMaturityCorpus', label: 'Total NPS Maturity Corpus at Age 60', isTotal: true },
    { key: 'lumpSumAmount', label: 'Tax-Free Lump Sum Withdrawal (Sec 10(12A))', class: 'text-semantic-up' },
    { key: 'annuityCorpus', label: 'Annuity Re-investment Corpus' },
    { key: 'monthlyPension', label: 'Estimated Monthly Pension Income', class: 'text-primary font-bold' },
  ],
  inputs: [
    {
      id: 'monthlyInvestment',
      type: 'number',
      label: 'Monthly NPS Contribution (₹)',
      min: 500,
      max: 150000,
      step: 500,
      prefix: '₹',
      minLabel: '₹500',
      maxLabel: '₹1.5L',
      default: 10000,
    },
    {
      id: 'currentAge',
      type: 'number',
      label: 'Current Age (Years)',
      min: 18,
      max: 59,
      step: 1,
      suffix: 'Yrs',
      minLabel: '18 Yrs',
      maxLabel: '59 Yrs',
      default: 30,
    },
    {
      id: 'expectedReturn',
      type: 'number',
      label: 'Expected NPS Growth Rate (%)',
      min: 5,
      max: 18,
      step: 0.5,
      suffix: '%',
      minLabel: '5%',
      maxLabel: '18%',
      default: 10,
    },
    {
      id: 'annuityPercent',
      type: 'number',
      label: 'Annuity Re-investment Ratio (%)',
      min: 40,
      max: 100,
      step: 5,
      suffix: '%',
      minLabel: '40%',
      maxLabel: '100%',
      default: 40,
    },
    {
      id: 'expectedAnnuityRate',
      type: 'number',
      label: 'Expected Annuity Rate (%)',
      min: 4,
      max: 10,
      step: 0.5,
      suffix: '%',
      minLabel: '4%',
      maxLabel: '10%',
      default: 6,
    },
  ],
  hasAmortizationTable: false,
};