import { calculatePersonalLoan } from '../loans/personal-loan-calculator.js';

export const personalLoanCalculatorConfig = {
  title: 'Personal Loan Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculatePersonalLoan,
  primaryResult: {
    key: 'emi',
    label: 'Monthly Personal Loan EMI',
  },
  ratioBarItems: [
    { key: 'loanAmount', label: 'Principal', colorClass: 'bg-primary' },
    { key: 'totalInterest', label: 'Interest', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'loanAmount', label: 'Borrowed Loan Principal' },
    { key: 'totalInterest', label: 'Total Interest Payable', class: 'text-semantic-down' },
    { key: 'processingFee', label: 'Processing Fee (Est.)' },
    { key: 'totalPayment', label: 'Total Repayment Amount', isTotal: true },
  ],
  inputs: [
    {
      id: 'amount',
      type: 'number',
      label: 'Personal Loan Amount',
      min: 10000,
      max: 4000000,
      step: 10000,
      prefix: '₹',
      minLabel: '₹10K',
      maxLabel: '₹40L',
      default: 500000,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'Interest Rate (p.a.)',
      min: 8,
      max: 30,
      step: 0.1,
      suffix: '%',
      minLabel: '8%',
      maxLabel: '30%',
      default: 11.5,
    },
    {
      id: 'tenure',
      type: 'tenure',
      label: 'Tenure',
      maxYears: 7,
      maxMonths: 84,
      default: 3,
    },
    {
      id: 'processingFeePct',
      type: 'number',
      label: 'Processing Fee (%)',
      min: 0,
      max: 5,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '5%',
      default: 1.0,
    },
  ],
  hasAmortizationTable: true,
};