import { calculatePpfCalculator } from '../savings/ppf-calculator.js';

export const PPF_CONFIG = {
  id: 'ppf-calculator',
  title: 'Public Provident Fund (PPF) Calculator',
  category: 'Deposit & Savings Calculators',
  categorySlug: 'savings',
  defaultAnnualDeposit: 150000,
  defaultInterestRate: 7.1,
  defaultTenureYears: 15,

  presets: [
    {
      id: 'max_80c_yearly',
      title: '🌟 Max Statutory Cap (₹1.5 Lakhs/yr for 15 Years)',
      description: 'Maximizing the annual Section 80C limit for 15 years to build a ₹40L+ tax-free retirement corpus.',
      values: {
        annualDeposit: 150000,
        depositFrequency: 'yearly',
        depositDay: 'before_5th',
        interestRate: 7.1,
        tenureYears: 15,
        extensionMode: 'with_contribution',
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
    {
      id: 'monthly_sip_12500',
      title: '📅 Monthly SIP (₹12,500/month before 5th)',
      description: 'Disciplined monthly installment of ₹12,500 deposited on or before the 5th of every month.',
      values: {
        annualDeposit: 150000,
        depositFrequency: 'monthly',
        depositDay: 'before_5th',
        interestRate: 7.1,
        tenureYears: 15,
        extensionMode: 'with_contribution',
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
    {
      id: 'extended_25y_wealth',
      title: '🚀 25-Year Wealth Compounding (2 Extension Blocks)',
      description: 'Extending PPF for 2 five-year blocks (25 years total) with continued annual contributions.',
      values: {
        annualDeposit: 150000,
        depositFrequency: 'yearly',
        depositDay: 'before_5th',
        interestRate: 7.1,
        tenureYears: 25,
        extensionMode: 'with_contribution',
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
    {
      id: 'starter_50k',
      title: '🌱 Starter Savers (₹50,000/yr for 15 Years)',
      description: 'Moderate tax saver investing ₹50,000 annually to build a guaranteed ₹13.5L+ tax-free nest egg.',
      values: {
        annualDeposit: 50000,
        depositFrequency: 'yearly',
        depositDay: 'before_5th',
        interestRate: 7.1,
        tenureYears: 15,
        extensionMode: 'with_contribution',
        marginalTaxRate: 20,
        currency: 'INR',
      },
    },
  ],

  benchmarks: {
    statutoryInterestRate: 7.1,
    sec80cMaxDepositCap: 150000,
    minAnnualDeposit: 500,
    statutoryLockInYears: 15,
    extensionBlockYears: 5,
    eeeTaxStatus: '100% Tax-Free (Sec 10(11))',
  },
};

export const ppfCalculatorConfig = {
  ...PPF_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculatePpfCalculator,
  primaryResult: {
    key: 'finalBalance',
    label: '100% Tax-Free Maturity Balance',
  },
  ratioBarItems: [
    { key: 'totalDeposits', label: 'Total Contributions', colorClass: 'bg-primary' },
    { key: 'totalInterestEarned', label: 'Tax-Free Compound Interest', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'totalDeposits', label: 'Total Deposits Paid' },
    { key: 'totalInterestEarned', label: 'Total Compound Interest Earned (EEE)', class: 'text-semantic-up' },
    { key: 'totalSec80cTaxSaved', label: 'Total Section 80C Tax Saved', class: 'text-purple-600' },
    { key: 'finalBalance', label: 'Total Tax-Free Maturity Corpus', isTotal: true },
  ],
  inputs: [
    {
      id: 'annualDeposit',
      type: 'number',
      label: 'Annual Deposit Amount (₹)',
      min: 500,
      max: 150000,
      step: 5000,
      prefix: '₹',
      minLabel: '₹500',
      maxLabel: '₹1.5L',
      default: 150000,
    },
    {
      id: 'interestRate',
      type: 'number',
      label: 'Notified Interest Rate (% p.a.)',
      min: 1,
      max: 15,
      step: 0.1,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '15%',
      default: 7.1,
    },
    {
      id: 'tenureYears',
      type: 'number',
      label: 'PPF Tenure (Years)',
      min: 15,
      max: 30,
      step: 5,
      suffix: 'Yrs',
      minLabel: '15 Yrs',
      maxLabel: '30 Yrs',
      default: 15,
    },
  ],
  hasAmortizationTable: false,
};
