import { calculateProvidentFundCalculator } from '../retirement/provident-fund-calculator.js';

export const providentFundCalculatorConfig = {
  title: 'EPF Retirement Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateProvidentFundCalculator,
  primaryResult: {
    key: 'finalEpfBalance',
    label: 'Total EPF Maturity Balance at Retirement',
  },
  ratioBarItems: [
    { key: 'totalEmployeeContribution', label: 'Employee Contribution (12%)', colorClass: 'bg-primary' },
    { key: 'totalEmployerContribution', label: 'Employer Contribution (3.67%)', colorClass: 'bg-semantic-up' },
    { key: 'totalInterestEarned', label: 'Compound Interest Earned', colorClass: 'bg-accent-amber' },
  ],
  summaryItems: [
    { key: 'yearsInvested', label: 'Years Invested Until Retirement' },
    { key: 'totalEmployeeContribution', label: 'Total Employee Contribution (12%)' },
    { key: 'totalEmployerContribution', label: 'Total Employer EPF Contribution (3.67%)', class: 'text-semantic-up' },
    { key: 'totalContribution', label: 'Total Combined Contributions' },
    { key: 'totalInterestEarned', label: 'Total Compound Interest Earned' },
    { key: 'finalEpfBalance', label: 'Total Final EPF Maturity Balance', isTotal: true },
  ],
  inputs: [
    {
      id: 'monthlyBasicSalary',
      type: 'number',
      label: 'Monthly Basic Salary + DA (₹)',
      min: 2000,
      max: 500000,
      step: 1000,
      prefix: '₹',
      minLabel: '₹2K',
      maxLabel: '₹5L',
      default: 30000,
    },
    {
      id: 'currentAge',
      type: 'number',
      label: 'Current Age (Years)',
      min: 18,
      max: 57,
      step: 1,
      suffix: 'Yrs',
      minLabel: '18 Yrs',
      maxLabel: '57 Yrs',
      default: 25,
    },
    {
      id: 'retirementAge',
      type: 'number',
      label: 'Retirement Age (Years)',
      min: 50,
      max: 65,
      step: 1,
      suffix: 'Yrs',
      minLabel: '50 Yrs',
      maxLabel: '65 Yrs',
      default: 58,
    },
    {
      id: 'epfInterestRate',
      type: 'number',
      label: 'Declared EPFO Interest Rate (%)',
      min: 6,
      max: 12,
      step: 0.05,
      suffix: '%',
      minLabel: '6%',
      maxLabel: '12%',
      default: 8.25,
    },
    {
      id: 'annualSalaryIncrease',
      type: 'number',
      label: 'Expected Annual Salary Increase (%)',
      min: 0,
      max: 20,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '20%',
      default: 5,
    },
    {
      id: 'currentEpfBalance',
      type: 'number',
      label: 'Current Existing EPF Balance (₹)',
      min: 0,
      max: 5000000,
      step: 10000,
      prefix: '₹',
      minLabel: '₹0',
      maxLabel: '₹50L',
      default: 0,
    },
  ],
  hasAmortizationTable: false,
};