import { calculateQuickRatioCalculator } from '../business/quick-ratio-calculator.js';

export const QUICK_RATIO_PRESETS = [
  {
    id: 'manufacturing_plant',
    name: 'Manufacturing & Industrial Plant',
    description: '₹75L Quick Assets, ₹40L Inventory, ₹50L Current Liabilities → 1.50x Quick Ratio',
    badge: 'Manufacturing',
    values: {
      calculationMode: 'component',
      cashAndEquivalents: 2500000,
      marketableSecurities: 1500000,
      accountsReceivable: 3500000,
      inventory: 4000000,
      prepaidExpenses: 500000,
      currentLiabilities: 5000000,
      dailyOperatingExpenses: 60000,
      targetQuickRatio: 1.0,
      currencySymbol: '₹',
    },
  },
  {
    id: 'saas_tech',
    name: 'SaaS & Technology Startup',
    description: '₹1.0 Cr Quick Assets, Zero Inventory, ₹40L Liabilities → 2.50x Quick Ratio',
    badge: 'SaaS / Tech',
    values: {
      calculationMode: 'component',
      cashAndEquivalents: 5000000,
      marketableSecurities: 2000000,
      accountsReceivable: 3000000,
      inventory: 0,
      prepaidExpenses: 300000,
      currentLiabilities: 4000000,
      dailyOperatingExpenses: 40000,
      targetQuickRatio: 1.25,
      currencySymbol: '₹',
    },
  },
  {
    id: 'retail_supermarket',
    name: 'Retail & Supermarket (Inventory Heavy)',
    description: '₹20L Quick Assets, ₹80L Inventory, ₹40L Liabilities → 0.50x Quick Ratio',
    badge: 'Retail',
    values: {
      calculationMode: 'component',
      cashAndEquivalents: 1000000,
      marketableSecurities: 500000,
      accountsReceivable: 500000,
      inventory: 8000000,
      prepaidExpenses: 200000,
      currentLiabilities: 4000000,
      dailyOperatingExpenses: 30000,
      targetQuickRatio: 0.8,
      currencySymbol: '₹',
    },
  },
  {
    id: 'healthcare_clinic',
    name: 'Healthcare & Diagnostic Clinic',
    description: '₹80L Quick Assets, ₹15L Medical Supplies, ₹45L Liabilities → 1.78x Quick Ratio',
    badge: 'Healthcare',
    values: {
      calculationMode: 'component',
      cashAndEquivalents: 3000000,
      marketableSecurities: 1000000,
      accountsReceivable: 4000000,
      inventory: 1500000,
      prepaidExpenses: 400000,
      currentLiabilities: 4500000,
      dailyOperatingExpenses: 50000,
      targetQuickRatio: 1.2,
      currencySymbol: '₹',
    },
  },
  {
    id: 'construction_epc',
    name: 'Construction & EPC Contractor',
    description: '₹90L Quick Assets, ₹50L WIP Materials, ₹70L Liabilities → 1.29x Quick Ratio',
    badge: 'Construction',
    values: {
      calculationMode: 'component',
      cashAndEquivalents: 2000000,
      marketableSecurities: 1000000,
      accountsReceivable: 6000000,
      inventory: 5000000,
      prepaidExpenses: 800000,
      currentLiabilities: 7000000,
      dailyOperatingExpenses: 80000,
      targetQuickRatio: 1.0,
      currencySymbol: '₹',
    },
  },
  {
    id: 'wholesale_fmcg',
    name: 'Wholesale & FMCG Distribution',
    description: '₹70L Quick Assets, ₹60L Stock, ₹55L Liabilities → 1.27x Quick Ratio',
    badge: 'Wholesale',
    values: {
      calculationMode: 'component',
      cashAndEquivalents: 1500000,
      marketableSecurities: 1000000,
      accountsReceivable: 4500000,
      inventory: 6000000,
      prepaidExpenses: 300000,
      currentLiabilities: 5500000,
      dailyOperatingExpenses: 70000,
      targetQuickRatio: 1.1,
      currencySymbol: '₹',
    },
  },
];

export const quickRatioCalculatorConfig = {
  title: 'Quick Ratio (Acid-Test Ratio) Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateQuickRatioCalculator,
  presets: QUICK_RATIO_PRESETS,
  defaultCashAndEquivalents: 2500000,
  defaultMarketableSecurities: 1500000,
  defaultAccountsReceivable: 3500000,
  defaultCurrentLiabilities: 5000000,
  primaryResult: {
    key: 'quickRatio',
    label: 'Quick Ratio (Acid-Test)',
  },
  ratioBarItems: [
    { key: 'cashAndEquivalents', label: 'Cash & Bank Balances', colorClass: 'bg-primary' },
    { key: 'marketableSecurities', label: 'Marketable Securities', colorClass: 'bg-emerald-500' },
    { key: 'accountsReceivable', label: 'Accounts Receivable', colorClass: 'bg-indigo-500' },
    { key: 'inventory', label: 'Inventory (Excluded)', colorClass: 'bg-amber-500' },
  ],
  summaryItems: [
    { key: 'quickRatio', label: 'Quick Ratio (Acid-Test)', isTotal: true },
    { key: 'currentRatio', label: 'Current Ratio' },
    { key: 'cashRatio', label: 'Cash Ratio' },
    { key: 'quickAssets', label: 'Total Quick Assets' },
    { key: 'quickWorkingCapital', label: 'Quick Working Capital Surplus / (Deficit)' },
  ],
  inputs: [
    {
      id: 'cashAndEquivalents',
      type: 'number',
      label: 'Cash & Cash Equivalents',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 2500000,
    },
    {
      id: 'marketableSecurities',
      type: 'number',
      label: 'Marketable Securities / Short Investments',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 1500000,
    },
    {
      id: 'accountsReceivable',
      type: 'number',
      label: 'Accounts Receivable (Net)',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 3500000,
    },
    {
      id: 'currentLiabilities',
      type: 'number',
      label: 'Total Current Liabilities',
      min: 0,
      max: 10000000000,
      step: 100000,
      prefix: '₹',
      default: 5000000,
    },
  ],
};
