/**
 * Remittance Fee Calculator Configuration & Presets
 * Sprint 81 / Flagship #88
 */

export const REMITTANCE_FEE_CONFIG = {
  id: 'remittance-fee-calculator',
  title: 'Remittance Fee Calculator',
  category: 'currency',
  categoryName: 'Currency & Cost Calculators',
  version: '3.0.0',
  author: 'Fintools Find Cross-Border Remittance & FX Advisory Board',
  lastUpdated: '2026-08-27',

  defaults: {
    sendAmount: 1000,
    fromCurrency: 'USD',
    toCurrency: 'INR',
    fixedFee: 0,
    percentageFee: 0,
    fxSpreadPct: 1.2,
    recipientFee: 0,
    intermediaryFee: 0,
    feeMode: 'ADD_ON_TOP',
  },

  presets: [
    {
      id: 'us_india_fintech',
      label: 'US → India (Fintech ACH / Zero Fee)',
      icon: '🇺🇸',
      sendAmount: 1000,
      fromCurrency: 'USD',
      toCurrency: 'INR',
      fixedFee: 0,
      percentageFee: 0,
      fxSpreadPct: 0.9,
      recipientFee: 0,
      intermediaryFee: 0,
      feeMode: 'ADD_ON_TOP',
      desc: '$1,000 USD → ₹86.7k INR · 0.9% FX Spread',
    },
    {
      id: 'uae_india_exchange',
      label: 'UAE → India (Exchange House / IMPS)',
      icon: '🇦🇪',
      sendAmount: 2500,
      fromCurrency: 'AED',
      toCurrency: 'INR',
      fixedFee: 15,
      percentageFee: 0,
      fxSpreadPct: 0.75,
      recipientFee: 0,
      intermediaryFee: 0,
      feeMode: 'ADD_ON_TOP',
      desc: '2,500 AED → ₹59.1k INR · 15 AED Fee + 0.75% Spread',
    },
    {
      id: 'uk_india_bank',
      label: 'UK → India (Direct Bank Transfer)',
      icon: '🇬🇧',
      sendAmount: 800,
      fromCurrency: 'GBP',
      toCurrency: 'INR',
      fixedFee: 2.50,
      percentageFee: 0,
      fxSpreadPct: 0.8,
      recipientFee: 0,
      intermediaryFee: 0,
      feeMode: 'ADD_ON_TOP',
      desc: '£800 GBP → ₹88.4k INR · £2.50 Fee + 0.8% Spread',
    },
    {
      id: 'swift_wire_high_cost',
      label: 'International SWIFT Wire (Traditional Bank)',
      icon: '🏛️',
      sendAmount: 5000,
      fromCurrency: 'USD',
      toCurrency: 'EUR',
      fixedFee: 35, // Outgoing wire fee
      percentageFee: 0,
      fxSpreadPct: 2.5, // 2.5% Retail Bank Margin
      recipientFee: 10, // Beneficiary receiving fee in EUR
      intermediaryFee: 15, // Correspondent bank deduction
      feeMode: 'ADD_ON_TOP',
      desc: '$5,000 USD → €4,457 EUR · $35 Fee + 2.5% Spread + SWIFT Intermediary',
    },
    {
      id: 'canada_india_transfer',
      label: 'Canada → India (Interac Online)',
      icon: '🇨🇦',
      sendAmount: 1500,
      fromCurrency: 'CAD',
      toCurrency: 'INR',
      fixedFee: 3.99,
      percentageFee: 0,
      fxSpreadPct: 1.1,
      recipientFee: 0,
      intermediaryFee: 0,
      feeMode: 'ADD_ON_TOP',
      desc: 'C$1,500 CAD → ₹94.3k INR · C$3.99 Fee + 1.1% Spread',
    },
    {
      id: 'europe_us_transfer',
      label: 'Eurozone → US (SEPA / Wire)',
      icon: '🇪🇺',
      sendAmount: 2000,
      fromCurrency: 'EUR',
      toCurrency: 'USD',
      fixedFee: 4.50,
      percentageFee: 0.2,
      fxSpreadPct: 0.8,
      recipientFee: 0,
      intermediaryFee: 0,
      feeMode: 'ADD_ON_TOP',
      desc: '€2,000 EUR → $2,156 USD · Low Fee SEPA Corridor',
    },
  ],
};
