import { calculateRentVsBuyCalculator } from '../loans/rent-vs-buy-calculator.js';

export const RENT_VS_BUY_CONFIG = {
  id: 'rent-vs-buy-calculator',
  title: 'Rent vs Buy Calculator (Housing Financial Decision Engine)',
  category: 'Loan Calculators',
  categorySlug: 'loans',

  defaultPropertyPrice: 7500000,
  defaultMonthlyRent: 25000,
  defaultDownPaymentPct: 20.0,
  defaultHomeLoanRate: 8.5,
  defaultTenureYears: 20,
  defaultPropertyAppreciationRate: 5.0,
  defaultRentInflationRate: 7.0,
  defaultInvestmentReturnRate: 12.0,
  defaultAnnualMaintenanceRate: 1.0,
  defaultPurchaseCostPct: 5.0,
  defaultSellingCostPct: 2.0,
  defaultTaxSlabRate: 30.0,
  defaultIncludeTaxBenefits: false,

  referenceData: {
    taxContext: 'Income Tax Act Section 24(b) allows up to ₹2 Lakhs interest deduction on self-occupied house property under Old Tax Regime (AY 2025-26). Section 80C allows principal deduction up to ₹1.5 Lakhs. Tax benefits vary by regime.',
    rbiHpiContext: 'RBI Housing Price Index (HPI) long-term property appreciation benchmark: ~4.5% - 6.5% p.a.',
  },

  presets: [
    {
      id: 'metro_tier1_apartment',
      title: '🏙️ Metro Tier-1 Apartment (₹75L Property vs ₹25k Rent)',
      description: 'Standard 20-year metro housing scenario with 5% property growth and 12% equity return.',
      values: {
        propertyPrice: 7500000,
        monthlyRent: 25000,
        downPaymentPct: 20.0,
        homeLoanRate: 8.5,
        tenureYears: 20,
        propertyAppreciationRate: 5.0,
        rentInflationRate: 7.0,
        investmentReturnRate: 12.0,
        includeTaxBenefits: false,
        currency: 'INR',
      },
    },
    {
      id: 'suburban_family_villa',
      title: '🏡 Suburban Family Villa (₹1.5 Cr Property vs ₹45k Rent)',
      description: 'Larger suburban home purchase with 20-year tenure and moderate rent escalation.',
      values: {
        propertyPrice: 15000000,
        monthlyRent: 45000,
        downPaymentPct: 20.0,
        homeLoanRate: 8.5,
        tenureYears: 20,
        propertyAppreciationRate: 5.5,
        rentInflationRate: 6.5,
        investmentReturnRate: 12.0,
        includeTaxBenefits: false,
        currency: 'INR',
      },
    },
    {
      id: 'starter_condo_10y',
      title: '🏢 Starter Condo (₹40L Property vs ₹15k Rent, 10 Yrs)',
      description: 'Shorter 10-year horizon starter home decision model.',
      values: {
        propertyPrice: 4000000,
        monthlyRent: 15000,
        downPaymentPct: 20.0,
        homeLoanRate: 8.5,
        tenureYears: 10,
        propertyAppreciationRate: 5.0,
        rentInflationRate: 7.0,
        investmentReturnRate: 12.0,
        includeTaxBenefits: false,
        currency: 'INR',
      },
    },
    {
      id: 'high_appreciation_market',
      title: '📈 High-Growth Real Estate Market (₹1 Cr Property @ 8% Appreciation)',
      description: 'High real estate appreciation scenario evaluating property wealth vs equity SIPs.',
      values: {
        propertyPrice: 10000000,
        monthlyRent: 30000,
        downPaymentPct: 20.0,
        homeLoanRate: 8.5,
        tenureYears: 20,
        propertyAppreciationRate: 8.0,
        rentInflationRate: 7.0,
        investmentReturnRate: 12.0,
        includeTaxBenefits: false,
        currency: 'INR',
      },
    },
  ],
};

export const rentVsBuyCalculatorConfig = {
  ...RENT_VS_BUY_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateRentVsBuyCalculator,
  primaryResult: {
    key: 'netAdvantage',
    label: 'Net Financial Advantage',
  },
  ratioBarItems: [
    { key: 'netWorthBuy', label: 'Net Worth (Buying)', colorClass: 'bg-emerald-500' },
    { key: 'netWorthRent', label: 'Net Worth (Renting & Investing)', colorClass: 'bg-blue-500' },
  ],
  summaryItems: [
    { key: 'winningOption', label: 'Recommended Choice' },
    { key: 'netAdvantage', label: 'Net Financial Advantage', isTotal: true },
    { key: 'breakevenYear', label: 'Breakeven Year' },
    { key: 'netWorthBuy', label: 'Final Net Worth (Buy Scenario)' },
    { key: 'netWorthRent', label: 'Final Net Worth (Rent & Invest Scenario)' },
    { key: 'totalOutflowBuy', label: 'Total Cash Outflow (Buy Scenario)' },
    { key: 'totalOutflowRent', label: 'Total Cash Outflow (Rent Scenario)' },
    { key: 'futurePropertyValue', label: 'Future Inflated Property Value' },
  ],
  inputs: [
    {
      id: 'propertyPrice',
      type: 'number',
      label: 'Property Purchase Price Today',
      min: 500000,
      max: 200000000,
      step: 100000,
      prefix: '₹',
      minLabel: '₹5 Lakhs',
      maxLabel: '₹20 Cr',
      default: 7500000,
    },
    {
      id: 'monthlyRent',
      type: 'number',
      label: 'Initial Monthly Rent Today',
      min: 2000,
      max: 1000000,
      step: 1000,
      prefix: '₹',
      minLabel: '₹2k',
      maxLabel: '₹10L',
      default: 25000,
    },
    {
      id: 'tenureYears',
      type: 'number',
      label: 'Comparison Time Horizon (Years)',
      min: 1,
      max: 40,
      step: 1,
      minLabel: '1 Yr',
      maxLabel: '40 Yrs',
      default: 20,
    },
    {
      id: 'downPaymentPct',
      type: 'number',
      label: 'Down Payment Percentage (%)',
      min: 0,
      max: 100,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '100%',
      default: 20.0,
    },
    {
      id: 'homeLoanRate',
      type: 'number',
      label: 'Home Loan Interest Rate (% p.a.)',
      min: 1.0,
      max: 25.0,
      step: 0.1,
      suffix: '%',
      minLabel: '1.0%',
      maxLabel: '25.0%',
      default: 8.5,
    },
    {
      id: 'propertyAppreciationRate',
      type: 'number',
      label: 'Property Appreciation Rate (% p.a.)',
      min: 0,
      max: 25.0,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '25.0%',
      default: 5.0,
    },
    {
      id: 'rentInflationRate',
      type: 'number',
      label: 'Annual Rent Inflation Rate (% p.a.)',
      min: 0,
      max: 25.0,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '25.0%',
      default: 7.0,
    },
    {
      id: 'investmentReturnRate',
      type: 'number',
      label: 'Equity SIP Investment Return (% p.a.)',
      min: 0,
      max: 30.0,
      step: 0.1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '30.0%',
      default: 12.0,
    },
  ],
};
