import { calculateRetirementCorpusCalculator } from '../retirement/retirement-corpus-calculator.js';

export const retirementCorpusCalculatorConfig = {
  title: 'Retirement Corpus Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateRetirementCorpusCalculator,
  primaryResult: {
    key: 'requiredCorpus',
    label: 'Total Required Retirement Nest Egg Corpus',
  },
  ratioBarItems: [
    { key: 'requiredCorpus', label: 'Total Nest Egg Needed', colorClass: 'bg-primary' },
    { key: 'requiredMonthlySip', label: 'Required Monthly SIP', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'yearsToRetirement', label: 'Years Remaining Until Retirement' },
    { key: 'yearsInRetirement', label: 'Expected Years in Retirement' },
    { key: 'futureMonthlyExpense', label: 'Inflation-Adjusted Monthly Expense at Retirement' },
    { key: 'futureAnnualExpense', label: 'Inflation-Adjusted Annual Expense at Retirement' },
    { key: 'realPostReturn', label: 'Real Post-Retirement Return (%)' },
    { key: 'requiredCorpus', label: 'Total Target Retirement Corpus Needed', isTotal: true },
    { key: 'requiredMonthlySip', label: 'Required Monthly SIP to Build Corpus', class: 'text-semantic-up' },
  ],
  inputs: [
    {
      id: 'currentAge',
      type: 'number',
      label: 'Current Age (Years)',
      min: 18,
      max: 75,
      step: 1,
      suffix: 'Yrs',
      minLabel: '18 Yrs',
      maxLabel: '75 Yrs',
      default: 30,
    },
    {
      id: 'retirementAge',
      type: 'number',
      label: 'Expected Retirement Age (Years)',
      min: 40,
      max: 80,
      step: 1,
      suffix: 'Yrs',
      minLabel: '40 Yrs',
      maxLabel: '80 Yrs',
      default: 60,
    },
    {
      id: 'lifeExpectancy',
      type: 'number',
      label: 'Expected Life Expectancy (Years)',
      min: 60,
      max: 100,
      step: 1,
      suffix: 'Yrs',
      minLabel: '60 Yrs',
      maxLabel: '100 Yrs',
      default: 85,
    },
    {
      id: 'monthlyExpenses',
      type: 'number',
      label: 'Current Monthly Living Expenses (₹)',
      min: 10000,
      max: 1000000,
      step: 5000,
      prefix: '₹',
      minLabel: '₹10K',
      maxLabel: '₹10L',
      default: 50000,
    },
    {
      id: 'inflationRate',
      type: 'number',
      label: 'Expected Inflation Rate (%)',
      min: 2,
      max: 15,
      step: 0.5,
      suffix: '%',
      minLabel: '2%',
      maxLabel: '15%',
      default: 6,
    },
    {
      id: 'preRetirementReturn',
      type: 'number',
      label: 'Pre-Retirement Annual Return (%)',
      min: 4,
      max: 20,
      step: 0.5,
      suffix: '%',
      minLabel: '4%',
      maxLabel: '20%',
      default: 12,
    },
    {
      id: 'postRetirementReturn',
      type: 'number',
      label: 'Post-Retirement Annual Return (%)',
      min: 3,
      max: 15,
      step: 0.5,
      suffix: '%',
      minLabel: '3%',
      maxLabel: '15%',
      default: 8,
    },
  ],
  hasAmortizationTable: false,
};