/**
 * Configuration, educational presets, metadata, and default parameters for Salary Calculator.
 */

import {
  PAY_FREQUENCIES,
  JURISDICTIONS,
} from '../salary/salary-calculator.js';

export const SALARY_CONFIG = {
  id: 'salary-calculator',
  name: 'Salary Calculator',
  slug: 'salary-calculator',
  category: 'salary',
  categoryName: 'Personal/Salary Calculators',
  metaTitle: 'Salary Calculator: Gross to Net Take-Home Pay & Compensation Engine',
  metaDescription: 'Calculate annual, monthly, bi-weekly, and hourly take-home pay, progressive income tax, payroll deductions, target gross-up salary, and job offer comparisons.',

  defaults: {
    salaryAmount: 90000,
    payFrequency: 'ANNUAL',
    hoursPerWeek: 40,
    weeksPerYear: 52,
    workingDaysPerYear: 260,
    bonusAnnual: 0,
    commissionAnnual: 0,
    otherTaxableAnnual: 0,
    preTaxDeductionsAnnual: 4000,
    postTaxDeductionsAnnual: 0,
    jurisdiction: 'US',
    indiaRegime: 'new',
    customTaxRate: 20,
    customSocialRate: 5,
    stateTaxRatePct: 4.5,
  },

  presets: [
    {
      id: 'us_tech_salary',
      label: 'US Tech Salary ($120k + $15k)',
      icon: '💻',
      desc: 'US $120,000 base salary + $15,000 bonus with $6,000 401(k) pre-tax contribution and state tax.',
      salaryAmount: 120000,
      payFrequency: 'ANNUAL',
      hoursPerWeek: 40,
      weeksPerYear: 52,
      bonusAnnual: 15000,
      commissionAnnual: 0,
      otherTaxableAnnual: 0,
      preTaxDeductionsAnnual: 6000,
      postTaxDeductionsAnnual: 0,
      jurisdiction: 'US',
      stateTaxRatePct: 4.5,
    },
    {
      id: 'india_senior_swe',
      label: 'India Senior SWE (₹24L + ₹3L)',
      icon: '🇮🇳',
      desc: 'India ₹24 Lakhs base salary + ₹3 Lakhs bonus under FY 2025-26 New Tax Regime with standard deduction.',
      salaryAmount: 2400000,
      payFrequency: 'ANNUAL',
      hoursPerWeek: 40,
      weeksPerYear: 52,
      bonusAnnual: 300000,
      commissionAnnual: 0,
      otherTaxableAnnual: 0,
      preTaxDeductionsAnnual: 0,
      postTaxDeductionsAnnual: 0,
      jurisdiction: 'IN',
      indiaRegime: 'new',
    },
    {
      id: 'uk_professional',
      label: 'UK Professional (£55k Base)',
      icon: '🇬🇧',
      desc: 'UK £55,000 salary with 5% (£2,750) pre-tax pension deduction, PAYE income tax, and National Insurance.',
      salaryAmount: 55000,
      payFrequency: 'ANNUAL',
      hoursPerWeek: 37.5,
      weeksPerYear: 52,
      bonusAnnual: 2500,
      commissionAnnual: 0,
      otherTaxableAnnual: 0,
      preTaxDeductionsAnnual: 2750,
      postTaxDeductionsAnnual: 0,
      jurisdiction: 'UK',
    },
    {
      id: 'hourly_contractor',
      label: 'Hourly Worker ($32/hr)',
      icon: '⏱️',
      desc: 'Hourly wage of $32.00/hr working 40 hours per week across 50 working weeks per year.',
      salaryAmount: 32,
      payFrequency: 'HOURLY',
      hoursPerWeek: 40,
      weeksPerYear: 50,
      bonusAnnual: 0,
      commissionAnnual: 0,
      otherTaxableAnnual: 0,
      preTaxDeductionsAnnual: 1500,
      postTaxDeductionsAnnual: 0,
      jurisdiction: 'US',
      stateTaxRatePct: 3.5,
    },
    {
      id: 'ca_executive',
      label: 'Canada Manager (C$140k)',
      icon: '🇨🇦',
      desc: 'Canada C$140,000 salary + C$15,000 bonus with CPP, EI, and federal/provincial progressive taxes.',
      salaryAmount: 140000,
      payFrequency: 'ANNUAL',
      hoursPerWeek: 40,
      weeksPerYear: 52,
      bonusAnnual: 15000,
      commissionAnnual: 0,
      otherTaxableAnnual: 0,
      preTaxDeductionsAnnual: 5000,
      postTaxDeductionsAnnual: 0,
      jurisdiction: 'CA',
      stateTaxRatePct: 8.0,
    },
    {
      id: 'au_consultant',
      label: 'Australia Consultant (A$110k)',
      icon: '🇦🇺',
      desc: 'Australia A$110,000 base salary under 2024-25/2025-26 Stage 3 tax cuts with 2% Medicare Levy.',
      salaryAmount: 110000,
      payFrequency: 'ANNUAL',
      hoursPerWeek: 38,
      weeksPerYear: 52,
      bonusAnnual: 5000,
      commissionAnnual: 0,
      otherTaxableAnnual: 0,
      preTaxDeductionsAnnual: 0,
      postTaxDeductionsAnnual: 0,
      jurisdiction: 'AU',
    },
  ],

  payFrequencies: PAY_FREQUENCIES,
  jurisdictions: JURISDICTIONS,
};
