/**
 * Staking Rewards Calculator Configuration & Educational Presets
 * Sprint 84 / Flagship #91
 * 
 * Note: Presets represent realistic protocol structural archetypes and baseline reference
 * parameters as of Q3 2026. They are not live data feeds.
 */

export const STAKING_REWARDS_CONFIG = {
  id: 'staking-rewards-calculator',
  title: 'Staking Rewards Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Quantitative Digital Asset & Proof-of-Stake Advisory Board',
  lastUpdated: '2026-08-27',

  defaults: {
    stakedAmount: 10,
    tokenPrice: 3000,
    rateMode: 'APR',
    rewardRatePct: 4.0,
    compoundingFrequency: 'DAILY',
    durationMonths: 12,
    validatorCommissionPct: 5.0,
    fixedFeeTokens: 0,
    recurringMonthlyFeeTokens: 0,
    unbondingDays: 0,
    currency: 'USD',
    assetName: 'Ethereum (ETH)',
  },

  presets: [
    {
      id: 'eth_validator_pool',
      label: 'Ethereum (ETH): Staking Pool',
      icon: 'Ξ',
      assetName: 'Ethereum (ETH)',
      stakedAmount: 32,
      tokenPrice: 3000,
      rateMode: 'APR',
      rewardRatePct: 3.8,
      compoundingFrequency: 'DAILY',
      durationMonths: 12,
      validatorCommissionPct: 5.0,
      fixedFeeTokens: 0.005,
      recurringMonthlyFeeTokens: 0,
      unbondingDays: 0,
      currency: 'USD',
      desc: '32 ETH · 3.8% APR · Daily Compounding · 5% Commission',
    },
    {
      id: 'sol_native_stake',
      label: 'Solana (SOL): Native Validator Delegation',
      icon: '◎',
      assetName: 'Solana (SOL)',
      stakedAmount: 250,
      tokenPrice: 150,
      rateMode: 'APY',
      rewardRatePct: 6.8,
      compoundingFrequency: 'DAILY',
      durationMonths: 12,
      validatorCommissionPct: 5.0,
      fixedFeeTokens: 0.01,
      recurringMonthlyFeeTokens: 0,
      unbondingDays: 3,
      currency: 'USD',
      desc: '250 SOL · 6.8% APY · Epoch Auto-Compound · 3-Day Unbonding',
    },
    {
      id: 'ada_pool_stake',
      label: 'Cardano (ADA): Non-Custodial Stake Pool',
      icon: '₳',
      assetName: 'Cardano (ADA)',
      stakedAmount: 15000,
      tokenPrice: 0.45,
      rateMode: 'APR',
      rewardRatePct: 3.2,
      compoundingFrequency: 'DAILY',
      durationMonths: 12,
      validatorCommissionPct: 2.0,
      fixedFeeTokens: 2.0,
      recurringMonthlyFeeTokens: 0,
      unbondingDays: 0,
      currency: 'USD',
      desc: '15,000 ADA · 3.2% APR · 5-Day Epochs · Zero Lockup',
    },
    {
      id: 'dot_npos_stake',
      label: 'Polkadot (DOT): Nominated PoS',
      icon: '●',
      assetName: 'Polkadot (DOT)',
      stakedAmount: 500,
      tokenPrice: 7.50,
      rateMode: 'APR',
      rewardRatePct: 11.5,
      compoundingFrequency: 'DAILY',
      durationMonths: 12,
      validatorCommissionPct: 3.0,
      fixedFeeTokens: 0.1,
      recurringMonthlyFeeTokens: 0,
      unbondingDays: 28,
      currency: 'USD',
      desc: '500 DOT · 11.5% APR · Daily Era Payout · 28-Day Unbonding',
    },
    {
      id: 'atom_cosmos_stake',
      label: 'Cosmos (ATOM): Hub Staking',
      icon: '⚛️',
      assetName: 'Cosmos (ATOM)',
      stakedAmount: 300,
      tokenPrice: 8.00,
      rateMode: 'APR',
      rewardRatePct: 14.0,
      compoundingFrequency: 'DAILY',
      durationMonths: 12,
      validatorCommissionPct: 5.0,
      fixedFeeTokens: 0.05,
      recurringMonthlyFeeTokens: 0,
      unbondingDays: 21,
      currency: 'USD',
      desc: '300 ATOM · 14.0% APR · Daily Compounding · 21-Day Unbonding',
    },
    {
      id: 'usdc_stable_yield',
      label: 'Stablecoin Yield Vault (USDC/USDT)',
      icon: '💵',
      assetName: 'USDC Vault',
      stakedAmount: 10000,
      tokenPrice: 1.00,
      rateMode: 'APY',
      rewardRatePct: 5.2,
      compoundingFrequency: 'DAILY',
      durationMonths: 12,
      validatorCommissionPct: 0,
      fixedFeeTokens: 0,
      recurringMonthlyFeeTokens: 0,
      unbondingDays: 0,
      currency: 'USD',
      desc: '10,000 USDC · 5.2% APY · Daily Compounding · Instant Liquidity',
    },
  ],
};
