import { calculateStampDutyCalculator } from '../real-estate/stamp-duty-calculator.js';

export const STAMP_DUTY_PRESETS = [
  {
    id: 'mumbai_1cr',
    name: 'Mumbai 2BHK Apartment (₹1 Crore)',
    description: '₹1 Crore Residential Flat in Mumbai (Maharashtra 5% + 1% Metro Cess + ₹30K Reg Cap)',
    badge: 'Mumbai 1 Cr',
    values: {
      propertyValue: 10000000,
      circleRateValue: 9000000,
      state: 'maharashtra',
      gender: 'male',
      location: 'urban',
      advocateLegalFees: 35000,
    },
  },
  {
    id: 'delhi_female',
    name: 'Delhi Floor (Female Buyer Rebate)',
    description: '₹75 Lakhs Builder Floor in Delhi with 4% Female Stamp Duty Concession',
    badge: 'Delhi Female',
    values: {
      propertyValue: 7500000,
      circleRateValue: 7000000,
      state: 'delhi',
      gender: 'female',
      location: 'urban',
      advocateLegalFees: 25000,
    },
  },
  {
    id: 'bangalore_tech',
    name: 'Bangalore Villa (₹1.5 Crores)',
    description: '₹1.5 Crores Gated Villa in Bangalore (Karnataka 5% + Cess + 1% Registration)',
    badge: 'Bangalore Villa',
    values: {
      propertyValue: 15000000,
      circleRateValue: 12000000,
      state: 'karnataka',
      gender: 'male',
      location: 'urban',
      advocateLegalFees: 50000,
    },
  },
  {
    id: 'chennai_apartment',
    name: 'Chennai Flat (7% + 2% Reg)',
    description: '₹60 Lakhs Apartment in Chennai (Tamil Nadu 7% Stamp Duty + 2% Registration)',
    badge: 'Chennai Flat',
    values: {
      propertyValue: 6000000,
      circleRateValue: 5500000,
      state: 'tamil_nadu',
      gender: 'male',
      location: 'urban',
      advocateLegalFees: 20000,
    },
  },
  {
    id: 'noida_joint',
    name: 'Noida High-Rise (Joint Ownership)',
    description: '₹90 Lakhs High-Rise in Noida (UP 6.5% Joint Stamp Duty + ₹20K Reg Cap)',
    badge: 'Noida Joint',
    values: {
      propertyValue: 9000000,
      circleRateValue: 8000000,
      state: 'uttar_pradesh',
      gender: 'joint',
      location: 'urban',
      advocateLegalFees: 30000,
    },
  },
  {
    id: 'hyderabad_plot',
    name: 'Hyderabad Commercial Plot (₹2 Cr)',
    description: '₹2 Crores Commercial Plot in Hyderabad (Telangana 5.5% + 1.5% Transfer Duty)',
    badge: 'Hyderabad 2 Cr',
    values: {
      propertyValue: 20000000,
      circleRateValue: 18000000,
      state: 'telangana',
      gender: 'male',
      location: 'urban',
      advocateLegalFees: 60000,
    },
  },
];

export const stampDutyCalculatorConfig = {
  title: 'Stamp Duty & Property Registration Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateStampDutyCalculator,
  presets: STAMP_DUTY_PRESETS,
  defaultPropertyValue: 5000000,
  defaultCircleRate: 0,
  defaultState: 'maharashtra',
  defaultGender: 'male',
  defaultLocation: 'urban',
  primaryResult: {
    key: 'totalGovernmentCharges',
    label: 'Total Govt. Stamp Duty & Registration',
  },
  ratioBarItems: [
    { key: 'propertyValue', label: 'Property Agreement Value', colorClass: 'bg-primary' },
    { key: 'totalStampDuty', label: 'Stamp Duty & Cesses', colorClass: 'bg-rose-500' },
    { key: 'registrationCharges', label: 'Registration Charges', colorClass: 'bg-amber-500' },
  ],
  summaryItems: [
    { key: 'propertyValue', label: 'Property Purchase Price' },
    { key: 'totalStampDuty', label: 'Total Stamp Duty Payable' },
    { key: 'registrationCharges', label: 'Registration Fee' },
    { key: 'legalFees', label: 'Legal & Documentation Outflow' },
    { key: 'totalPropertyCost', label: 'All-Inclusive Total Property Cost', isTotal: true },
  ],
  inputs: [
    {
      id: 'propertyValue',
      type: 'number',
      label: 'Property Agreement Value (₹)',
      min: 500000,
      max: 500000000,
      step: 100000,
      prefix: '₹',
      minLabel: '₹5 Lakhs',
      maxLabel: '₹50 Crores',
      default: 5000000,
    },
    {
      id: 'circleRateValue',
      type: 'number',
      label: 'Ready Reckoner / Circle Rate Value (₹)',
      min: 0,
      max: 500000000,
      step: 100000,
      prefix: '₹',
      default: 0,
    },
    {
      id: 'state',
      type: 'select',
      label: 'State / Location',
      default: 'maharashtra',
    },
    {
      id: 'gender',
      type: 'select',
      label: 'Buyer Ownership Gender',
      default: 'male',
    },
    {
      id: 'location',
      type: 'select',
      label: 'Area Classification',
      default: 'urban',
    },
    {
      id: 'advocateLegalFees',
      type: 'number',
      label: 'Legal & Advocate Charges (₹)',
      min: 0,
      max: 500000,
      step: 5000,
      prefix: '₹',
      default: 25000,
    },
  ],
  hasAmortizationTable: false,
};
