import { calculateStartupValuationCalculator } from '../business/startup-valuation-calculator.js';

export const STARTUP_VALUATION_PRESETS = [
  {
    id: 'seed_prototype',
    name: 'Seed Stage Prototype',
    description: '₹2.0 Cr Base, ₹50L Ask, ₹1.2 Cr ARR (8x Multiple) → ₹2.16 Cr Pre-Money',
    badge: 'Seed Stage',
    values: {
      primaryMethod: 'scorecard',
      basePreMoneyValuation: 20000000,
      investmentAsk: 5000000,
      annualRevenue: 12000000,
      arrMultiple: 8,
      teamScore: 110,
      marketSizeScore: 115,
      productScore: 105,
      competitionScore: 100,
      partnershipsScore: 100,
      capitalNeedScore: 100,
      regulatoryScore: 100,
      currencySymbol: '₹',
    },
  },
  {
    id: 'pre_seed_idea',
    name: 'Pre-Seed Idea Stage',
    description: 'Pre-Revenue Berkus Method (Sound Idea, Prototype, Team) → ₹1.50 Cr Valuation',
    badge: 'Pre-Seed',
    values: {
      primaryMethod: 'berkus',
      basePreMoneyValuation: 10000000,
      investmentAsk: 2500000,
      annualRevenue: 0,
      arrMultiple: 5,
      berkusSoundIdea: 4000000,
      berkusPrototype: 4000000,
      berkusQualityTeam: 4000000,
      berkusStrategicAlliances: 2000000,
      berkusProductRollout: 1000000,
      currencySymbol: '₹',
    },
  },
  {
    id: 'early_saas',
    name: 'Early Revenue SaaS',
    description: '₹3.6 Cr ARR at 10x Multiple → ₹3.60 Cr ARR Valuation',
    badge: 'SaaS Scaleup',
    values: {
      primaryMethod: 'arr_multiple',
      basePreMoneyValuation: 30000000,
      investmentAsk: 7500000,
      annualRevenue: 36000000,
      arrMultiple: 10,
      teamScore: 120,
      marketSizeScore: 125,
      productScore: 110,
      competitionScore: 105,
      partnershipsScore: 110,
      capitalNeedScore: 100,
      regulatoryScore: 100,
      currencySymbol: '₹',
    },
  },
  {
    id: 'series_a_growth',
    name: 'Series A VC Exit Model',
    description: '₹100 Cr Year-5 Exit at 6x Multiple (10x ROI Hurdle) → ₹40.0 Cr Pre-Money',
    badge: 'Series A VC',
    values: {
      primaryMethod: 'vc_method',
      basePreMoneyValuation: 400000000,
      investmentAsk: 100000000,
      annualRevenue: 60000000,
      arrMultiple: 8,
      exitYearRevenue: 1000000000,
      exitMultiple: 6,
      targetRoiMultiple: 10,
      futureDilutionPct: 25,
      currencySymbol: '₹',
    },
  },
  {
    id: 'deeptech_ip',
    name: 'DeepTech / IP Heavy',
    description: 'High Product (150%) & Management (130%) Scorecard Multipliers',
    badge: 'DeepTech',
    values: {
      primaryMethod: 'scorecard',
      basePreMoneyValuation: 50000000,
      investmentAsk: 15000000,
      annualRevenue: 5000000,
      arrMultiple: 12,
      teamScore: 130,
      marketSizeScore: 120,
      productScore: 150,
      competitionScore: 120,
      partnershipsScore: 100,
      capitalNeedScore: 90,
      regulatoryScore: 110,
      currencySymbol: '₹',
    },
  },
  {
    id: 'consumer_viral',
    name: 'Consumer App Scale',
    description: 'Blended Synthesis across Scorecard, Berkus, and VC Exit Models',
    badge: 'Consumer Tech',
    values: {
      primaryMethod: 'blended',
      basePreMoneyValuation: 25000000,
      investmentAsk: 5000000,
      annualRevenue: 10000000,
      arrMultiple: 8,
      teamScore: 115,
      marketSizeScore: 140,
      productScore: 110,
      competitionScore: 90,
      partnershipsScore: 100,
      capitalNeedScore: 100,
      regulatoryScore: 100,
      currencySymbol: '₹',
    },
  },
];

export const startupValuationCalculatorConfig = {
  title: 'Startup Valuation Calculator: Scorecard, Berkus & VC Methods',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateStartupValuationCalculator,
  presets: STARTUP_VALUATION_PRESETS,
  defaultBasePreMoneyValuation: 20000000,
  defaultInvestmentAsk: 5000000,
  defaultAnnualRevenue: 12000000,
  defaultArrMultiple: 8,
  primaryResult: {
    key: 'selectedPreMoney',
    label: 'Estimated Pre-Money Valuation',
  },
  ratioBarItems: [
    { key: 'scorecardValuation', label: 'Scorecard Method', colorClass: 'bg-primary' },
    { key: 'berkusValuation', label: 'Berkus Method', colorClass: 'bg-emerald-500' },
    { key: 'vcPreMoneyValuation', label: 'VC Exit Method', colorClass: 'bg-indigo-500' },
    { key: 'arrMultipleValuation', label: 'ARR Multiple', colorClass: 'bg-amber-500' },
  ],
  summaryItems: [
    { key: 'selectedPreMoney', label: 'Estimated Pre-Money Valuation', isTotal: true },
    { key: 'postMoneyValuation', label: 'Post-Money Valuation' },
    { key: 'investorEquityPct', label: 'Investor Equity Dilution (%)' },
    { key: 'blendedValuation', label: 'Blended Synthesis Valuation' },
    { key: 'valuationMin', label: 'Valuation Range (Low - High)' },
  ],
  inputs: [
    {
      id: 'basePreMoneyValuation',
      type: 'number',
      label: 'Regional / Sector Base Valuation',
      min: 10000,
      max: 10000000000,
      step: 500000,
      prefix: '₹',
      default: 20000000,
    },
    {
      id: 'investmentAsk',
      type: 'number',
      label: 'Target Investment Capital Raised',
      min: 0,
      max: 5000000000,
      step: 250000,
      prefix: '₹',
      default: 5000000,
    },
    {
      id: 'annualRevenue',
      type: 'number',
      label: 'Current Annual Revenue / ARR',
      min: 0,
      max: 5000000000,
      step: 250000,
      prefix: '₹',
      default: 12000000,
    },
    {
      id: 'arrMultiple',
      type: 'number',
      label: 'Sector Revenue Multiple',
      min: 1,
      max: 50,
      step: 0.5,
      suffix: 'x ARR',
      default: 8,
    },
  ],
};
