import { calculateSwp } from '../investment/swp-calculator.js';

export const swpCalculatorConfig = {
  title: 'SWP Parameters & Withdrawal Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateSwp,
  primaryResult: {
    key: 'totalWithdrawn',
    label: 'Total Cumulative Payout Withdrawn',
  },
  ratioBarItems: [
    { key: 'totalWithdrawn', label: 'Total Withdrawn', colorClass: 'bg-semantic-up' },
    { key: 'finalBalance', label: 'Remaining Balance', colorClass: 'bg-primary' },
  ],
  summaryItems: [
    { key: 'totalInvestment', label: 'Initial Invested Capital' },
    { key: 'totalWithdrawn', label: 'Total Capital Withdrawn', class: 'text-semantic-up' },
    { key: 'finalBalance', label: 'Remaining Final Corpus Balance', isTotal: true },
  ],
  inputs: [
    {
      id: 'totalInvestment',
      type: 'number',
      label: 'Initial Investment Corpus',
      min: 100000,
      max: 50000000,
      step: 100000,
      prefix: '₹',
      minLabel: '₹1L',
      maxLabel: '₹5 Cr',
      default: 5000000,
    },
    {
      id: 'monthlyWithdrawal',
      type: 'number',
      label: 'Monthly Withdrawal Payout',
      min: 1000,
      max: 500000,
      step: 1000,
      prefix: '₹',
      minLabel: '₹1K',
      maxLabel: '₹5L',
      default: 30000,
    },
    {
      id: 'expectedReturnRate',
      type: 'number',
      label: 'Expected Return Rate (p.a.)',
      min: 1,
      max: 25,
      step: 0.5,
      suffix: '%',
      minLabel: '1%',
      maxLabel: '25%',
      default: 8,
    },
    {
      id: 'tenureYears',
      type: 'number',
      label: 'Withdrawal Duration (Years)',
      min: 1,
      max: 40,
      step: 1,
      suffix: 'Yrs',
      minLabel: '1 Yr',
      maxLabel: '40 Yrs',
      default: 10,
    },
  ],
  hasYearlySchedule: true,
};