import { calculateTakeHomeSalaryCalculator } from '../tax/take-home-salary-calculator.js';

export const takeHomeSalaryCalculatorConfig = {
  title: 'Take-Home Salary Details',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateTakeHomeSalaryCalculator,
  primaryResult: {
    key: 'netMonthlyTakeHome',
    label: 'Net Monthly Take-Home Pay (In-Hand Salary)',
  },
  ratioBarItems: [
    { key: 'netAnnualTakeHome', label: 'Net In-Hand Salary', colorClass: 'bg-semantic-up' },
    { key: 'totalIncomeTax', label: 'Income Tax', colorClass: 'bg-accent-amber' },
    { key: 'epfAnnual', label: 'EPF Savings', colorClass: 'bg-primary' },
  ],
  summaryItems: [
    { key: 'grossAnnualCtc', label: 'Gross Annual CTC' },
    { key: 'standardDeduction', label: 'Standard Deduction (FY 2025-26)' },
    { key: 'taxableIncome', label: 'Net Taxable Income' },
    { key: 'totalIncomeTax', label: 'Annual Income Tax Payable (incl. Cess)' },
    { key: 'epfAnnual', label: 'Employee Provident Fund (EPF - 12%)' },
    { key: 'netAnnualTakeHome', label: 'Net Annual In-Hand Salary' },
    { key: 'netMonthlyTakeHome', label: 'Net Monthly In-Hand Pay', isTotal: true },
  ],
  inputs: [
    {
      id: 'ctc',
      type: 'number',
      label: 'Gross Annual CTC (₹)',
      min: 200000,
      max: 20000000,
      step: 25000,
      prefix: '₹',
      minLabel: '₹2L',
      maxLabel: '₹2 Cr',
      default: 1200000,
    },
    {
      id: 'basicPercent',
      type: 'number',
      label: 'Basic Salary Percentage of CTC (%)',
      min: 30,
      max: 70,
      step: 5,
      suffix: '%',
      minLabel: '30%',
      maxLabel: '70%',
      default: 50,
    },
    {
      id: 'professionalTax',
      type: 'number',
      label: 'Annual Professional Tax (₹)',
      min: 0,
      max: 5000,
      step: 100,
      prefix: '₹',
      minLabel: '₹0',
      maxLabel: '₹5K',
      default: 2400,
    },
  ],
  hasAmortizationTable: false,
};