import { calculateTermLifeInsuranceCalculator } from '../insurance/term-life-insurance-calculator.js';

export const TERM_INSURANCE_PRESETS = [
  {
    id: 'young_professional',
    name: 'Young Professional (Age 25)',
    description: '25 Yrs, ₹8L Income, ₹1 Cr Cover for 35 Years, Non-Smoker',
    badge: 'Age 25',
    values: {
      currentAge: 25,
      gender: 'male',
      isSmoker: false,
      annualIncome: 800000,
      existingLiabilities: 500000,
      annualFamilyExpenses: 350000,
      expenseReplacementYears: 20,
      futureGoals: 1000000,
      existingAssets: 300000,
      coverageYears: 35,
      sizingMethod: 'dime',
      criticalIllnessRider: false,
      accidentalRider: false,
      waiverOfPremiumRider: false,
      currencySymbol: '₹',
    },
  },
  {
    id: 'married_parent',
    name: 'Married Parent (Age 32)',
    description: '32 Yrs, ₹18L Income, ₹2 Cr Cover, Home Loan + Child Higher Education',
    badge: 'Family Protection',
    values: {
      currentAge: 32,
      gender: 'male',
      isSmoker: false,
      annualIncome: 1800000,
      existingLiabilities: 4500000,
      annualFamilyExpenses: 800000,
      expenseReplacementYears: 18,
      futureGoals: 3500000,
      existingAssets: 1500000,
      coverageYears: 30,
      sizingMethod: 'dime',
      criticalIllnessRider: true,
      accidentalRider: true,
      waiverOfPremiumRider: true,
      currencySymbol: '₹',
    },
  },
  {
    id: 'mid_career',
    name: 'Mid-Career Executive (Age 42)',
    description: '42 Yrs, ₹30L Income, ₹2.5 Cr Cover, Moderate Liabilities',
    badge: 'Age 42',
    values: {
      currentAge: 42,
      gender: 'male',
      isSmoker: false,
      annualIncome: 3000000,
      existingLiabilities: 3000000,
      annualFamilyExpenses: 1200000,
      expenseReplacementYears: 15,
      futureGoals: 4000000,
      existingAssets: 4000000,
      coverageYears: 25,
      sizingMethod: 'dime',
      criticalIllnessRider: true,
      accidentalRider: false,
      waiverOfPremiumRider: true,
      currencySymbol: '₹',
    },
  },
  {
    id: 'female_professional',
    name: 'Working Woman (Age 28)',
    description: '28 Yrs Female, ₹12L Income, ₹1.5 Cr Cover with 10% Longevity Discount',
    badge: 'Female Discount',
    values: {
      currentAge: 28,
      gender: 'female',
      isSmoker: false,
      annualIncome: 1200000,
      existingLiabilities: 1000000,
      annualFamilyExpenses: 500000,
      expenseReplacementYears: 20,
      futureGoals: 2000000,
      existingAssets: 800000,
      coverageYears: 35,
      sizingMethod: 'dime',
      criticalIllnessRider: true,
      accidentalRider: false,
      waiverOfPremiumRider: false,
      currencySymbol: '₹',
    },
  },
  {
    id: 'smoker_protection',
    name: 'Smoker Underwriting (Age 30)',
    description: '30 Yrs Smoker, ₹15L Income, ₹1.5 Cr Cover with Tobacco Surcharge',
    badge: 'Smoker Model',
    values: {
      currentAge: 30,
      gender: 'male',
      isSmoker: true,
      annualIncome: 1500000,
      existingLiabilities: 2500000,
      annualFamilyExpenses: 600000,
      expenseReplacementYears: 15,
      futureGoals: 2000000,
      existingAssets: 1000000,
      coverageYears: 30,
      sizingMethod: 'dime',
      criticalIllnessRider: false,
      accidentalRider: true,
      waiverOfPremiumRider: false,
      currencySymbol: '₹',
    },
  },
  {
    id: 'high_net_worth',
    name: 'High Net Worth HLV (Age 35)',
    description: '35 Yrs, ₹50L Income, ₹5 Cr Human Life Value (HLV) Cover',
    badge: 'HLV Method',
    values: {
      currentAge: 35,
      gender: 'male',
      isSmoker: false,
      annualIncome: 5000000,
      existingLiabilities: 10000000,
      annualFamilyExpenses: 2000000,
      expenseReplacementYears: 20,
      futureGoals: 10000000,
      existingAssets: 15000000,
      coverageYears: 30,
      sizingMethod: 'hlv',
      criticalIllnessRider: true,
      accidentalRider: true,
      waiverOfPremiumRider: true,
      currencySymbol: '₹',
    },
  },
];

export const termLifeInsuranceCalculatorConfig = {
  title: 'Term Life Insurance & Human Life Value (HLV) Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateTermLifeInsuranceCalculator,
  presets: TERM_INSURANCE_PRESETS,
  defaultCurrentAge: 30,
  defaultAnnualIncome: 1200000,
  defaultExistingLiabilities: 3000000,
  defaultAnnualFamilyExpenses: 600000,
  defaultExpenseReplacementYears: 15,
  defaultFutureGoals: 2000000,
  defaultExistingAssets: 1000000,
  defaultCoverageYears: 35,
  primaryResult: {
    key: 'recommendedSumAssured',
    label: 'Recommended Term Life Insurance Cover',
  },
  ratioBarItems: [
    { key: 'baseAnnualPremium', label: 'Base Pure Term Premium', colorClass: 'bg-primary' },
    { key: 'gstAmount', label: 'GST (18%) & Riders', colorClass: 'bg-amber-500' },
  ],
  summaryItems: [
    { key: 'recommendedSumAssured', label: 'Recommended Sum Assured (Life Cover)', isTotal: true },
    { key: 'grossAnnualPremium', label: 'Estimated Annual Premium (incl. GST)' },
    { key: 'monthlyEquivalentPremium', label: 'Monthly Equivalent Outflow' },
    { key: 'totalLifetimePremiumsPaid', label: 'Total Lifetime Premiums Paid' },
    { key: 'sipWealthAdvantage', label: 'Pure Term + SIP Advantage vs TROP' },
  ],
  inputs: [
    {
      id: 'currentAge',
      type: 'number',
      label: 'Your Current Age',
      min: 18,
      max: 65,
      step: 1,
      suffix: 'Yrs',
      default: 30,
    },
    {
      id: 'annualIncome',
      type: 'number',
      label: 'Annual Gross Income',
      min: 100000,
      max: 100000000,
      step: 50000,
      prefix: '₹',
      default: 1200000,
    },
    {
      id: 'existingLiabilities',
      type: 'number',
      label: 'Outstanding Loans & Debts (Mortgage, Car, Personal)',
      min: 0,
      max: 100000000,
      step: 100000,
      prefix: '₹',
      default: 3000000,
    },
    {
      id: 'annualFamilyExpenses',
      type: 'number',
      label: 'Annual Living Expenses (Excluding Self)',
      min: 50000,
      max: 50000000,
      step: 50000,
      prefix: '₹',
      default: 600000,
    },
    {
      id: 'expenseReplacementYears',
      type: 'number',
      label: 'Income Replacement Duration',
      min: 5,
      max: 40,
      step: 1,
      suffix: 'Yrs',
      default: 15,
    },
    {
      id: 'futureGoals',
      type: 'number',
      label: 'Future Education & Marriage Provisions',
      min: 0,
      max: 100000000,
      step: 100000,
      prefix: '₹',
      default: 2000000,
    },
    {
      id: 'existingAssets',
      type: 'number',
      label: 'Existing Liquid Investments & Current Life Cover',
      min: 0,
      max: 100000000,
      step: 100000,
      prefix: '₹',
      default: 1000000,
    },
    {
      id: 'coverageYears',
      type: 'number',
      label: 'Coverage Term Duration',
      min: 5,
      max: 50,
      step: 1,
      suffix: 'Yrs',
      default: 35,
    },
  ],
};
