/**
 * Token Vesting Calculator Configuration & Educational Presets
 * Sprint 90 / Flagship #97
 * 
 * Note: Presets represent educational hypothetical token vesting schedules.
 * They do not constitute actual project allocations, live token prices, or legal investment advice.
 */

export const TOKEN_VESTING_CONFIG = {
  id: 'token-vesting-calculator',
  title: 'Token Vesting Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find Blockchain Economics Research Board',
  lastUpdated: '2026-08-28',

  defaults: {
    totalTokens: 100000,
    tokenPrice: 1.5,
    grantPrice: 0.25,
    startDate: '2024-01-01',
    evaluationDate: '2025-01-01',
    vestingModel: 'CLIFF_LINEAR',
    cliffMonths: 12,
    vestingMonths: 48,
    vestingFrequency: 'MONTHLY',
    initialUnlockPct: 0,
    totalSupply: 10000000,
    currency: 'USD',
    tokenSymbol: 'TOKEN',
  },

  presets: [
    {
      id: 'employee_equity_grant',
      label: 'Employee Grant (4yr / 1yr Cliff)',
      icon: '💼',
      vestingModel: 'CLIFF_LINEAR',
      totalTokens: 100000,
      tokenPrice: 1.5,
      grantPrice: 0.25,
      startDate: '2024-01-01',
      evaluationDate: '2025-01-01',
      cliffMonths: 12,
      vestingMonths: 48,
      vestingFrequency: 'MONTHLY',
      initialUnlockPct: 0,
      totalSupply: 10000000,
      tokenSymbol: 'TEAM',
      currency: 'USD',
      desc: 'Standard Silicon Valley / Web3 4-Year Schedule with 1-Year Cliff',
    },
    {
      id: 'token_launch_tge',
      label: 'TGE Launch (10% Initial + 2yr)',
      icon: '🚀',
      vestingModel: 'INITIAL_UNLOCK_CLIFF_LINEAR',
      totalTokens: 250000,
      tokenPrice: 2.0,
      grantPrice: 0.50,
      startDate: '2024-01-01',
      evaluationDate: '2024-07-01',
      cliffMonths: 6,
      vestingMonths: 24,
      vestingFrequency: 'MONTHLY',
      initialUnlockPct: 10,
      totalSupply: 25000000,
      tokenSymbol: 'PROTO',
      currency: 'USD',
      desc: '10% Unlocked at Token Generation Event · 6m Cliff · 24m Linear',
    },
    {
      id: 'investor_seed_round',
      label: 'Seed Investor (1yr Cliff / 2yr Linear)',
      icon: '🏛️',
      vestingModel: 'CLIFF_LINEAR',
      totalTokens: 500000,
      tokenPrice: 2.5,
      grantPrice: 0.20,
      startDate: '2024-01-01',
      evaluationDate: '2025-06-01',
      cliffMonths: 12,
      vestingMonths: 36,
      vestingFrequency: 'MONTHLY',
      initialUnlockPct: 0,
      totalSupply: 50000000,
      tokenSymbol: 'SEED',
      currency: 'USD',
      desc: 'Early Stage SAFT / Token Warrant Structure with 12m Lockup',
    },
    {
      id: 'advisor_continuous_linear',
      label: 'Advisor Grant (No Cliff / 2yr)',
      icon: '🤝',
      vestingModel: 'LINEAR_NO_CLIFF',
      totalTokens: 50000,
      tokenPrice: 1.25,
      grantPrice: 0.30,
      startDate: '2024-01-01',
      evaluationDate: '2024-09-01',
      cliffMonths: 0,
      vestingMonths: 24,
      vestingFrequency: 'MONTHLY',
      initialUnlockPct: 0,
      totalSupply: 10000000,
      tokenSymbol: 'ADVISOR',
      currency: 'USD',
      desc: 'Immediate Linear Vesting across 24 Months without Cliff',
    },
    {
      id: 'quarterly_tranche_grant',
      label: 'Quarterly Tranche Vesting',
      icon: '📊',
      vestingModel: 'PERIODIC_TRANCHE',
      totalTokens: 200000,
      tokenPrice: 3.0,
      grantPrice: 0.75,
      startDate: '2024-01-01',
      evaluationDate: '2025-04-01',
      cliffMonths: 12,
      vestingMonths: 36,
      vestingFrequency: 'QUARTERLY',
      initialUnlockPct: 0,
      totalSupply: 20000000,
      tokenSymbol: 'EXEC',
      currency: 'USD',
      desc: 'Discrete Quarterly Block Unlocks following 1-Year Cliff',
    },
    {
      id: 'high_volatility_scenario',
      label: 'High Price Volatility (10x Gain)',
      icon: '📈',
      vestingModel: 'CLIFF_LINEAR',
      totalTokens: 1000000,
      tokenPrice: 5.0,
      grantPrice: 0.10,
      startDate: '2024-01-01',
      evaluationDate: '2025-01-01',
      cliffMonths: 12,
      vestingMonths: 48,
      vestingFrequency: 'MONTHLY',
      initialUnlockPct: 0,
      totalSupply: 100000000,
      tokenSymbol: 'ALPHA',
      currency: 'USD',
      desc: 'Simulating $0.10 Grant to $5.00 Spot Price Expansion Dynamics',
    },
  ],
};
