import { calculateVpfCalculator } from '../retirement/vpf-calculator.js';

export const VPF_CONFIG = {
  id: 'vpf-calculator',
  title: 'Voluntary Provident Fund (VPF) Calculator',
  category: 'Retirement Calculators',
  categorySlug: 'retirement',
  defaultMonthlyBasic: 50000,
  defaultEpfPercent: 12,
  defaultVpfPercent: 10,
  defaultCurrentAge: 30,
  defaultRetirementAge: 58,
  defaultRate: 8.25,
  defaultSalaryGrowth: 5.0,
  defaultMarginalTaxRate: 30,

  benchmarks: {
    epfoNotifiedRate: 8.25, // EPFO-notified interest rate for FY 2023-24 / FY 2024-25
    effectiveFinancialYear: 'FY 2024-25 EPFO Notified Rate',
    sec10_11TaxCap: 250000, // ₹2.5 Lakhs employee contribution tax-free ceiling under Sec 10(11)
    sec80cMaxCap: 150000,
    mandatoryEpfPercent: 12,
    maxCombinedContributionPercent: 100,
    ppfBenchmarkRate: 7.1,
    npsBenchmarkRate: 10.0,
    sourceNotice: 'EPFO Ministry of Labour & Employment & Income Tax Act Section 10(11) (CBDT Notifications)',
  },

  presets: [
    {
      id: 'optimal_tax_free_10pct',
      title: '👑 Optimal 10% VPF Contribution (@ 8.25% p.a.)',
      description: 'Balanced VPF contribution yielding high tax-free compounding below the ₹2.5L annual Section 10(11) tax threshold.',
      values: {
        monthlyBasicSalary: 50000,
        epfPercent: 12,
        vpfPercent: 10,
        currentAge: 30,
        retirementAge: 58,
        rate: 8.25,
        salaryGrowth: 5.0,
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
    {
      id: 'aggressive_vpf_30pct',
      title: '🚀 Aggressive 30% VPF Allocation (@ 8.25% p.a.)',
      description: 'High-saving allocation building a massive retirement nest egg with EPFO notified returns.',
      values: {
        monthlyBasicSalary: 60000,
        epfPercent: 12,
        vpfPercent: 30,
        currentAge: 32,
        retirementAge: 58,
        rate: 8.25,
        salaryGrowth: 5.0,
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
    {
      id: 'fitted_250k_cap',
      title: '🛡️ Max Sec 10(11) Tax-Free Cap Fitting',
      description: 'Fitted employee EPF+VPF contribution to stay exactly within the ₹2.5L/yr 100% tax-free interest threshold.',
      values: {
        monthlyBasicSalary: 90000,
        epfPercent: 12,
        vpfPercent: 11,
        currentAge: 35,
        retirementAge: 58,
        rate: 8.25,
        salaryGrowth: 5.0,
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
    {
      id: 'hni_executive_200k',
      title: '💼 HNI Executive Allocation (₹2L Basic Salary)',
      description: 'Senior executive allocation auditing Section 10(11) taxable interest on excess contributions above ₹2.5L/yr.',
      values: {
        monthlyBasicSalary: 200000,
        epfPercent: 12,
        vpfPercent: 15,
        currentAge: 40,
        retirementAge: 58,
        rate: 8.25,
        salaryGrowth: 5.0,
        marginalTaxRate: 30,
        currency: 'INR',
      },
    },
  ],
};

export const vpfCalculatorConfig = {
  ...VPF_CONFIG,
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateVpfCalculator,
  primaryResult: {
    key: 'maturityCorpus',
    label: 'Total VPF Retirement Corpus',
  },
  ratioBarItems: [
    { key: 'totalEmployeeContribution', label: 'Total Employee VPF+EPF Contribution', colorClass: 'bg-primary' },
    { key: 'totalInterestEarned', label: 'Total EPFO Notified Interest Earned', colorClass: 'bg-semantic-up' },
  ],
  summaryItems: [
    { key: 'monthlyVpfContribution', label: 'Monthly VPF Contribution' },
    { key: 'monthlyEpfContribution', label: 'Monthly Mandatory EPF Contribution' },
    { key: 'totalEmployeeContribution', label: 'Total Cumulative Employee Contribution' },
    { key: 'totalInterestEarned', label: 'Total EPFO Notified Interest Earned', class: 'text-semantic-up' },
    { key: 'taxFreeInterest', label: 'Sec 10(11) Tax-Free Interest Component', class: 'text-semantic-success font-bold' },
    { key: 'taxableInterest', label: 'Sec 10(11) Taxable Interest (Above ₹2.5L Cap)', class: 'text-amber-600 font-bold' },
    { key: 'maturityCorpus', label: 'Total Retirement Corpus at Age 58', isTotal: true },
  ],
  inputs: [
    {
      id: 'monthlyBasicSalary',
      type: 'number',
      label: 'Monthly Basic Salary + DA (₹)',
      min: 10000,
      max: 2000000,
      step: 1000,
      prefix: '₹',
      minLabel: '₹10,000',
      maxLabel: '₹20 Lakhs',
      default: 50000,
    },
    {
      id: 'vpfPercent',
      type: 'number',
      label: 'Voluntary VPF Contribution (% of Basic)',
      min: 0,
      max: 88,
      step: 1,
      suffix: '%',
      minLabel: '0%',
      maxLabel: '88% (Max 100% with EPF)',
      default: 10,
    },
    {
      id: 'rate',
      type: 'number',
      label: 'EPFO Notified Interest Rate (% p.a.)',
      min: 1,
      max: 15,
      step: 0.05,
      suffix: '%',
      minLabel: '1.0%',
      maxLabel: '15.0%',
      default: 8.25,
    },
  ],
  hasAmortizationTable: true,
};
