import { calculateWorkingCapitalCalculator } from '../business/working-capital-calculator.js';

export const WORKING_CAPITAL_PRESETS = [
  {
    id: 'ecommerce',
    name: 'E-Commerce Direct-to-Consumer (D2C)',
    description: 'Fast-inventory online retail with digital payments and 30-day supplier credit',
    badge: 'D2C Retail',
    values: {
      cash: 800000,
      accountsReceivable: 200000,
      inventory: 1500000,
      otherCurrentAssets: 100000,
      accountsPayable: 1200000,
      shortTermDebt: 300000,
      accruedExpenses: 150000,
      annualRevenue: 20000000,
      annualCogs: 12000000,
      costOfCapital: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'manufacturing',
    name: 'Industrial Manufacturing Plant',
    description: 'Heavy raw material inventory, 45-day dealer receivables, and bank credit lines',
    badge: 'Manufacturing',
    values: {
      cash: 1500000,
      accountsReceivable: 6000000,
      inventory: 4500000,
      otherCurrentAssets: 500000,
      accountsPayable: 4000000,
      shortTermDebt: 3000000,
      accruedExpenses: 800000,
      annualRevenue: 50000000,
      annualCogs: 32000000,
      costOfCapital: 11,
      currencySymbol: '₹',
    },
  },
  {
    id: 'saas',
    name: 'B2B SaaS / IT Services Agency',
    description: 'Zero physical inventory, high cash reserves, and 30-day corporate client receivables',
    badge: 'SaaS / Tech',
    values: {
      cash: 3000000,
      accountsReceivable: 2500000,
      inventory: 0,
      otherCurrentAssets: 200000,
      accountsPayable: 600000,
      shortTermDebt: 0,
      accruedExpenses: 1200000,
      annualRevenue: 30000000,
      annualCogs: 10000000,
      costOfCapital: 10,
      currencySymbol: '₹',
    },
  },
  {
    id: 'wholesale',
    name: 'Wholesale FMCG Distributor',
    description: 'High volume, rapid inventory turnover, and 21-day retail grocery receivables',
    badge: 'Wholesale',
    values: {
      cash: 1000000,
      accountsReceivable: 4500000,
      inventory: 3500000,
      otherCurrentAssets: 250000,
      accountsPayable: 5000000,
      shortTermDebt: 1500000,
      accruedExpenses: 400000,
      annualRevenue: 60000000,
      annualCogs: 50000000,
      costOfCapital: 12,
      currencySymbol: '₹',
    },
  },
  {
    id: 'construction',
    name: 'Commercial Construction Contractor',
    description: 'Long billing milestones, retention money receivables, and heavy sub-contractor payables',
    badge: 'Contracting',
    values: {
      cash: 2000000,
      accountsReceivable: 12000000,
      inventory: 2000000,
      otherCurrentAssets: 1000000,
      accountsPayable: 9000000,
      shortTermDebt: 4000000,
      accruedExpenses: 1500000,
      annualRevenue: 80000000,
      annualCogs: 60000000,
      costOfCapital: 13,
      currencySymbol: '₹',
    },
  },
  {
    id: 'distressed',
    name: 'Stressed Working Capital Deficit',
    description: 'Working capital crunch scenario with current liabilities exceeding liquid current assets',
    badge: 'Stressed Model',
    values: {
      cash: 200000,
      accountsReceivable: 800000,
      inventory: 500000,
      otherCurrentAssets: 50000,
      accountsPayable: 1800000,
      shortTermDebt: 1200000,
      accruedExpenses: 600000,
      annualRevenue: 12000000,
      annualCogs: 9000000,
      costOfCapital: 14,
      currencySymbol: '₹',
    },
  },
];

export const workingCapitalCalculatorConfig = {
  title: 'Working Capital & Liquidity Ratios Calculator',
  currency: 'INR',
  currencySymbol: '₹',
  calculateFn: calculateWorkingCapitalCalculator,
  presets: WORKING_CAPITAL_PRESETS,
  defaultCash: 500000,
  defaultAccountsReceivable: 1200000,
  defaultInventory: 800000,
  defaultOtherCurrentAssets: 100000,
  defaultAccountsPayable: 900000,
  defaultShortTermDebt: 400000,
  defaultAccruedExpenses: 200000,
  defaultAnnualRevenue: 10000000,
  defaultAnnualCogs: 6000000,
  defaultCostOfCapital: 12,
  primaryResult: {
    key: 'netWorkingCapital',
    label: 'Net Working Capital (NWC)',
  },
  ratioBarItems: [
    { key: 'totalCurrentAssets', label: 'Total Current Assets', colorClass: 'bg-primary' },
    { key: 'totalCurrentLiabilities', label: 'Total Current Liabilities', colorClass: 'bg-rose-500' },
  ],
  summaryItems: [
    { key: 'totalCurrentAssets', label: 'Total Current Assets' },
    { key: 'totalCurrentLiabilities', label: 'Total Current Liabilities' },
    { key: 'netWorkingCapital', label: 'Net Working Capital (Surplus/Deficit)', isTotal: true },
    { key: 'currentRatio', label: 'Current Ratio (Benchmark: 1.5 - 2.0)' },
    { key: 'quickRatio', label: 'Quick Acid-Test Ratio (Benchmark: ≥ 1.0)' },
    { key: 'cashConversionCycle', label: 'Cash Conversion Cycle (Days)' },
    { key: 'totalPotentialCashUnlock', label: 'Potential Working Capital Cash Unlock' },
  ],
  inputs: [
    {
      id: 'cash',
      type: 'number',
      label: 'Cash & Cash Equivalents',
      min: 0,
      max: 1000000000,
      step: 50000,
      prefix: '₹',
      default: 500000,
    },
    {
      id: 'accountsReceivable',
      type: 'number',
      label: 'Accounts Receivable (Trade Debtors)',
      min: 0,
      max: 1000000000,
      step: 50000,
      prefix: '₹',
      default: 1200000,
    },
    {
      id: 'inventory',
      type: 'number',
      label: 'Inventory (Raw Material, WIP & Stock)',
      min: 0,
      max: 1000000000,
      step: 50000,
      prefix: '₹',
      default: 800000,
    },
    {
      id: 'otherCurrentAssets',
      type: 'number',
      label: 'Prepaid & Other Current Assets',
      min: 0,
      max: 100000000,
      step: 10000,
      prefix: '₹',
      default: 100000,
    },
    {
      id: 'accountsPayable',
      type: 'number',
      label: 'Accounts Payable (Trade Creditors)',
      min: 0,
      max: 1000000000,
      step: 50000,
      prefix: '₹',
      default: 900000,
    },
    {
      id: 'shortTermDebt',
      type: 'number',
      label: 'Short-Term Debt & Bank Overdrafts',
      min: 0,
      max: 1000000000,
      step: 50000,
      prefix: '₹',
      default: 400000,
    },
    {
      id: 'accruedExpenses',
      type: 'number',
      label: 'Accrued Wages & Other Current Liabilities',
      min: 0,
      max: 100000000,
      step: 10000,
      prefix: '₹',
      default: 200000,
    },
    {
      id: 'annualRevenue',
      type: 'number',
      label: 'Annual Gross Revenue / Sales',
      min: 100000,
      max: 10000000000,
      step: 500000,
      prefix: '₹',
      default: 10000000,
    },
    {
      id: 'annualCogs',
      type: 'number',
      label: 'Annual Cost of Goods Sold (COGS)',
      min: 100000,
      max: 10000000000,
      step: 500000,
      prefix: '₹',
      default: 6000000,
    },
    {
      id: 'costOfCapital',
      type: 'number',
      label: 'Overdraft / Borrowing Rate (%)',
      min: 0,
      max: 50,
      step: 0.5,
      suffix: '%',
      default: 12,
    },
  ],
};
