/**
 * Yield Farming APY Calculator Configuration & Educational Presets
 * Sprint 88 / Flagship #95
 * 
 * Note: Presets represent educational analytical scenarios for DeFi yield modeling.
 * They do not constitute live protocol data, guaranteed yields, or financial advice.
 */

export const YIELD_FARMING_APY_CONFIG = {
  id: 'yield-farming-apy-calculator',
  title: 'Yield Farming APY Calculator',
  category: 'crypto',
  categoryName: 'Crypto Calculators',
  version: '3.0.0',
  author: 'Fintools Find DeFi Quantitative Research Board',
  lastUpdated: '2026-08-28',

  defaults: {
    initialDeposit: 10000,
    rateMode: 'APR',
    interestRate: 30,
    compoundingFrequency: 'DAILY',
    farmingDurationDays: 90,
    depositFeePct: 0,
    performanceFeePct: 2,
    withdrawalFeePct: 0,
    isRewardTokenVolatile: false,
    initialRewardTokenPrice: 10,
    finalRewardTokenPrice: 10,
    isLpMode: false,
    lpPriceRatio: 1.0,
    currency: 'USD',
    poolName: 'DeFi Liquidity Farm',
  },

  presets: [
    {
      id: 'daily_compounding_20apr',
      label: 'Auto-Compounding Vault (20% APR)',
      icon: '⚡',
      initialDeposit: 10000,
      rateMode: 'APR',
      interestRate: 20,
      compoundingFrequency: 'DAILY',
      farmingDurationDays: 90,
      depositFeePct: 0,
      performanceFeePct: 2,
      withdrawalFeePct: 0,
      isRewardTokenVolatile: false,
      currency: 'USD',
      poolName: 'Yearn / Beefy Auto-Vault',
      desc: '20% APR Daily Compounding · 22.13% APY · 2% Performance Fee',
    },
    {
      id: 'monthly_compounding_12apr',
      label: 'Monthly DeFi Staking (12% APR)',
      icon: '📅',
      initialDeposit: 10000,
      rateMode: 'APR',
      interestRate: 12,
      compoundingFrequency: 'MONTHLY',
      farmingDurationDays: 180,
      depositFeePct: 0,
      performanceFeePct: 0,
      withdrawalFeePct: 0,
      isRewardTokenVolatile: false,
      currency: 'USD',
      poolName: 'Monthly Compound Farm',
      desc: '12% APR Monthly Compounding · 12.68% APY · 6 Months Duration',
    },
    {
      id: 'high_yield_high_fee',
      label: 'High-Yield / High-Fee Farm (80% APR)',
      icon: '🔥',
      initialDeposit: 10000,
      rateMode: 'APR',
      interestRate: 80,
      compoundingFrequency: 'DAILY',
      farmingDurationDays: 60,
      depositFeePct: 3.0,
      performanceFeePct: 4.0,
      withdrawalFeePct: 1.5,
      isRewardTokenVolatile: false,
      currency: 'USD',
      poolName: 'Degenerative High-Yield Farm',
      desc: '80% APR with 3% Deposit & 1.5% Exit Fees · Fee Drag Analysis',
    },
    {
      id: 'stablecoin_farming_low_risk',
      label: 'Stablecoin Pair Farm (8% APR)',
      icon: '🛡️',
      initialDeposit: 25000,
      rateMode: 'APR',
      interestRate: 8,
      compoundingFrequency: 'DAILY',
      farmingDurationDays: 365,
      depositFeePct: 0,
      performanceFeePct: 1.0,
      withdrawalFeePct: 0,
      isRewardTokenVolatile: false,
      currency: 'USD',
      poolName: 'USDC / USDT Stable Farm',
      desc: '$25,000 Deposit · 8.33% APY · Near-Zero Impermanent Loss Risk',
    },
    {
      id: 'reward_token_depreciation',
      label: 'Reward Token Price Drop (-60%)',
      icon: '📉',
      initialDeposit: 10000,
      rateMode: 'APR',
      interestRate: 60,
      compoundingFrequency: 'DAILY',
      farmingDurationDays: 90,
      depositFeePct: 0,
      performanceFeePct: 2.0,
      withdrawalFeePct: 0,
      isRewardTokenVolatile: true,
      initialRewardTokenPrice: 10,
      finalRewardTokenPrice: 4,
      currency: 'USD',
      poolName: 'Volatile Farm Token Pool',
      desc: '60% APR Farm · Reward Token drops from $10 to $4 (-60% price drag)',
    },
    {
      id: 'lp_farming_with_il',
      label: 'LP Farming + 2x Relative Price Move',
      icon: '🔄',
      initialDeposit: 10000,
      rateMode: 'APR',
      interestRate: 35,
      compoundingFrequency: 'DAILY',
      farmingDurationDays: 180,
      depositFeePct: 0,
      performanceFeePct: 2.0,
      withdrawalFeePct: 0,
      isLpMode: true,
      lpPriceRatio: 2.0,
      currency: 'USD',
      poolName: 'ETH / USDC LP Yield Farm',
      desc: '35% Farming Yield offset against -5.72% Impermanent Loss ($10k LP)',
    },
  ],
};
